### ISSUE TITLE
Design "Add new Item" 

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1021]
goal: define design and position of "add new item" for collections

### Problem
The collections needs a standard way to display a button to Add new items

### Tasks
- [x] Define design and behaviour for uses cases
- [ ] Visuals
- [ ] Update files on Box and Zeplin
- [ ] Document

### Uses cases
1. The page display a single collection. The collection should be displayed with a title reflecting the content of the collection for example "Projects". To the right will be a text button with a *filled plus* icon and the corresponding object, like: "[+] Project"

    ![image](https://user-images.githubusercontent.com/22662903/30551807-10544b38-9c9c-11e7-9afc-e981e541a5ed.png)

2. On 2 columns layouts the Collection title and "add button" are adjacent to the corresponding collection.

    ![image](https://user-images.githubusercontent.com/22662903/30551895-6b4ada5c-9c9c-11e7-9b34-4cb81ed121dc.png)

3. On collections with **ToolBar** the "add button" will be placed at the end of the main road.

    ![image](https://user-images.githubusercontent.com/22662903/30551860-49f99e6a-9c9c-11e7-9fd6-e4cb38661b61.png)

### Responsive behaviour

1. On collections without **Toolbar** the behaviour stays the same

    ![image](https://user-images.githubusercontent.com/22662903/30551968-ade05702-9c9c-11e7-98d1-aeb84465e7bf.png)

2. With the **ToolBar** the caption of the button is hidden to save space

    ![image](https://user-images.githubusercontent.com/22662903/30551995-c5734712-9c9c-11e7-8ee4-5c47cacaa07b.png)

**Comment by LeoT7508** [comment]
@joseegm 

Im still waiting on uploading the visuals for this because I'm experimenting with changing the typeface and it will effect some of these details.

**Comment by joseegm** [comment]
Reorganized the placement of the filters/visualisations all to the left and all the actions to the right

![image](https://user-images.githubusercontent.com/22662903/31077261-2df5f622-a77e-11e7-9960-b2cfc564609c.png)

During this, realised we are going to have a space problem when there is more than 2 actions. That's why I think we are better of with only recommending icon-buttons for the actions. 

![image](https://user-images.githubusercontent.com/22662903/31077417-b5d7b83c-a77e-11e7-84a2-b7d751c8658e.png)

**Comment by LeoT7508** [comment]
@joseegm @xak 

Why not group the controls this way? 

Also, there was discussion about not ever having the "+" icon in the Title Bar, the thought was to always have it connected to the section it was affecting, an example would be right above a list, or right about a grid of cards. 

![techne_2 0_title bar 3](https://user-images.githubusercontent.com/28761982/31097021-836c4ce6-a783-11e7-803f-ff170ac363d6.png)

**Comment by joseegm** [comment]
They are positioned by most common usage: filtering, sorting, change view. 

We talked about the "Add item" button the other day and we decided to have two versions. One when the list doesn't have a toolbar and the other with the toolbar. The rationale behind it, is that the lists without toolbars always have the title, so we can put the add button there. The ones with toolbar usually doesn't have the title.

Also we need a way to display other "actions" on the toolbar, like "delete", "clone", etc.

**Comment by LeoT7508** [comment]
@joseegm 

I made a small adjustment to tables to accommodate Panel options above. Overall this works best from a visual side of things. I think its the best solution we have. 

![screen shot 2017-10-05 at 12 32 52 pm](https://user-images.githubusercontent.com/28761982/31242331-50781b4e-a9cc-11e7-9acb-bb0139d73989.png)
![screen shot 2017-10-05 at 12 50 54 pm](https://user-images.githubusercontent.com/28761982/31242333-5080b538-a9cc-11e7-98cb-c223a9c93427.png)
![screen shot 2017-10-05 at 12 51 05 pm](https://user-images.githubusercontent.com/28761982/31242332-50808e64-a9cc-11e7-80a2-374c8cb8505d.png)

**Comment by joseegm** [comment]
Great!

The actions at the top of the "collection" area looks great. Also when there is no title.

The addition of the top border to the table looks good as well, we need to see how it looks with the toolbar.

@LeoT7508 
Can you please put together an example with. "add, clone, delete" actions + tool bar + table? Thanks

**Comment by LeoT7508** [comment]
@joseegm 
 
Example with all tools included. 

![stater page - table- 3 column 1440](https://user-images.githubusercontent.com/28761982/31284327-d54f2cb6-aa7d-11e7-9a34-6c9eb4e89cf0.png)

**Comment by joseegm** [comment]
@LeoT7508 
Can we have the same margin from the toolbar to the "add, clone, delete" actions as to the table border?
After that I think we are good to go.

**Comment by LeoT7508** [comment]
@joseegm 

The margins for the whole page is 20px. For consistency we should stick to that.
