### ISSUE TITLE
Pkg: Icon updates

### ISSUE THREAD

**Issue by LeoT7508** [SAP/techne#1030]
# Workflow

- [x] Develop
- [x] Design review
- [x] Code review
- [x] Merge to `dev`

All 1.5 icons have been updated to match the new design system. 
SVG files can be found on box here:
https://hybris.box.com/s/bzssyy0155zlvjezbct1mgbp944w0dnq

All new icons must pass through design before being added to this folder.

**Comment by saadmhybris** [comment]
@LeoT7508  - can't seem to find the icon files at the link, can you pls double check? we need them to be SVG file of a consistent file which you already know...
