### ISSUE TITLE
Ops: Fix CDN versioning.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#1032]
**Current Temp solution:**  update bamboo config by hand - https://bamboo.hybris.com/build/admin/edit/editBuildTasks.action?buildKey=PTW-USPRODTECHNE2-DJ

**Solutions must:** 
- maintain a minified, uncompressed CSS and icon fonts for all released versions
- fully automated so we don't have to do anything by hand
- no dependency on yaas domain 
- possibly independent of bamboo

**Comment by saadmhybris** [comment]
@derberg - please let me know if you have any ideas for this

**Comment by derberg** [comment]
just to clarify requirements, 
* you want to expose techne.min.css and techne.css not only for latest but for previous versions too? and you do not want to do it here https://techne.yaas.io/libs/techne/2.0.0-alpha-3/techne.min.css but sap.github.io/techne/libs/techne/2.0.0-alpha-3/techne.min.css ?
* what is your current release process? I looked into your package.json but there are no release scripts and it is hard for me to figure out how you do the release. For example I have a couple of scripts for my personal project https://github.com/derberg/arghun/blob/master/package.json

From the technical point of view, what has to be done:
- https://github.com/SAP/techne/blob/v2.0/.travis.yml must be extended so it not only builds a site, but also does the css build
- then I would extend https://github.com/SAP/techne/blob/v2.0/ops/gulp/ghpages-deploy.js to grab those generated files and place them also in ghpages branch so they are available under sap.github.io/techne. You can get the current version that you are building for from the package.json like this, so you can use it as a value to build directory with css files:
```
var pjson = require('./package.json');
console.log(pjson.version);
```

You want to give it a try or should I do that for ya?

**Comment by saadmhybris** [comment]
- The release process is still evolving. Since we are in alpha we are not publishing releases on GitHub for now, maybe we should start doing this as there is no way to maintain each release. 
- The release process is documented here - https://github.com/SAP/techne/wiki/Release-Process
- Also, Techne 2.0 will be renamed to Fundamental UI and moved to the new GitHub repo. So we need to account for this impending change as well.

**Comment by derberg** [comment]
- looks like you do release on github https://github.com/SAP/techne/releases
- what is the timeframe for the rename, as it kind of means another name change for the CDN

**Comment by saadmhybris** [comment]
- yes. we do release on github, but currently not putting out each version of alpha. 
- it could be a while for the name change as we need to get an approval for another open source repo.

**Comment by derberg** [comment]
if techne is already approved and you are just changing the name...why can't you just change the name of this repo? techne link will still work anyway as github assures redirects for old links

**Comment by saadmhybris** [comment]
We haven't gotten to that point yet, but we also wanted to maintain techne 1.5 for a while and this new name will also be a version 1.0 instead of 2.0 of techne.

**Comment by saadmhybris** [comment]
We are starting to talk about the name change and beta transition process. in the meantime, we will maintain an archived copy of previous versions so that the old CDN links are not broken. We would still need to work out a more permanent solution for this when FUI hits beta. :)
