### ISSUE TITLE
Icons are missing in scss files in Techne 2

### ISSUE THREAD

**Issue by akucharska** [SAP/techne#1040]
Icons are missing after install of techne@2.0.0-alpha-3 in scss files.

Also in toolbar.css you have wrong path`src: url(components/TechneIcons.woff2)` but TechneIcons.woff2 is in dist folder not in dist/components

**Comment by saadmhybris** [comment]
HI, @akucharska - Thanks for your feedback You can grab the icons scss files from here for the time being - https://github.com/SAP/techne/tree/v2.0/scss/icons

We will address both of your issues in the next release.
