### ISSUE TITLE
Recolor the starter page Elements

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1044]
goal: makes a better color scheme for the elements of the starter page

### Problem
The Starter page top elements: ActionBar, help and ToolBar are all gray
![screen shot 2017-09-21 at 11 17 17](https://user-images.githubusercontent.com/22662903/30688991-ed5105ce-9ebf-11e7-870a-af62cbeb5801.png)

It makes the page loos very heavy and like all the 3 top components belong together somehow.

I experimented a little but still didn't arrive to a satisfactory solution.

![screen shot 2017-09-21 at 11 17 26](https://user-images.githubusercontent.com/22662903/30689035-0fc68f48-9ec0-11e7-8609-77df5dfa9a82.png)
This is just an example.

@LeoT7508 
Can you please play a little more with the 3 components backgrounds and try to make them like they are different components.

**Comment by LeoT7508** [comment]
@joseegm 

The goal for all these elements was to push back all the tools visually and bring the content forward with white space to put emphasis on content. The only suggestion I can make is to find another place for that page description text. For example, in the title bar with the title somehow to minimize the amount of vertical space those elements take up. Adding different colored strips to differentiate sections becomes distracting. From a design side this is the solution. The next best thing is to figure out a way to minimize and consolidate the content from a UX side.
