### ISSUE TITLE
Fix the disabled state for the Action Bar buttons

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1049]
goal: Fix the visual design for the action bar Buttons when they are disabled.

### Problem
![screen shot 2017-09-22 at 14 22 04](https://user-images.githubusercontent.com/22662903/30744255-8b31d4d0-9fa1-11e7-8f77-95fb611e921d.png)
The visual design for the "disabled" state on the Action Bar buttons is too contrasting with the rest of the component.

**Comment by LeoT7508** [comment]
All guidelines for Icon Button are detailed here:

![techne_2 0_icon button guidelines](https://user-images.githubusercontent.com/28761982/30879986-b96e178c-a2c6-11e7-90ab-35dfb3b55906.png)

**Comment by joseegm** [comment]
@LeoT7508 
Very good, thanks, then is a implementation bug.

@saadmhybris 
Can you please add a new issue to correct this one?
Thanks.
