### ISSUE TITLE
Pkg: Add animation to hover effects

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1055]
goal: improve a consistent behaviour for the hover effect.

### Problem
There are elements with hover effect, some have animation, some not.

### Affected components
1. Inputs
2. Select
3. Dropdown
4. Table: row hover
5. Buttons

**Comment by saadmhybris** [comment]
@joseegm I inadvertently pushed changes for this ticket in #1054 PR. Please review changes for both ticket here - https://github.com/SAP/techne/pull/1094

sorry for the incontinence

**Comment by joseegm** [comment]
Looks good as well
