### ISSUE TITLE
Design Loading animations

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1073]
goal: improve and diversify the loader indicators.

### Prior art
![screen shot 2017-09-29 at 11 35 51](https://user-images.githubusercontent.com/22662903/31010231-607cd7f8-a50a-11e7-8dfa-24149cfcad8c.png)

### Pain points
- Now is done via CSS and HTML which make the markup complex
- There is only one size for all the loaders

### Tasks
- [x] Define types of loaders and the uses cases
- [x] Visuals
- [ ] Document

**Comment by joseegm** [comment]
### User cases

1. Global loader element, that is animated, with an element overlapping the whole page. It is use to when waiting for the whole content of the page to load.

  ![image](https://user-images.githubusercontent.com/22662903/31338060-29a22ad4-acfe-11e7-8434-3ba385c293c3.png)

2. Local loader element, like the global loader element, same element overlapping the part of page waiting to load.

  ![image](https://user-images.githubusercontent.com/22662903/31338232-b1013178-acfe-11e7-9868-5cfca99335fe.png)

**Comment by joseegm** [comment]
@LeoT7508 
This are the two cases. We are good to decide which shape and animation we use.

**Comment by LeoT7508** [comment]
@joseegm @xak 

We looked around and picked a pretty simple one, should scale easily enough. If you see any issues let me know. 

http://github.danielcardoso.net/load-awesome/animations/line-scale.html

**Comment by joseegm** [comment]
That one looks good. Generic, so it won't be an issue incorporate it in the **two needed sizes**. 

@xak 
The HTML is simple enough I guess

**Comment by xak** [comment]
I'm fine using this one, however, if we can reduce it to 4 bars (from 5) I can do it with one DIV.

```
<div class="tn-spinner">
    <div></div>
</div>
```

Also, please put up a design with color, sizes, etc. I'm coding this so that any container should be able to have spinner inside, whether it be the whole page, a section, a panel, etc.

**Comment by joseegm** [comment]
Four bars is fine for me.
