### ISSUE TITLE
Table & Tree update

### ISSUE THREAD

**Issue by LeoT7508** [SAP/techne#1095]
To accommodate Panel controls/options we will add a 1px rule above the table column headers to create better positioning for the options above. 

- The padding above the column headers should be the same as padding below the labels. 

![screen shot 2017-10-05 at 11 49 52 am](https://user-images.githubusercontent.com/28761982/31241400-5deabea6-a9c9-11e7-9f28-75d314d91e18.png)
![screen shot 2017-10-05 at 11 50 04 am](https://user-images.githubusercontent.com/28761982/31241402-5dfc1c96-a9c9-11e7-8425-5f6b555ec1f3.png)
![screen shot 2017-10-05 at 12 32 52 pm](https://user-images.githubusercontent.com/28761982/31241401-5dfa2f9e-a9c9-11e7-84be-729319165dd6.png)

**Comment by xak** [comment]
This has already been implemented.
