### ISSUE TITLE
Fix Cards text decoration when using an <a> elements as card elment

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1098]
### Problem

When an `<a>` element is used to construct the card elements all text inside the card us underlined when the cursor hovers the element.

![screen shot 2017-10-06 at 15 06 51](https://user-images.githubusercontent.com/22662903/31279101-03ebb2b8-aaa8-11e7-9f0e-2e9609fada67.png)

**Comment by xak** [comment]
@joseegm I'm not seeing this bug now. Can you verify this is still a problem?

**Comment by joseegm** [comment]
Yep Problem still there.

http://sap.github.io/techne/components.html

![screen shot 2017-12-13 at 11 54 04](https://user-images.githubusercontent.com/22662903/33935489-683601f4-dffc-11e7-85ea-ddc5e9f10f75.png)
