### ISSUE TITLE
Pkg: Fonts should be opt-in

### ISSUE THREAD

**Issue by xak** [SAP/techne#1112]
Fonts are currently hard coded into `all.scss`. They should be explicitly set into a theme or fonts file so they can be replaced. Now they always get downloaded whether you want them or not.

Also, should set an explicit font stack for each font type.

**Comment by joseegm** [comment]
This is good! We should include the fonts as part of the theme settings and not directly on the library. The library will work with the standard platform font.

**Comment by xak** [comment]
@saadmhybris Since we are tying fonts to specific themes, I recommend creating a Techne theme file at `scss/theme/techne.scss`. In that file, only include the fonts and the `tn-fonts` variable declaration - remove the `!default` - from `_settings.scss`

In `_settings.scss`, change `tn-fonts` to the browser defaults only. Then in `all.scss` uncomment the theme line and set that as your theme file. This will essentially preserve the Techne look and feel which is intentionally buried in `core/_settings.scss` but separates the fonts.

I think this is better than hardcoding them in the starter HTML `head`.
