### ISSUE TITLE
Pkg: Fix disable actions style on Actionbar

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1139]
### Problem
![screen shot 2017-10-18 at 14 38 41](https://user-images.githubusercontent.com/22662903/31718985-37d06290-b412-11e7-85c2-290544d85a23.png)
This happens when the button element have only the disabled parameter
```html
<button class="tn-button tn-button--text tn-button--action-bar" disabled>
                <span class="tn-icon tn-icon--edit tn-icon--medium" role="presentation"></span>
                Customize
</button>
```

needs to be similar to 
![screen shot 2017-10-25 at 14 55 01](https://user-images.githubusercontent.com/2720077/32001083-fa12edce-b998-11e7-9a61-9aa986505eb1.png)

**Comment by xak** [comment]
This is the same issue as #1143. It's been fixed.
