### ISSUE TITLE
Should the Card single action be a button or a link?

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1141]
at
http://sap.github.io/techne/card.html#actions-card
The Actions is selected as link not a button, is that correct?

**Comment by saadmhybris** [comment]
I think it does not make a huge difference since you could put ngClick on virtually any element.

**Comment by joseegm** [comment]
Yes but the it looks different from the text button... It gets underlined when hovered

**Comment by xak** [comment]
The implementation looks correct to me. I'm not sure what you mean by a link not a button. If you are talking about the dropdown options the in this particular case, the `a`s **should** have an `href` attribute or `role=button`. 

The dropdown component was build to be very flexible. It would be also be possible to use the `li`s.
```
<li class="tn-dropdown__item" role="button">Pellentesque metus</li>
``` 

The most important thing is that `[role="button]` be applied to the element when it used as a button but is not an actual `button` element. Similarly, if it's a link, it should be an `a` or use `[role="link"]`.
