### ISSUE TITLE
Reduce the spacing between the label and the inputs

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1164]
### Problem
The spacing is a little too much. There is no really a separation between the Label and Input group from one another

![screen shot 2017-10-24 at 15 32 00](https://user-images.githubusercontent.com/22662903/31945815-87af7f5e-b8d0-11e7-983e-61c28055cf84.png)

**Reducing** the spacing will bring the label with the corresponding input close together

![screen shot 2017-10-24 at 15 29 49](https://user-images.githubusercontent.com/22662903/31945858-a3d07882-b8d0-11e7-8702-dc73fd7c635d.png)
This screenshot is reducing the padding from 12px to 4px

**Comment by joseegm** [comment]
@LeoT7508 
We got this in our round of feedback from SNK. It looks better with close space, maybe with more space between groups but we need to change as it is right now.

**Comment by LeoT7508** [comment]
@joseegm 

The spacing for field labels to fields is actually 8px. 

Vertical spacing between fields in a column is 32px. 

This will not change.

**Comment by joseegm** [comment]
@LeoT7508 
This needs to change now because is not easy to see which label belongs to what input.

**Comment by LeoT7508** [comment]
@joseegm 

I went over this with Zack, he had to make an update to the build to match the visuals on Zeplin so there was a small discrepancy in the version you were looking at. However the updated version is correct. When he finishes his updates and pushes the fresh code you should be able to see the right spacing.
