### ISSUE TITLE
Revisit Text button hover effect

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1166]
### Problem
The hover effect of the text Button is not noticeable.

![screen shot 2017-10-24 at 15 39 50](https://user-images.githubusercontent.com/22662903/31946252-9b2ae446-b8d1-11e7-9ffd-7bfcb22e1d50.png)
Note: the first button here is hovered

Maybe we can add a very light background when hovered that will display the whole button and the current dimensions as well.

![screen shot 2017-10-24 at 15 43 21](https://user-images.githubusercontent.com/22662903/31946439-1ba59eb8-b8d2-11e7-84ed-7a2e22e2410a.png)

**Comment by LeoT7508** [comment]
This is already done, the hover state for this button is an underline.

**Comment by joseegm** [comment]
@LeoT7508 
Nope. That is for the Link Buton: http://sap.github.io/techne/button.html#link-button
Which have a different function.

This issue is for the normal Text button: http://sap.github.io/techne/button.html#text-button-sizes

Underlying the text won't work when the button have an icon. We need a more visible effect here.

**Comment by LeoT7508** [comment]
@joseegm 

The action of the small hand appearing on hover along with the color change should be enough, this hover state follows all the other instances we have now. We shouldn't make a special case for one.

**Comment by joseegm** [comment]
@LeoT7508 
That's the problem, the hover color is not noticeable mostly. As posted before we got that feedback from the team used the library.

**Comment by LeoT7508** [comment]
@joseegm 

These buttons don't have to have an extremely noticeable hover. The highlight color differentiates this from titles, body copy, or H labels. Again the size, color, subtle hover affect, and the small hand on hover is more than enough to tell the user this is an action. 

If you want examples of this in use, check Material Design or Lightening, they both have text & text icon buttons without a dramatic hover affect and in many cases no hover affect. They use color to show separation and actions vs read only text and labels. 

We will stick to the pattern we created.

**Comment by joseegm** [comment]
@LeoT7508 
It's actually needed.

Material have the same background effect that was suggested.
<img width="557" alt="screen shot 2017-11-02 at 17 17 27" src="https://user-images.githubusercontent.com/22662903/32337283-da45a5ea-bff1-11e7-9635-01872d2d209a.png">

<img width="578" alt="screen shot 2017-11-02 at 17 17 36" src="https://user-images.githubusercontent.com/22662903/32337296-df62899e-bff1-11e7-9bf5-40dbb6f4c61f.png">

<img width="572" alt="screen shot 2017-11-02 at 17 17 44" src="https://user-images.githubusercontent.com/22662903/32337300-e547d1de-bff1-11e7-9ada-beaef4dbf21d.png">

**Comment by LeoT7508** [comment]
@joseegm 

False. Log into your account and check My Account page, none of those buttons have a hover affect. 

![screen shot 2017-11-02 at 11 19 48 am](https://user-images.githubusercontent.com/28761982/32337414-f46b86f6-bfbf-11e7-8e17-f7272c290c84.png)

Not all buttons are created equal.

**Comment by joseegm** [comment]
@LeoT7508 
Those on "my account" are not buttons are links.

On their last implementation they have it
implementation: https://material.angular.io/components/button/examples
design specs: https://material-components-web.appspot.com/button.html (scroll to CSS Only, at the bottom of the page)

**Comment by LeoT7508** [comment]
@joseegm 

That's still not a valid reason to change our patterns. The point is there is different buttons for different scenarios, the examples I provided prove that point clearly. The pattern will stay as is.
