### ISSUE TITLE
Pkg: Fix tool bar icons.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#1174]
- remove filter icon is missing 
- slight alignment issues on filer toggle icon. 
<img width="470" alt="screen shot 2017-10-31 at 11 15 29 am" src="https://user-images.githubusercontent.com/15215400/32235648-0bb88ba8-be2e-11e7-9364-3ac1410dcd35.png">

**Comment by xak** [comment]
@saadmhybris The icons are fixed with PR #1170 —  https://github.com/SAP/techne/pull/1170/files#diff-b83e54035739031251bc3df22b6b2acb

The alignment is a related to the dropdown component. It looks worse without the Open Sans font.

**Comment by saadmhybris** [comment]
@xak we can use this task to add the filter-remove icon back to match the original design. the close icon does not look good at all.

**Comment by xak** [comment]
Sure.
