### ISSUE TITLE
Pkg: Make placeholder images available via CDN

### ISSUE THREAD

**Issue by xak** [SAP/techne#1175]
# User and product thumbnails
https://zpl.io/Vqy7x1l
https://zpl.io/2jZN8Z6

> NOTE: Use @2x retina image for each, meaning they will be 2x the actual size.

Use a logical naming system, e.g., `placeholder-user-xl.png`
```
user-thumb-placeholder-{size}.png
product-thumb-placeholder-{size}.png
```
Include the largest size of each as a default with no size, e.g., `placeholder-user.png`. And include the largest size as an SVG.

# Product images
https://zpl.io/bW4MRQn
```
product-image-placeholder-hat.jpg
product-image-placeholder-glasses.jpg
product-image-placeholder-mug.jpg
```
Go ahead and include @2x versions in addition to those above, i.e., `product-image-placeholder-hat@2x.jpg`. 

And choose the one you like best and make that `product-image-placeholder.jpg` for ease of remembering.

**Comment by xak** [comment]
@saadmhybris Would like your input on this one? Should we version these or just make them available in the CDN root?

Also, related to #1084, it would also be possible to use data-uris in the CSS as the "fallback" image. With only two images (in SVG form) it wouldn't be that much data. I'm already doing this for the `select` and `tn-dropdown` toggle image — https://github.com/SAP/techne/blob/v2.0/scss/core/_settings.scss#L151 — since `select`s don't support `::after` and `::before` pseudos you have to use a background.

Generally, I'd love to avoid managing images in the project.

**Comment by xak** [comment]
@LeoT7508 and @jinjiahuangsap See above. Can you please provide the images as spec'ed below?

### Thumbnails
We only need the square image but we need @1x and @2x sizes of each named like such ...
```
user-thumb-placeholder-xs.png
user-thumb-placeholder-xs@2x.png
```
That should result in 12 images of each type for a total of 24 images.

### Product images
We need each of the three images in @1x and @2x sizes.
```
product-image-placeholder-hat.jpg
product-image-placeholder-hat@2x.jpg
```
That should result in 2 images of each type for a total of 6 images.

> NOTE: A 2x of 510px at 1020px is pretty big. I'll leave it you guys to determine what you think the largest size should be and then give us 2x that. [This edge case](zpl://screen?pid=598cce4ab8aced8f15a420a1&sid=59de810bcc36c261421acc73) should be rare.

**Comment by xak** [comment]
@LeoT7508 and @jinjiahuangsap We've determined a different approach to the placeholders, can you guys supply the largest SVG version of the profile and product placeholder images?

```
user-thumb-placeholder.svg
product-thumb-placeholder.svg
```

I do **not** need all the other versions of these two, only the SVG. 

However, please supply the Product images (the photographs) in JPG format as described above.

**Comment by xak** [comment]
@LeoT7508 and @jinjiahuangsap Just realized I also need the pixely image used as the example.

<img width="202" alt="screen shot 2017-11-06 at 11 44 45 am" src="https://user-images.githubusercontent.com/424119/32455468-ffb0c3b6-c2e7-11e7-90a7-63be84b8f5ab.png">

The largest size is fine.

**Comment by saadmhybris** [comment]
in progress... waiting on @LeoT7508  or @jinjiahuangsap to supply images

**Comment by LeoT7508** [comment]
@xak @saadmhybris 

Waiting for Jinjia he has the source file, should be ready to go tomorrow.

**Comment by jinjiahuangsap** [comment]
[product:user placeholder.zip](https://github.com/SAP/techne/files/1450673/product.user.placeholder.zip)

**Comment by xak** [comment]
@jinjiahuangsap The attached has ...

```
product-image-placeholder-hat.jpg
product-image-placeholder-hat@2x.png
product-image-placeholder-mug.jpg
product-image-placeholder-mug@2x.png
product-image-placeholder-sunglasses.jpg
product-image-placeholder-sunglasses@2x.png
```

Can you replace the PNGs to be JPGs? We want all JPGs.

**Comment by jinjiahuangsap** [comment]
[product:user placeholder.zip](https://github.com/SAP/techne/files/1454460/product.user.placeholder.zip)
