### ISSUE TITLE
Home page (Website)

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1194]
Here is the wire for the home page:
![image](https://user-images.githubusercontent.com/24274321/32901148-ca61cd02-cab4-11e7-901a-a6f8422e55f0.png)

Next, it will need to go to @LeoT7508 for visuals.

**Comment by joseegm** [comment]
Before going to Visual Design.

1. On the Designers part:
  - The link to "Styles" is missing, there the principles, colors, spacing etc.
2. On the Developers part:
  - Get started is fine
  - Link to components
  - Link to layouts and starter pages

We can leave the design request for now.

The ask a question will link probably to "fundamental at sap dot com"

**Comment by gcho1023** [comment]
On the designers part, they can view all the "style" information when they go to "Getting started" content. There are no "Styles" page... so link to the the UI Guideline?

<img width="972" alt="screen shot 2017-11-07 at 9 12 27 am" src="https://user-images.githubusercontent.com/32933889/32500749-d24f22aa-c39b-11e7-99e7-bd6ac98a1424.png">

**Comment by jeannewalters** [comment]
I updated the wires above based on discussions over the last few days.

**Comment by LeoT7508** [comment]
@joseegm 

This design is final for the Home Page. We can move it to development. 

![fundamentalui_website_home page_gradient - medium v2](https://user-images.githubusercontent.com/28761982/33679981-d1bd4ab4-da85-11e7-8a20-5d59cf14fc05.jpg)
