### ISSUE TITLE
Docs: Implement panels

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#1199]
panels components completed under - https://github.com/SAP/techne/issues/1082

**Comment by saadmhybris** [comment]
need to discuss how to document this. maybe use illustrations and screenshots instead of actual code components.

**Comment by saadmhybris** [comment]
we need to figure out a better way to document layout pieces as just using code snippets will not be very effective. moving to alpha 8.

**Comment by joseegm** [comment]
this is already done
