### ISSUE TITLE
Responsive Grid System under UI Guidelines (Fundamental UI Website)

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1205]
- Define responsive grid system basic structure (what is the responsive grid system?)
- Break points info 
- Column and margin info
- Wire for the page, don't have content

**Comment by gcho1023** [comment]
A wire example of type of content for Grid system #
![responsive grid system](https://user-images.githubusercontent.com/32933889/32465913-c0a71a1c-c30a-11e7-997a-43345c532b06.png)

**Comment by joseegm** [comment]
@gcho1023 
We have defined the breakpoints for the major screens at https://github.com/SAP/techne/issues/739

**Comment by gcho1023** [comment]
@LeoT7508  @joseegm  This wire is an example of the type of content for explaining the design grid system. I think in our earlier call last week, we wanted to add this under UI Guideline page where the Styles are....do you think that page would be too long?

**Comment by joseegm** [comment]
@LeoT7508 
I guess the only things missing are the illustrations

**Comment by LeoT7508** [comment]
@joseegm 

Jinjia is working on this. Should be in a good place soon.

**Comment by joseegm** [comment]
Designs done, discussed and on zeplin
https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/screen/5a1ed4ccc62383cab68709bb

<img width="640" alt="screen shot 2017-11-30 at 09 43 18" src="https://user-images.githubusercontent.com/22662903/33421670-272c98f6-d5b3-11e7-8ce3-8ac87b0ac4bb.png">
