### ISSUE TITLE
Getting Started for Designers page (Fundamental UI website)

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1207]
A wire for type of content needed for designers

**Comment by gcho1023** [comment]
Wires attached. Up for review and discussion.
![getting started designers](https://user-images.githubusercontent.com/32933889/32468227-0739592e-c313-11e7-9242-764f01da2a25.png)

**Comment by gcho1023** [comment]
Wires attached. Up for review and discussion. @joseegm 
![getting start designers](https://user-images.githubusercontent.com/32933889/32468266-2b730222-c313-11e7-9832-651aa6d2af1c.png)

**Comment by gcho1023** [comment]
We would need a ticket for the UI kit to be build.

**Comment by joseegm** [comment]
@gcho1023 
We had some Goals/principles for the new version already on 
https://github.com/SAP/techne/wiki/Techne-2.0-Goals

We need to merge those with the ones in here. Because we are not making emphasis on "mobile first" anymore. Thats not a goal for the new version. It works on mobile but is not mobile first.

Note: I'm investigating how to produce the UI Kit automatically, in  SVG format directly from the components. If that doesn't work as expected then we have to do it manually.

**Big question** this content could be added to the "Styles" (http://sap.github.io/techne/styles.html) page or do we need an extra page for this?

**Comment by gcho1023** [comment]
Techne goals are NOT design goals. It a holistic vision for the entire Fundamental UI. Mobile first is part of SAP Fiori Design guidelines, that is why I kept it there. Designers do not speak in business experience, we want to provide better user experience overall.

**Comment by joseegm** [comment]
Okay. But we want to turn down the "mobile first" emphasis we had before on Techne, which causes a lot of confusion and misunderstandings. 

So, I don't think we have to put it so prominently.

**Comment by gcho1023** [comment]
Updated 
![getting start designers](https://user-images.githubusercontent.com/32933889/32502072-639d5c42-c39f-11e7-9760-48058236bec0.png)

**Comment by gcho1023** [comment]
Also, I don't think it should be added to Style or UI Guideines page because it is overloaded with content and the designers will always get started in this area. We don't want content to be redundant.

**Comment by gcho1023** [comment]
Updated Wires 
![getting start designers](https://user-images.githubusercontent.com/32933889/32817778-4519def8-c985-11e7-9c25-152d32164de1.png)

**Comment by gcho1023** [comment]
https://6umx4d.axshare.com/#g=1&p=starterpage_designers @LeoT7508   all the pages should be in the same prototype

**Comment by joseegm** [comment]
@LeoT7508 
Can you please see if all the elements present on the wires have visuals on 
https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/screen/5a0c62563e7be3d263faef28

Also we need the Illustration for it.

**Comment by LeoT7508** [comment]
@joseegm 

Everything seems to be in order, unless the wires are changing.

**Comment by jeannewalters** [comment]
Below is the suggested content from UX for the UI Kit area. @LeoT7508 @joseegm 
![image](https://user-images.githubusercontent.com/24274321/33998852-6cbd68d6-e0ae-11e7-93aa-919f749f8487.png)

**Comment by jinjiahuangsap** [comment]
Team, here's the new update for the designer page: https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/screen/5a314d4cd96869711a718f99

![fundamentalui_website_ get started - designer](https://user-images.githubusercontent.com/32305332/34492499-7c3d19f6-efad-11e7-8e60-34f6b5f09a8b.jpg)

@joseegm @gcho1023 @jeannewalters
