### ISSUE TITLE
Use a common 3rd party CDN

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1212]
### Problem
Our current CDN deployment is not really a CDN and we dunno how long the site will stay up. And we have to manage it ourselves.

I did some investigation and it is slow.

https://techne.yaas.io/libs/techne/2.0.0-alpha-6/techne.min.css - more than 200ms to load 

There are services that CDN the NPM packages automatically without any work on our side. Just push the new NPM packages.

https://cdn.jsdelivr.net/npm/techne@2.0.0-alpha-6/dist/techne.min.css - less than 30ms 
https://unpkg.com/techne@2.0.0-alpha-6/dist/techne.min.css - less than 30ms 

**The question**: Should we link to one of these or take care of our CDN ourselves? 

I think few teams/products will consume the lib via CDN, that's why if we don't have to take care of that part it will be a gain.

**Comment by xak** [comment]
I'm fine with this. I prefer the latter only because the name is less JS specific but they both seem about the same. 

My only reservation is whether these services collect any data but neither have any kind of terms on their sites. I understand that the service is "available" and usable regardless of our consent so it probably doesn't matter much at the end of the day.

If @saadmhybris is on board, we should create a ticket to update CDN references.

**Comment by saadmhybris** [comment]
Like it! the second option for sure. one less thing to worry about.

**Comment by MartinKolarik** [comment]
@xak jsDelivr does have a privacy policy here: https://github.com/jsdelivr/jsdelivr#privacy-policy (I'm on the core team). We are also more focused on stability and production usage, compared to unpkg.com. Happy to answer any other questions you might have.

**Comment by joseegm** [comment]
@MartinKolarik 
Thanks for chiming it.

Any plans to make the final CDN urls a little more "friendly" like unpkg.com?

@xak @saadmhybris 
I like unpkg.com as well, shorter and simple URL, can be type by hand.

**Comment by MartinKolarik** [comment]
@joseegm our npm URLs have exactly the same format, except there's `npm` at the beginning, since we also support other registries than npm. That said, if you set `jsdelivr` field in `package.json` to `dist/techne.min.css`, you'll be able to use this shorter link: https://cdn.jsdelivr.net/npm/techne

**Comment by xak** [comment]
@joseegm This is all done, right?

**Comment by joseegm** [comment]
yep
