### ISSUE TITLE
Investigate and design the footer

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1215]
### Tasks
- [ ] Investigate and list what information we really need on the footer.
- [ ] Wireframes
- [ ] Visuals

**Comment by joseegm** [comment]
This is the footer of OpenUI5, so I guess we need to have most of that info on our as well.

![screen shot 2017-11-08 at 16 42 39](https://user-images.githubusercontent.com/22662903/32557970-f78e9b50-c4a3-11e7-8c35-e10640ede882.png)

**Comment by jeannewalters** [comment]
Here is a footer wire based on some other libraries.
![image](https://user-images.githubusercontent.com/24274321/32624717-b0d81afe-c54f-11e7-8730-88c6002b0fbc.png)

**Comment by joseegm** [comment]
@jeannewalters 
We still need all the links for the Legal/imprint, privacy etc, or they are on the "copyright info???" part? I don't think we have so much place in one line with the "Have a question" element...

**Comment by gcho1023** [comment]
<img width="792" alt="screen shot 2018-02-01 at 12 52 17 pm" src="https://user-images.githubusercontent.com/32933889/35697064-c7fbba56-074e-11e8-8c85-66ef8a97ace2.png">

Footer updates

**Comment by joseegm** [comment]
This is already on the website
