### ISSUE TITLE
Redesign the Top nav and the sidebar

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1216]
Revisit the Top nav and sidebar.

As we are going to base the whole navigation of the site on the sidebar. I think we can get away from the top nav, ala http://carbondesignsystem.com/ they only have Sidenav (with branding info) and the main content.

**Comment by jeannewalters** [comment]
Here is the latest wire for the top and side bar.
@LeoT7508 is working on wires to support 3 levels of a tree in the left nav. The Logo is a link back to Home so there is no "Home" nav item in the left (other than the logo). I've also attached the site map that documents what are pages and what are just expanding nav items.  We can discuss these tomorrow. Will the library website be fully responsive or adaptive?  I would like to discuss what options we have for the mobile library experience tomorrow as well.  @saadmhybris - let me know if there are other options in the base Github to modify the mobile experience.  

Wire:
![main_nav](https://user-images.githubusercontent.com/24274321/32806100-1231c21e-c951-11e7-8afd-d7bce5dc5202.png)

Site Map:
![site_map](https://user-images.githubusercontent.com/24274321/32806127-24230942-c951-11e7-922e-a99fcb8764bb.png)

**Comment by saadmhybris** [comment]
design in zeplin - 
https://zpl.io/Vq11Dr4
https://zpl.io/29NNXYe

**Comment by LeoT7508** [comment]
@saadmhybris 

I will break those individual components out in separate documents, I'm doing that now.

**Comment by saadmhybris** [comment]
Ok no problem.

**Comment by LeoT7508** [comment]
@jeannewalters @joseegm @saadmhybris 

These items are now on Zeplin in separate design sheets.
