### ISSUE TITLE
List all types, modifiers and states, etc.

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1217]
Get the info from the .scss file

**Comment by joseegm** [comment]
- Action Bar: Only components inside
- Alert: Types
- Button: Types, modifiers, states
- Card: Types, states
- Card Group: Types
- Dropdown: State
- Forms: Complex, Types, modifiers, states
- Icons: Types
- Input Group: Types
- List: Types of list item
- Pagination: none
- Status Indicators: Types, modifier
- Table: Modifier
- Toggle: Type, States
- Toolbar: Only the components inside
- Tree: Types of rows, Modifier
- Modal: Only components inside

**Comment by joseegm** [comment]
@jeannewalters 
Most of the components -the simple ones- can be fitted in the pattern, 
- Types
- Modifiers
- States

**Comment by jeannewalters** [comment]
@xak @joseegm I was looking at these components with states, types and modifiers - how would the right rail work? Would we have a combination of the state, type, modifier for each link in the right rail or would they be radio buttons like Lightning does it?  (https://www.lightningdesignsystem.com/components/accordion/?variant=base)
Based on our last meeting, I thought these links in the right rail would be jump links. 
Maybe to determine this, we will need the specific state, type and modifier (and/or combination) for each component - not just what they have as listed below.
Copying @LeoT7508 as part of this too.

**Comment by xak** [comment]
@jeannewalters I don't think we can do the Lightning approach for now.

In some instances like Buttons and Cards we are showing most modifications and states, in others like [Dropdown](http://sap.github.io/techne/dropdown.html) we aren't not showing **how** you open the menu — toggle `aria-expanded` and `aria-hidden` attributes _OR_ toggle class `is-expanded` and `is-hidden`. See https://github.com/SAP/techne/blob/v2.0/scss/components/dropdown.scss#L40

 The Lightning approach is very different, [selecting options to generate code and see examples](https://sapse.invisionapp.com/share/6NCQ6SNJE#/245274252_UI). Bootstrap is better example for [showing base and variants in the right rail](http://getbootstrap.com/docs/4.0/components/dropdowns/).

**Comment by joseegm** [comment]
Yes, I was all the time thinking in the Bootstrap variant that Zack linked in the previous post.
That's why we need a "pattern" to structure the documentation. So the right trail will link to the "subheaders" which in correspond to the right types, modifiers, etc.

**Comment by joseegm** [comment]
@jeannewalters 
Here is the list of concrete types, modifiers and states for the Button components so you can incorporate a real life example on the wires:

- **Types**: Standard, Text, Link, ActionBarButton, Contextual Menu
- **Modifiers**: With icon, Sizes (small, default, large)
- **State**: normal, selected, disabled

**Comment by jeannewalters** [comment]
Here is the button page. We can review it all together in the meeting.
![image](https://user-images.githubusercontent.com/24274321/33384636-2691e026-d4ec-11e7-8aa2-08f8bc786197.png)

**Comment by jeannewalters** [comment]
@joseegm @LeoT7508 Here is the updated button wire based on feedback from our call earlier today:
![image](https://user-images.githubusercontent.com/24274321/33395299-ac0c9fc0-d50a-11e7-8f4a-e9ab040cff3d.png)

**Comment by joseegm** [comment]
@jeannewalters 
This looks good. I'll start modifying the Buttons website page to reflect this new structure. That can be done in code. 

One small thing, do we need to have the "Usage" headline for every variation? I think with only the description will be fine. And only use "Usage: page1, page2" when linking to the starter pages. What you think?
