### ISSUE TITLE
UI Guidelines - Colors page for Fundamental UI website

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1235]
New wire added
https://6umx4d.axshare.com/#g=1&p=colors

**Comment by joseegm** [comment]
The current color page looks like this. 

![screen shot 2017-11-21 at 10 27 16](https://user-images.githubusercontent.com/22662903/33064611-9c8e2eca-cea6-11e7-9439-47277c270ad6.png)

The colors are divided in groups named according their use.

**Question** it will be nice to have a small place with text to describe every color group. How that will looks like?

**Comment by gcho1023** [comment]
I honestly don't think we need text for each section it the headlines are clear and relabeled like the wireframes.

**Comment by joseegm** [comment]
@gcho1023 
Fair enough. Do you think we keep the color representation we have now or have any other idea how to better represent those?
I will like optionally to have it all colors in one single screen and don't have to scroll to see them all. That's make it easy to find the right color.

**Comment by LeoT7508** [comment]
@joseegm 

I will work this out when I design the page.

**Comment by joseegm** [comment]
Designs discussed and approved and already on Zeplin
https://app.zeplin.io/project/59fc8d826e1e5e806854ddbf/screen/5a1eda5f8f7c54cf1af1effe

<img width="963" alt="screen shot 2017-11-30 at 09 40 12" src="https://user-images.githubusercontent.com/22662903/33421510-976e2b8a-d5b2-11e7-92a4-894802d93400.png">
