### ISSUE TITLE
UI Guidelines - Spacing page for Fundamental UI website

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1236]
New wire
![spacing](https://user-images.githubusercontent.com/32933889/32844977-3fb598b2-c9e9-11e7-93fc-c00ab1c1e339.png)

**Comment by joseegm** [comment]
@LeoT7508 
Any updates on this one?

**Comment by LeoT7508** [comment]
@joseegm 

No.

**Comment by joseegm** [comment]
@LeoT7508 
We can use a simplified version of this one to represent the spacing
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/59e5020327ee3d6b1ddf1abc

**Comment by LeoT7508** [comment]
@joseegm 

I think we need more guidance as to what we need to show here. We are already showing something very similar on the grid page. If we are going to take a deep dive into how we separate sections and panels then we will need more structure and information to explain that. 

Please provide a wire and more copy for that instance.

**Comment by gcho1023** [comment]
@LeoT7508  you know more about the spacing than we do. I just saw the spacing information in your zeplin file. give us examples of how spacing works... on H1 or between panels...

**Comment by LeoT7508** [comment]
@gcho1023 @joseegm 

I still need copy and how you want to structure this information. Unless you want me to make it up as I go, but I'm not a copywriter.
