### ISSUE TITLE
UI Guidelines - Typography page for Fundamental UI website

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1238]
New wire
![typography](https://user-images.githubusercontent.com/32933889/32845737-21b408ce-c9eb-11e7-93a2-35df6de3b5ac.png)

**Comment by LeoT7508** [comment]
@joseegm 

This is completed from a design perspective. 

Zeplin link
https://zpl.io/2jpy7jW

![fundamentalui_website_ui guidelines_typography](https://user-images.githubusercontent.com/28761982/33737575-45bf20be-db5c-11e7-8e9a-7bb2c4daacbf.png)


Are we going to give the option to download the typeface from here???
