### ISSUE TITLE
Update Existing Page - Getting Started for Developers  

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1241]
The following are tasks that are needed for this page:
- Content to be reviewed and updated by @xak @saadmhybris. It also needs a page description.
- Needs new template applied

**Comment by xak** [comment]
https://github.com/SAP/techne/blob/master/docs/markdown/main/GettingStarted.md

We do not need the last section "How to build Techné Documentation locally". This is not a common use case.

**Comment by saadmhybris** [comment]
this is done.
