### ISSUE TITLE
UX - Starter Page - Empty page

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1245]
Create Empty page Starter Page.

**Comment by gcho1023** [comment]
https://techne.yaas.io/starterpages/start.html

are there use cases we should cover for this page @joseegm ?

https://techne.yaas.io/starterpages/start.html

**Comment by joseegm** [comment]
Yes. The use cases we are covering now are:
1. When there is a "collection" with no items: http://sap.github.io/techne/empty-starter-page.html
2. When you filter too much but there is no results: same as above but not + button

**Comment by gcho1023** [comment]
https://6umx4d.axshare.com/#g=1&p=empty_page_-_without_side_bar

could you take a look at these pages for feedback? @joseegm
