### ISSUE TITLE
UX: Starter Page - Form

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1248]
Create Form Starter Page.

**Comment by gcho1023** [comment]
https://6umx4d.axshare.com/#g=1&p=form

https://6umx4d.axshare.com/#g=1&p=form_table

open for discussion - feedback

**Comment by joseegm** [comment]
Good. But maybe we can take a real use case, like adding Adress information and shipping options example when we use real labels and stuff, it will look better, I think :)

**Comment by jinjiahuangsap** [comment]
The wire shows 10 cols but we are still using 12 col grid here, with 32px spacing between forms.
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/5a56617ed8129336c854fcbe
https://app.zeplin.io/project/598cce4ab8aced8f15a420a1/screen/5a56617d0ed18624c888dea1
![techne_2 0_form table](https://user-images.githubusercontent.com/32305332/34790252-d84859e0-f606-11e7-8e4a-110e5f2f5f24.jpg)
![techne_2 0_form](https://user-images.githubusercontent.com/32305332/34790253-d85370a0-f606-11e7-8221-5b25ceed9c11.jpg)

**Comment by gcho1023** [comment]
@jinjiahuangsap  the wire has 12 cols without the left nav

**Comment by jinjiahuangsap** [comment]
@gcho1023 The text is updated but I stick to the 32px gutter spacing because of the previous discussion on this issue. We can probably have a discussion on that during the next meeting.

**Comment by LeoT7508** [comment]
@jinjiahuangsap @gcho1023 
From a design perspective this issue is closed.
