### ISSUE TITLE
Site: Resources page

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1252]
Need page for Fundamental UI Website including wire, design, and page created.

Content includes:
- Color Palette - https://github.com/SAP/techne/issues/1249
- Download link of Axure lib file (lib of assets) - https://github.com/SAP/techne/issues/1250
- Download link of Sketch UI kit (lib of assets) -https://github.com/SAP/techne/issues/1251

**Comment by joseegm** [comment]
this is on the way, design resources still been created.
