### ISSUE TITLE
Support Dropdown

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1253]
Need a dropdown created to include the following:
-  Ask a Question - Opens a form with a Question field and Send button. @joseegm @saadmhybris @xak Can this form be integrated back to Github where it could auto create an issue in a project created specifically for this?
- Submit an Issue - this link will open a Github issue - @joseegm - can you provide details on how you would like to manage this? Should this be a form link Ask a question above?

**Comment by xak** [comment]
The Github API does not allow issue creation without authentication. We can provide a link to https://github.com/SAP/techne/issues/new and an email address.

**Comment by joseegm** [comment]
We'll got with the link to the issues page for now.

**Comment by saadmhybris** [comment]
this will be developed under #1255
