### ISSUE TITLE
Site: Top navigation, left navigation and right side bar of Fundamental Website

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1255]
Build out the following:
- Top nav
- Left nav
- Template with right nav
- Template without right nav

Linked to #1216

**Comment by saadmhybris** [comment]
design in zeplin -
https://zpl.io/Vq11Dr4
https://zpl.io/29NNXYe

**Comment by saadmhybris** [comment]
everything is done execpt right nav which for which a new issue has been opened here - #1287
