### ISSUE TITLE
Site: Website before the Beta Meta list

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1262]
This is only to keep track of all stuff to be done on the website before the beta.

0. -Website Structure-
	~~0.1 Top nav - #1255~~
	~~0.2 Side nav - #1255, #1261~~ 
	0.3 Back top button - #1288
1. Home page - #1194
	~~1.1 Getting started designer - #1207~~
	~~1.2 Getting started dev - use the code from above and info from current home~~
2. Style page 
	~~2.1 Colors - https://github.com/SAP/techne/issues/1235~~
	~~2.2 Spacing - https://github.com/SAP/techne/issues/1236~~
	~~2.3 Grid - https://github.com/SAP/techne/issues/1205~~
	~~2.4 Type - https://github.com/SAP/techne/issues/1238~~
	2.5 Layouts - https://github.com/SAP/techne/issues/1157 -- Hold off
3. Components index page - https://github.com/SAP/techne/issues/1213
4. Component page - https://github.com/SAP/techne/issues/842
	4.1 New Documentation Pattern - https://github.com/SAP/techne/issues/1217
	4.2 Right list of subheaders - jump links - #1287
5. Starter pages index - https://github.com/SAP/techne/issues/1214

**Comment by gcho1023** [comment]
@joseegm  should this be in UX? does not provide us much information on the action

**Comment by joseegm** [comment]
It is a list of dev tickets to track the overall progress.
