### ISSUE TITLE
Font files cannot get loaded from CDN stylesheet because of CORS policy.

### ISSUE THREAD

**Issue by odinath** [SAP/techne#1279]
The Fundamental UI stylesheet can get properly loaded from its CDN hosting:
https://techne.yaas.io/libs/techne/2.0.0-alpha-7/techne.min.css

Fundamental then requests for two font files:
- https://techne.yaas.io/libs/techne/2.0.0-alpha-7/TechneIcons.woff
- https://techne.yaas.io/libs/techne/2.0.0-alpha-7/TechneIcons.woff2

Those files can't unfortunately get loaded on the web browser, they got blocked because of the [CORS policy](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

It seems the settings of the CDN server need to get updated to allow for this "Cross Origin Resource Sharing", with an "Access-Control-Allow-Origin" header needs to get added to your HTTP responses.

See the following article which explains how to update your server settings:
https://www.maxcdn.com/one/tutorial/how-to-use-cdn-with-webfonts/

**Comment by joseegm** [comment]
@odinath 
That's a good catch.
We already decided to use a 3rd party CDN in #1212, so is only a matter of changing the link in the documentation, the CDN works out of the box.

Can you please, check if the same problem persist when you use this CDN?
https://unpkg.com/techne@2.0.0-alpha-6/dist/techne.min.css
is the one we plan to use, you may have already setup the testing environment where you found the bug :)

@saadmhybris 
So, is the time to change that to unpgk.com now

**Comment by odinath** [comment]
@joseegm Following your instructions, I just tested the 'unpkg' link on my local environment.
With this other CDN link, all font files are not being blocked anymore. The font-based icons get properly displayed on my pages.
I'm closing this ticket as 'fixed'.
