### ISSUE TITLE
Color page update

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1305]
- On the color page description "meaninful" is misspelled.  Correct -  "meaningful"
- The title of the swatches would look better centered than left aligned. 

<img width="980" alt="screen shot 2018-01-03 at 11 52 28 am" src="https://user-images.githubusercontent.com/32933889/34532719-c007b004-f07c-11e7-8e42-21cf81e6e053.png">

**Comment by saadmhybris** [comment]
@gcho1023 - 

- fixed typo. 
- i tried center alignment for the label, but it did not look good so going to leave it as originally designed.
