### ISSUE TITLE
Spacing page update

### ISSUE THREAD

**Issue by gcho1023** [SAP/techne#1307]
- Take out the apostrophe in the description "content area's"
- Lower case S and P in " Section and Panels"

<img width="1069" alt="screen shot 2018-01-03 at 11 59 21 am" src="https://user-images.githubusercontent.com/32933889/34532945-b8c3a50e-f07d-11e7-9385-5b5070a11428.png">

**Comment by gcho1023** [comment]
sorry I wasn't clear... the Heading should have "Sections & Panels" capital...but the body content where it says "there is a system of Sections & Panel" should be lower case @saadmhybris

**Comment by saadmhybris** [comment]
fixed - http://sap.github.io/techne/spacing.html

@gcho1023

**Comment by xak** [comment]
@gcho1023 Can you verify this is complete and close? Thanks.

**Comment by gcho1023** [comment]
Yep - fixed
