### ISSUE TITLE
Site: Feedbacks for Typography page

### ISSUE THREAD

**Issue by jinjiahuangsap** [SAP/techne#1320]
@saadmhybris 

- [ ] 1. Header is Typography
- [ ] 2. Header font weight
- [ ] 3. Roboto: Header: Roboto Bold
- [ ] 4. Roboto: Header bottom margin
- [ ] 5. Roboto: The “Rr” and “ABCD…” on the right should align the bottom
- [ ] 6. Roboto: the bottom margin of “Rr” should be 36px
- [ ] 7. Roboto: subheader: Roboto Regular,13px
- [ ] 8. Roboto: spacing between each font size: 20px
- [ ] 9. Open Sans: header: Open Sans, Bold
- [ ] 10. Open Sans: Text on the right: Open Sans Senmibold, 20px, 24 line height
- [ ] 11. Open Sans: the bottom margin of “Aa” should be 36px
- [ ] 12. Open Sans: spacing between each font size: 20px

![feedback-typography page](https://user-images.githubusercontent.com/32305332/34731112-f5479be0-f526-11e7-8a0e-de6434643b80.png)

**Comment by saadmhybris** [comment]
moved - https://github.com/SAP/fundamental/issues/50
