### ISSUE TITLE
SAMPLE Component Issue Title

### ISSUE THREAD

**Issue by jeannewalters** [SAP/techne#1321]
**Description/Value Statement** **(PO)**:
As a <user type>, I want to <function> so that <benefit> .

Examples on Invision:
<URL>

**Acceptance Criteria** (What is required for the business and for the PO to accept the story) **(PO)**:
- Feature
- Feature
- Feature
- Feature

**Definition of Done** **(PO)**:
- Passes <test> and <test>
- Acceptance by <WHO>
- Able to show feature in company-wide demo

NOTE: The dates below will be added when the person starts working on the issue. Issues won't be started until description and acceptance criteria are discussed and noted above:

Estimated Date for 1st Draft of Wires **(UX)**

Estimated Date for Visual **(Visual)**

Dev ticket created and linked to this.

**Comment by xak** [comment]
@jeannewalters Can you move this to a WIKI page — https://github.com/SAP/techne/wiki — for reference? Since it's not a real story it'll just sit here forever.
