### ISSUE TITLE
Top and Side Navigation

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#1329]
### Description
The Top and Side navigation will support intra and inter navigation on Fundamental UI Applications.

> **Intra app navigation:** navigation inside a single, standalone application. **Inter app navigation**: navigation to other, related standalone applications.

### Features

1. **Top navigation**:
  1.1 Can be used standalone without the side navigation
  1.2 Support for application branding, logo and name
  1.3 Support for Inter application navigation
  1.4 Support for Intra application navigation: access main application areas
  1.4.1 Should clearly display the current application area
  1.5 Support for application global actions: help, profile, settings, configuration, etc.
  1.6 Support for application wide search.
  1.7 Support a way to show/collapse the side navigation

2. **Side navigation**:
  2.1 Can be used standalone without the Top navigation
  2.2 Support for application branding, logo and name
  2.3 Support for Intra application navigation: access main application areas
    2.3.1 Support for deeper Intra application navigation: collapsible options, etc.
    2.3.2 Should clearly display the current navigation node
  2.4 Support for application global search
  2.5 Support for global actions: help, profile, settings, configuration, legal information, etc.

3. The Top and Side navigation can be use independently depending on the type of application.

**Comment by joseegm** [comment]
This will continue on the Fundamental repo

**Comment by jeannewalters** [comment]
@joseegm Please add a link to the new repo ticket.
