### ISSUE TITLE
Tree component - Fix example

### ISSUE THREAD

**Issue by bvanalderweireldt** [SAP/techne#305]
The Tree component given here : https://techne.yaas.io/section-20.html is not working as expected and the example is not an angular example, it would be nice to have for example the JS code of the category tree ?

**Comment by HybrisRawls** [comment]
Techne aims to be library dependent (outside of bootstrap), so we don't provide any JS with our markup. It will be up implementers to add show/hide functionality. 

The example is purely from a visual standpoint as to how the markup and display will look
