### ISSUE TITLE
Description for your project

### ISSUE THREAD

**Issue by jonathanbaker7** [SAP/techne#518]
Please update the description for your project.  1-2 sentences should be sufficient.  Thanks.

**Comment by joseegm** [comment]
Thank you for noticing the issue. We are still getting the right permissions for the git repo atm.

Thanks.

**Comment by jonathanbaker7** [comment]
Have you reached out to a Github administrator yet?


Cheers,
Jonathan

**Comment by joseegm** [comment]
Yes we did, but till now no progress there.

Cheers

Jose E.

**Comment by jonathanbaker7** [comment]
Interesting.  I haven't found anything in my inbox.  Perhaps you could send
it again?


Cheers,
Jonathan

**Comment by joseegm** [comment]
Just sent you an email.

Cheers

Jose E.

**Comment by saadmhybris** [comment]
Please grant me the admin rights to the repo as well. 

Saad.

**Comment by joseegm** [comment]
Yep. I told him, to grant us both access on my email ;)

**Comment by joseegm** [comment]
This is resolved now.
