### ISSUE TITLE
Document design system foundation

### ISSUE THREAD

**Issue by xak** [SAP/techne#592]
As a presentation architect, I would like to have a detailed spec of the underlying foundation of the Techne design system so I can more easily implement that system in CSS.

Spec sheet should include details for:
- [x] Breakpoints for responsive design (naming these based on screen size is always helpful e.g., xs, sm, med, large)
- [x] Grid (what are the column breakdowns and how should they behave responsively)
- [x] Max content width (should everything go full width or stop at some width; or perhaps support both options)
- [x] Padding and spacing for layout (ideally derived from a base unit, e.g, 5px expands to 5px, 10px, 25px, 50px, 100px; these can also have convenience names like compact, loose, etc.)
- [x] Font sizes with line-heights and margins (no more than 8 is ideal; with 6 most-used sizes + two extra for tiny legal text and jumbo text; a base unit or Modular Scale implementation here is also ideal)
- [x] Named colors (breaking these down to uses, e.g., primary, secondary, accent, etc. is helpful for theming purposes).

For foundation purposes, it is very important to understand how containers stack on top of each other, how columns fit on a grid, how containers stack in responsive views, etc. Getting the foundation right makes the component authoring more easily.

**Comment by joseegm** [comment]
Just added the Adobe XD file to the repo. We are going to track all visual changes here in the public repo as well.

Also created this project to track all tasks related to the Design part
https://github.com/SAP/techne/projects/2

Thanks for asking about it, we have now a important part of Techné also very public :)

@xak I think that will answer much of your questions. For those items not covered with the aforementioned actions. Please feel free to take action on that direction. Again a PR: talks louder than 1000s of words ;)

**Comment by joseegm** [comment]
@xak  
To clarify all this points in the right context.

On March 2017, we already had a visual direction that we are still using (July 2017). Attached bellow
[Visual-styles-builder.pdf](https://github.com/SAP/techne/files/1130343/Visual-styles-builder.pdf)

**Based on that**

On the successive time all those items you were requesting back them, have been designed, as they were put on the design pipeline.

1. Breakpoints for responsive #739 
2. Grid. We have a starting point for that #613, emphasis on **Starting Point**
3. Max content: This is a wide question that needs to be worked out when we define the **Layouts**, those are already on the list https://github.com/SAP/techne/wiki/Techne-Components, and part of Batch 1
4. Spacing that feature is already defined, at the proper time #751, documented at https://github.com/SAP/techne/wiki/Spacing-Design-specs
5. Fonts and font sizes #721 
6. That's been discussed now at #766 

Again to be very clear, some of the elements are based on the aforementioned vision that was present already.

I think with this, issue is already answered completely.

**Comment by xak** [comment]
Thanks for this. Leo and I have filled in most off the gaps here and I will work next week to implement what we have defined, with priority on the layout. I'm fine closing this even though much is still in progress.
