### ISSUE TITLE
Implement icons

### ISSUE THREAD

**Issue by xak** [SAP/techne#610]
Let's discuss the architecture but thinking something like this.

# src
`src/resources/icons`
`src/styles/icons.scss`

# dist
`dist/fonts/icons.woff`
`dist/css/techne-icons.css`

**Comment by joseegm** [comment]
The icon template svg file should be located also on `src/resources/icons`?

**Comment by joseegm** [comment]
Moving forward as per https://github.com/SAP/techne/issues/612#issuecomment-290765493
