### ISSUE TITLE
Port Icon template

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#612]
Located on 
`````
techne/src/font-icon-template.svg
`````
Related to #610

**Comment by joseegm** [comment]
Icon template file will be located on `/design`

**Comment by joseegm** [comment]
Icon template .svg file
[techne-icon-template.svg.zip](https://github.com/SAP/techne/files/889538/techne-icon-template.svg.zip)

**Comment by xak** [comment]
This is not used in the project tech so it should go in the `design` directory. I'm fine with @joseegm owning that directory and organizing it as best suits the needs of designers.

**Comment by joseegm** [comment]
The file is attached.

How is gonna be included?

**Comment by xak** [comment]
@joseegm anything you want in the `design` directory you can add yourself. nothing there affects the build or tech so I’ll defer to how you want that directory and how you want to use it. do a PR against `v2.0` and I’ll merge it.

**Comment by joseegm** [comment]
As agreed on the meeting on Friday 31.04.2017. The project is divided in two production lines. Implementation includes handling of files too.

Please take action on the location and availability of the item; when moving the issue to the Implementation production line. 

Remember the process is pull, not push.

Thanks
