### ISSUE TITLE
Design main Layout animation

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#619]
### Goal: Inform the main layout hierarchy via animation.

Elements to animate and animation description:
*  **Bar at the top**: linear moving animation during 0.5s; sliding down as a whole element from the top of the browser window
 * **Bar at the side**: delayed 0.5s, linear moving animation during 0.5s; sliding from the left of the browser window
 * **Content area**: delayed 0.5s, sequenced linear fade-in animation; Sequenced delays and timing as per the line 65 of the following framer prototype
`````
Framer.Extras.Preloader.enable()

maxWidth = Framer.Device.screen.width
maxHeight = Framer.Device.screen.height

bg = new Layer
	backgroundColor: "#fff"
	width: maxWidth
	height: maxHeight

start = new TextLayer 
	text: "START"
	fontSize: 20 
	y: maxHeight - 150
	x: maxWidth - 150
	z: 100

reset = new TextLayer 
	text: "RESET"
	fontSize: 20 
	y: maxHeight - 100
	x: maxWidth - 150
	z: 100

Main_Nav = new Layer
	width: Framer.Device.screen.width
	height: 50
	backgroundColor: '#0486E0'
	y: -50
	z: 1
	
Main_Nav.states.hide =
	y: -50	
Main_Nav.states.intro =
	y: 0

sideNavWidth = Framer.Device.screen.width * (0.61 / 2.5) 

Side_Nav = new Layer
	y: 50
	width: sideNavWidth 
	height: Framer.Device.screen.height
	backgroundColor: '#003459'
	z: 0
	x: sideNavWidth * -1
	
Side_Nav.states.hide =
	x: sideNavWidth * -1
	
Side_Nav.states.intro =
	x: 0

sectionHeight = (maxHeight * 0.61 / 2)
maxSections = maxHeight / sectionHeight

Sections = []
for i in [0..maxSections]
	Sections[i] = new Layer
		width: maxWidth - sideNavWidth
		height: sectionHeight
		y: 50 + i * sectionHeight
		x: sideNavWidth
		opacity: 0
		backgroundColor: Color.random().lighten(20).desaturate(100)
		animationOptions: 
			delay: 1 + (i/2 * 0.2)
			time: 0.5

start.onClick ->
	Main_Nav.animate "intro",
		time: 0.5
	Side_Nav.animate "intro",
		time: 0.5
		delay: 0.5
	for i in [0..maxSections]
		Sections[i].animate
			y: 50 + i * sectionHeight
			opacity: 1

reset.onClick () ->
	Main_Nav.stateSwitch "hide"
	Side_Nav.stateSwitch "hide"
	for i in [0..maxSections]
		Sections[i].animate
			opacity: 0
			options:
				delay: 0
				time: 0
`````     

Rendered animation in the attached video
[main-layout-animation.mov.zip](https://github.com/SAP/techne/files/889462/main-layout-animation.mov.zip)

**Comment by xak** [comment]
We could implement this on the Techne website itself but it would be difficult to enforce across all sites implementing Techne since the site vary widely. This would also require supporting JS to accompany the library. To date, we have not discussed introducing a JavaScript dependency to the project.

I do not recommended we pursue animation at this time; we can revisit later once the design system is more defined.

**Comment by joseegm** [comment]
@xak Recomendation is not a Decision.

The purpose of the feasibility check. As explained and understood in the meeting on 03.04.2017. (TODO Link meeting minutes here). Is only to check if it can be implemented. That's a yes or no answer. 

What is your decision?

**Comment by xak** [comment]
Yes, technically, this can be implemented.

**Comment by joseegm** [comment]
Please execute the next action.

**Comment by joseegm** [comment]
This can be implemented... The process is to put it on the implementation pipeline or at least on the implementation backlog... 
Otherwise it's gonna get forgotten
