### ISSUE TITLE
Find Techne 2.0 Main goals

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#634]
Issue goal: Find 3 Techne 2.0 goals

### Techne 2.0 goals
1. Empowers teams to Create Successfull Business Experiences
2. Provide the UX Design Elements needed to design Successful Business Experiences
3. Equip developers with tools and resources to implement Successful Business Experiences with minimal setup and powerful customization

The first goal is the main goal, 2nd is the UX main goal, 3rd is the Tech main goal.

**Comment by joseegm** [comment]
Missing: Successfull Business Experiences

**Comment by xak** [comment]
# Equip developers with tools to quickly assemble high-quality interfaces for products, demos, and prototypes with minimal setup and powerful customization.

- Remove the dependency on Bootstrap and advance Techné to a standalone component library with simple markup and style encapsulation.

- Provide out-of-the box interoperability with Angular and React libraries through namespaced styles and scripts, packaged for npm and bower distribution.

- Enable theming customizations through simple SASS configuration for branding, sales, testing, and accessibility needs.

**Comment by joseegm** [comment]
Main 2nd goal updated from #636 

Equip developers with tools to quickly assemble high-quality Busines Experiences for products, demos, and prototypes with minimal setup and powerful customization.

**Comment by xak** [comment]
If "successful business experiences" is repeated in every goal then it becomes the default theme of the entire project. I recommend weaving your definition into the goals themselves.

**Comment by joseegm** [comment]
Repetition is on purpose and it is indeed the default theme of the project.
