### ISSUE TITLE
Find Techne 2.0 Tech goals

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#636]
Issue goal: Find the main 3.0 Technology/library goals. Aligned with Tech goal on #634 

Velocity

**Comment by xak** [comment]
# Equip developers with tools to quickly assemble high-quality interfaces for products, demos, and prototypes with minimal setup and powerful customization.

- Remove the dependency on Bootstrap and advance Techné to a standalone component library with simple markup and style encapsulation.

- Provide out-of-the box interoperability with Angular and React libraries through namespaced styles and scripts, packaged for npm and bower distribution.

- Enable theming customizations through simple SASS configuration for branding, sales, testing, and accessibility needs.

**Comment by joseegm** [comment]
The headline should be the 3rd main goal? from #634 
Need to use the same language as in #634 and #635 : Interfaces -> Business Experiences

**Comment by joseegm** [comment]
### Main Tech v2.0 Tech Goal

Equip developers with tools and resources to Implement Successfull Business Experiences for products with minimal setup and powerful customization.

### Techne v2.0 Tech goals

1. Enable theming customizations through simple SASS configuration for branding, sales, testing, and accessibility needs.

2. Provide out-of-the box interoperability with Angular and React libraries through namespaced styles and scripts, packaged for npm and bower distribution.

1. Remove the dependency on Bootstrap and advance Techné to a standalone component library with simple markup and style encapsulation.

**Comment by xak** [comment]
Yes, I as following your direction to have a main goal and three sub-goals.

I like the addition of "tools and **resources**" but why remove "demos and prototypes" and leave only "products"? The tech should be flexible to allow for not only product-based work but Labs UI needs, user tests, pre-sales customizations, etc.

Is there an action item for me now? I think what I presented captures all the facets and focus of the tech implementation if you want to assemble the final goals set.

**Comment by xak** [comment]
OK, it takes some of the power away but it shortens it so that's fine. My thinking was that the list provided some distinction of use and speaks to the flexibility were trying to include. With only one listed it doesn't add much ... "for products" can be removed.

Revised with corrections ...
# Equip developers with tools and resources to implement successful business experiences with minimal setup and powerful customization.

**Comment by joseegm** [comment]
That's even better now
