### ISSUE TITLE
Pkg: Implement templates and layout

### ISSUE THREAD

**Issue by xak** [SAP/techne#640]
The master template manages the highest level structural HTML (meta, styles, header, footer, etc.) for the documentation site. Additional templates inherit from the master to allow for different content layouts.

Potenital needs:
- Home page
- Landing page
- Article page (tutorial)
- Documentation page (components)

CSS will need to be created for the high-level layout (header, footer, sidebar, etc.) of the templates.

# BLOCKED until wires/design is finalized

**Comment by saadmhybris** [comment]
no longer valid since we are doing this with jekyll now.
