### ISSUE TITLE
Pkg: Dependency management

### ISSUE THREAD

**Issue by xak** [SAP/techne#644]
It should be easy for end-user developers to use the library without managing OUR dependencies. This is esp. important since SASS does not allow dynamic variable interpolation like LESS. The means we cannot rely on an end user to set a `@bower_component_path` or `@hytech_path` like the current setup. 

Any paths used in the package as `@import`s, urls, etc. must be properly linked with no additional configuration.

The `v2.0` branch maps `bower_components` to `src/vendor` as an attempt to solve this problem. The idea here is that vendor libs would be copied and output as part of our package. They would be dependencies of our project, but they would NOT be dependencies of the package.

**Comment by joseegm** [comment]
@xak 
Is this valid? I remember we did some config on the NPM settings to ignore our dev dependencies.
