### ISSUE TITLE
Pkg: Manage supporting scripts

### ISSUE THREAD

**Issue by xak** [SAP/techne#645]
Techne will (probably) need some supporting JavaScript. There is nothing in place now to build and compile scripts.

It is recommended that we avoid jQuery and use plain JS if possible. http://youmightnotneedjquery.com

**Comment by saadmhybris** [comment]
@xak - for 'building and compiling scripts' are we doing to use anything other than plain js, for example, type script? we already have a task in place to copy, lint and minify js files from docs to www. Just looking to see if this is something I can get started on.

**Comment by xak** [comment]
This issue is for the JavaScript required for the library, i.e., Select2, jQuery, etc. We haven't identified any JS needs yet so not sure there is much to do unless you can anticipate what we may need.

**Comment by joseegm** [comment]
probably not gonna happen
