### ISSUE TITLE
Docs: Website deployment task

### ISSUE THREAD

**Issue by xak** [SAP/techne#647]
The current `v2.0` branch has a build task for the docs — `gulp docs-build`

Investigate if we need additional task(s) that will be run by Bamboo for various environments. A `--production` (or environment) flag may be employed to enable additional minification and optimizations if applicable. 

The docs build task currently calls `pkg-build` first which works OK for local development but is not ideal. We should consider decoupling these. Watch tasks handle compilation for development purposes and the `default` sequence can be changed to run `pkg-build` first.

Consider pulling Techne from `bower` in the deployment scenario. The local build process compiles the library in the project and copies it to `www/css` directory. This could introduce differences in the website version of Techne vs. the published packaged version. 

For each numbered releases, this would necessitate a publishing order:
1. Publish the package
2. Bump the Techne bower version in the project
3. Deploy the site

**Comment by xak** [comment]
Related rot #617

**Comment by joseegm** [comment]
@xak You can use this one now. It was ready a month ago, merged and unmerged. 
issue https://github.com/SAP/techne/issues/681, pr https://github.com/SAP/techne/pull/682

**Comment by xak** [comment]
# Blocked by #617

**Comment by saadmhybris** [comment]
no longer valid.
