### ISSUE TITLE
Find Questions for the Techne 2.0 Survey

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#651]
issue goal: Find max 10 questions to achive the survey goal

### Survey goal
Collect the current status, needs, main expectations for Techne 2.0. 

### Questions
1. **Please tell us about your Team name and Package/Product**
2. **How you use Techne?**
  a. Use it day in and day out
  b. Use only some components
  c. Will like to use it
  d. Don’t use it
3. **Your role is?**
  a. UX Designer
  b. Front-End Developer
  c. Full Stack Developer
  d. Other. Please specify.
4. **Please describe your front-end Stack?**
5. **Which browsers and versions is your product currently supporting?**
6. **The current version of Techne v1.5.x is well is suited to support your current Package/Product Goals?**
  a. Yes
  b. No
7. **Which features of Techne v1.5.x are useful for your package/product**
8. **Which features of Techne v1.5.x are not useful for your package/product**
9. **What you need on Techne 2.0 to better support your current package/product goals?**
  a. More components
  b. Better documentation
  c. New design
  d. Namespacing
  e. Simplified markup
  f. More layout options
  g. Angular components
  h. React components
  i. Independence from Bootstrap
10. **Any other feedback you would like to send our way to help us make Techne 2.0 more useful?**

**Comment by saadmhybris** [comment]
maybe #8 would be open-ended questions where they can enter whatever they want like - "Any other feedback you would like to add?"

**Comment by saadmhybris** [comment]
#9 - what do you like most about techne?
#10 - what do you like least about techne?

**Comment by joseegm** [comment]
Maybe we can do those two implicit on the current 8...

BTW with these questions we also try to validate our goals 
https://github.com/SAP/techne/wiki/Techne-2.0-Goals

Just to keep that in mind

**Comment by xak** [comment]
For #7, I recommend a range selection option to gauge multiple features instead of a single choice. Like a 1-5 scale, 1 being "Not Important at All" and 5 being "Very Important"

## How important are each of the following features for future releases of Techne?
- More components
- Better documentation
- New design
- Namespacing
- Simplified markup
- More layout options
- Angular components
- React components
- Independence from Bootstrap
- etc.

That should provide more nuanced data about a wider range of features.

**Comment by joseegm** [comment]
Due to the expected participation: > 50. Having a range will not be representative. Is better to only have the points as checkboxes; that denotes interest and a point repeat much that is important.

**Comment by joseegm** [comment]
This two
https://github.com/SAP/techne/issues/651#issuecomment-297457772
can be asked on the 6th question, depending on the answer

**Comment by joseegm** [comment]
@saadmhybris @xak 
Take a final look. I think we are good to go.

**Comment by saadmhybris** [comment]
looks good.

**Comment by xak** [comment]
"roll" should be "role"
