### ISSUE TITLE
Collect the component list for v2.0-alpha

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#652]
issue goal: collect and list all components that will gonna be on the first v2.0-alpha. The list should contain, at minimun, the components present on v1.5.x

Use the taxonomy defined on #653 

### Structure
* Grid
* Frames
* Spacing
* Layouts

### Colors
* Main colors
* Themes

### Typography
* Headings
* Help Text
* Content

### Containers
* Cards
* Product Thumbnails
* Images/Avatars

### Collections
* List
* Table
* Tree
* Cards
* Product Grid

### Actions
* Buttons
* Links
* Contextual Menu
* Expandable Button

### Modals
* Information Modal
* Decision Modal
* Form Modal

### Forms
* Inputs
* Textareas
* Radio buttons
* Checkboxes
* Dropdown 
* Multi-tab editor

### Navigation
* Tabs
* ActionBar
* ToolBar
* Standalone Pagination
* Tabs

### Guidance and Indicators
* Tooltip
* Loading
* Icons
* Alerts
* Tours
* Wizards
* Status indicators

**Comment by joseegm** [comment]
@saadmhybris @like-me1 @xak 
Please check if we are missing something on the list.

Note: Errors and help will be included on every component that have it. Same for the New items pattern

**Comment by like-me1** [comment]
@xak @joseegm what about renaming Conveyances to Guidance and moving icons into Collections?

**Comment by joseegm** [comment]
'Guidance and Indicators' may be a clearer name than 'Convoyance'

**Comment by joseegm** [comment]
And we have the initial list with all categories now
