### ISSUE TITLE
Add minimised version of dist CSS

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#658]
issue goal: have a minimised version of all CSS files we distribute, for use on production.

The current generated main Techne 2.0 CSS is not ready to use on production. 
https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css

To be production ready is still needs:
- [ ] Be minimised and trimmed of whitespace and formatting.
- [ ] Comments should be stripped down

The minimised files will have `*.min.css` suffix and be located along with the non-minimised files.

**Comment by xak** [comment]
This is already captured in #643

**Comment by joseegm** [comment]
Closing this as dupe of #643
