### ISSUE TITLE
Remove expensive CSS query

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#663]
issue goal: remove expensive CSS queries

On 
https://github.com/SAP/techne/blob/v2.0/dist/css/techne-all.css#L165
the CSS query 
```css
[class*="tn-primary-nav--"] { }
```
That's a expensive query to perform and is equivalent to 
```css
.tn-primary-nav { }
```
which is the default query for CSS, performance on browser implementations is optimised for it. Then use the cascade as described on #659

**Comment by xak** [comment]
There is an important difference in the two examples. Back to BEM, this shows a modifier for the component ...

```
.foo {
	border: solid 1px black;
	background-color: white;
}
.foo--highlighted {
	background-color: yellow;
}
```

In the markup, BEM notation (like Bootstrap) requires duplicate classes where `foo` gives you the base styles and the modifier class gives you the modifications ...

```
<div class="foo foo--highlighted">
</div>
```

Adding the attribute selector means there is no need for the duplication in the markup ...

```
[class*="foo--"], .foo {
	border: solid 1px black;
	background-color: white;
}
```

If you look at the source you'll see that this was testing a concept. https://github.com/SAP/techne/blob/v2.0/src/styles/components/primary-nav.scss#L26 

Not much attention has been given yet to component SASS structure and coding recommendations. As more components are built out we can assess the value. The attribute selector may not be useful or too hard to understand for some devs but I've found nothing to indicate this an expensive selector for performance being no worse than using multiple child selectors.

**Comment by joseegm** [comment]
This is issue is not solved. Please don't close it.

Bootstrap is not using BEM 
https://github.com/twbs/bootstrap/blob/v4-dev/dist/css/bootstrap.css#L4055
and Material2 is not using it either
https://github.com/angular/material2/blob/master/src/lib/card/card.scss

It is not a easy to type class names for developers and it creates a duplicated code as explained on #659 

On a 1x1 benchmark it is more expensive
https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/
Comparing results of 10 and 20 tests

We have to ditch BEM notation since it doesn't bring any real value and create duplicate code

**Comment by xak** [comment]
I'm fine removing the attribute selector. There are other ways to achieve the same thing in CSS. 

But I strongly disagree about BEM. It brings **A LOT** of value and unless we align around another approach or I see a specific custom implementation recommendation, there is no reason to change our approach. 

Please show me how you would define classes names for a component with multiple elements and multiple modifiers.

**Comment by joseegm** [comment]
Component with multiple elements and multiple modifiers
```css
.tn-component { }

    .tn-component-element1 { }
    .tn-component-element2 { }

    .tn-component-modifier1 { }
    .tn-component-modifier2 { }

/* card example */

.tn-card { }

    .tn-card-header { }
    .tn-card-content { }

    .tn-card-vertical { /* default, modifier optional */ }
    .tn-card-horizontal { }
```
and

```html
<div class="tn-card tn-card-horizontal">
    <div class="tn-card-header"> ... </div>
    <div class="tn-card-content"> ... </div>
</div>
```
@xak There you go
