### ISSUE TITLE
Philosophy images

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#673]
![1](https://cloud.githubusercontent.com/assets/22662903/25997324/f41b1e0a-371b-11e7-9f1b-35451349b640.png)
![2](https://cloud.githubusercontent.com/assets/22662903/25997325/f438f1b4-371b-11e7-9b13-4ddd2c5f218d.png)
![3](https://cloud.githubusercontent.com/assets/22662903/25997327/f43d74dc-371b-11e7-9918-67fd699c0abb.png)
![4](https://cloud.githubusercontent.com/assets/22662903/25997326/f43cc186-371b-11e7-87d3-6675a9dacaf1.png)
![5](https://cloud.githubusercontent.com/assets/22662903/25997330/f4407d3a-371b-11e7-9ee6-ee2ad63361e6.png)
![6](https://cloud.githubusercontent.com/assets/22662903/25997328/f43db7e4-371b-11e7-8402-479fae4e965e.png)
![7](https://cloud.githubusercontent.com/assets/22662903/25997329/f43fea3c-371b-11e7-99b8-474b8a67ad68.png)
![8](https://cloud.githubusercontent.com/assets/22662903/25997332/f452f46a-371b-11e7-9e9e-859aaf647679.png)
![9](https://cloud.githubusercontent.com/assets/22662903/25997331/f4531f62-371b-11e7-981d-345cbf3acd2d.png)
![10](https://cloud.githubusercontent.com/assets/22662903/25997335/f45776e8-371b-11e7-807c-867fafd2d6c7.png)
![11](https://cloud.githubusercontent.com/assets/22662903/25997333/f456bdf2-371b-11e7-81bb-8044e6d57ee5.png)
![12](https://cloud.githubusercontent.com/assets/22662903/25997334/f4576072-371b-11e7-9586-fae339c56234.png)
![13](https://cloud.githubusercontent.com/assets/22662903/25997336/f459c222-371b-11e7-8e3d-1f5da413aa2d.png)
![14](https://cloud.githubusercontent.com/assets/22662903/25997337/f469b740-371b-11e7-83a1-153633b80eff.png)
![15](https://cloud.githubusercontent.com/assets/22662903/25997338/f46a06a0-371b-11e7-9c9d-1629c67e5b2a.png)
![16](https://cloud.githubusercontent.com/assets/22662903/25997341/f4730c1e-371b-11e7-9f54-e960b9b77e50.png)
![17](https://cloud.githubusercontent.com/assets/22662903/25997342/f4788d74-371b-11e7-80d7-335cfc175a24.png)
![18](https://cloud.githubusercontent.com/assets/22662903/25997339/f46ed2ac-371b-11e7-8286-f628e22e9428.png)
![19](https://cloud.githubusercontent.com/assets/22662903/25997340/f470adfc-371b-11e7-9471-8f174ffa7d7d.png)
![20](https://cloud.githubusercontent.com/assets/22662903/25997343/f47f30fc-371b-11e7-91a2-125546375b35.png)
![21](https://cloud.githubusercontent.com/assets/22662903/25997344/f47f9844-371b-11e7-800c-33eb744bb012.png)
![22](https://cloud.githubusercontent.com/assets/22662903/25997345/f485c50c-371b-11e7-923b-4945995a3f3d.png)
![23](https://cloud.githubusercontent.com/assets/22662903/25997346/f48ce152-371b-11e7-96fc-53734622d67e.png)
![24](https://cloud.githubusercontent.com/assets/22662903/25997347/f48d6dca-371b-11e7-98df-44b5cf83a345.png)
![25](https://cloud.githubusercontent.com/assets/22662903/25997348/f491fa84-371b-11e7-8518-09fd27008da9.png)
![26](https://cloud.githubusercontent.com/assets/22662903/25997349/f4942f3e-371b-11e7-8c80-7941c15d79fd.png)
![27](https://cloud.githubusercontent.com/assets/22662903/25997350/f4945f5e-371b-11e7-9498-73fc44a02570.png)
![28](https://cloud.githubusercontent.com/assets/22662903/25997351/f49cbf46-371b-11e7-80aa-cc78e94100a2.png)

**Comment by joseegm** [comment]
PDF file
[techne-philosophy.pdf](https://github.com/SAP/techne/files/995985/techne-philosophy.pdf)

**Comment by tank6b** [comment]
Test comment
