### ISSUE TITLE
Should we keep the Grouped cards?

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#679]
### Should we keep the Grouped cards as part of "the cards"?

Reference #678

**Comment by joseegm** [comment]
Visually it looks more like a list. 
https://techne.yaas.io/components/Lists.html

The same elements displayed as a list layout it should occupy less space and "jump" less on hover.

*Quick tip: if you agree just add "Thumbs up reaction" it is an easy way to display agreement without making a comment.*

**Comment by denisewildner** [comment]
The grouped cards don't follow a techne guideline afaik and I see no value to use it. 
Therefore I am fine with changing it to a list.

**Comment by saadmhybris** [comment]
I don't see a reason why the list pattern cannot service the same purpose as grouped cards. 

repeal and replace.

**Comment by joseegm** [comment]
All right. Then we decided to use the **List** and removed the grouped cards from Cards
