### ISSUE TITLE
Revisit Product Thumbnail

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#680]
### Goals
1. Add a way to display the product thumbnail information horizontal as well.
2. Change how to display the textual information to make it look less plain with emphasis on the product title.
3. Display price, price discounts and price ranges in a more appealing way.

### Prior art
v1.5.x - https://techne.yaas.io/patterns/Product-Thumbnail.html

<img width="320" alt="screen shot 2017-05-15 at 22 36 14" src="https://cloud.githubusercontent.com/assets/22662903/26078186/f8ba8324-39be-11e7-8d30-2ef03ef8c414.png">

**Comment by LeoT7508** [comment]
Updated Product Thumbnail tile. As with the updated card designs I didn't try and overthink it or change it too much, I just worked with spacing, type size, padding, color, and worked to create a higher level of consistency with all of these parts.  
![techne_2 0_cards_productthumbnail](https://cloud.githubusercontent.com/assets/28761982/26360276/4d4a8ebe-3f9d-11e7-880a-8d568a1867aa.jpg)

**Comment by joseegm** [comment]
@LeoT7508 Excellent. 
Can you try the cases: price range, and rice range with discount?

Since this has the same characteristics as the cards, can we try this with the picture on the left and the info on the right?

**Comment by LeoT7508** [comment]
@joseegm 
![techne_2 0_cards_productthumbnail](https://cloud.githubusercontent.com/assets/28761982/26415103/f2ad3e86-4076-11e7-83a2-007fe8876ea2.jpg)

**Comment by joseegm** [comment]
@LeoT7508 Nice.

What about the cases with Price Range and Price Range discount?
Currently we are displaying it like

![screen shot 2017-05-26 at 10 37 14](https://cloud.githubusercontent.com/assets/22662903/26487325/5900476c-41ff-11e7-88b1-ef1c9d282a0e.png)

Based on how Amazon display prices.
* Current prices are red.
* Discount prices are black and strike.

Since this is a wildly know pattern user are used to, let's follow that.

**Comment by LeoT7508** [comment]
@joseegm 

Updated pricing.
![techne_2 0_cards_with product image](https://cloud.githubusercontent.com/assets/28761982/26589212/0fdd2494-451d-11e7-82ae-8ffa542617c5.jpg)

**Comment by joseegm** [comment]
@LeoT7508 did you posted the old version again? :D 
It is the same as https://github.com/SAP/techne/issues/680#issuecomment-303783791

Price ranges still missing

**Comment by LeoT7508** [comment]
Updated product cards
![techne_2 0_cards_with product image](https://cloud.githubusercontent.com/assets/28761982/26697450/bbcee754-46d7-11e7-94cb-b83d3004ebbd.jpg)

**Comment by joseegm** [comment]
This component will be included in the cards - #678 since it is very similar.
