### ISSUE TITLE
Better define property and state options for buttons; consider flexibility over specific uses

### ISSUE THREAD

**Issue by xak** [SAP/techne#685]
The current 1.x categorization of buttons is very specific. Common buttons are easily available, but the flexibility available to developers is not laid out. The differences in approaches is about flexibility to create a wide variety of interfaces with the library.

Some examples of generic implementations:
- [IBM](https://www.ibm.com/standards/web/design/buttons/)
- [MDC](https://material.io/components/web/catalog/buttons/)

Some thoughts:
1. Directional buttons — While the back button is a very common element in many UIs, should this simply be any option available to all button types? For example, in "Tours", we show a primary button with a "next" arrow so should directional buttons be icon buttons with text.
2. Icon buttons — Related to above, we show an icon button as an icon only, but a more flexible approach would be to allow any button to include an icon with or without text, e.g., a help button vs. the back button.
3. Transparent buttons — Related to above, back, link and icon buttons are really just transparent buttons vs. the filled primary and secondary buttons. Should we include three main button types, primary, secondary, transparent (or flat) button types. Then each of those types would allow for icons, text or both?
4. States — Should we show states like "disabled" for each button type?

Related:
- Buttons all use `btn-lg` class. If we remove Bootstrap, do we need to support different size buttons or will they all be large?
- Button class names are confusing. Secondary buttons use `btn-default`and the Cancel and Back buttons use `btn-subordinate`.  We don't define these however in terms of usage or hierarchy.

If you pull branch `feature/683` and look at `/buttons.html` you can how usage is being defined.

**Comment by joseegm** [comment]
@xak 
Is this one still valid?

**Comment by xak** [comment]
Yes, but this can be closed because the context is different now. The buttons do need to be revisited since a simple button may require up to four classes, that must be simplified.
