### ISSUE TITLE
Docs: Built out the web site shell

### ISSUE THREAD

**Issue by xak** [SAP/techne#689]
The site shell consists of the header (top nav), the sidebar (side nav), an empty content area, and the footer.

The shell should be consistent with the implementation across yaas.io. Use the current site as the guideline.  https://techne.yaas.io

**Comment by xak** [comment]
@joseegm Please confirm that secondary nav for Components will have 10 sub-sections as indicated at https://github.com/SAP/techne/wiki/Techne-Components? Will there be a Components landing page or will "Structure" be the index for the section?

**Comment by joseegm** [comment]
@xak Yes that will be the list.

For now we don't need and index page. We go directly to the first option.

The categories are only headers on the navigation -for now- not index pages for the components.

**Comment by like-me1** [comment]
@LeoT7508 I'm implemetning the skeletor of the web site for techne, and for now we will use old nvigation and I don't see the color analogues from pallette you provided and what is currently on techne.yaas.io. Could you please give me a the right mapping or should I re-use the old one?

**Comment by LeoT7508** [comment]
@like-me1 

The global and secondary nav should stay consistent with the rest of YaaS so stick with the old palette for now. 

Thanks.

**Comment by joseegm** [comment]
@like-me1 
As per the discussion we had on #698 we decided to keep as much as it is now.
But please don't use "Dosis" as font on the Secondary Navigation.

**Comment by xak** [comment]
@joseegm I don't see any value in being the only section in yaas.io that doesn't use Dosis in the left nav. It's about consistency with the rest of the site. No one will understand that ours is an "improvement" over the rest of the site, rather it will look like it's broken on our page ... and we don't want that.

**Comment by joseegm** [comment]
@xak It is obvious that the readability is increased when not using Dosis. As per the next screenshot.
![screen-shot-2017-06-07-at-09 21 06](https://user-images.githubusercontent.com/22662903/26866912-88b3ec58-4b63-11e7-8c30-ad9b5015c831.png)

Keeping the status quo for the sake of keeping the status quo is not helpful. If there is something we can improve then we gonna improve it.

Dosis is a not a good font for small text, like this. That's why we can take it out of the navigation.

**Comment by xak** [comment]
@joseegm I understand about the readability, I never questioned that. But Dosis has been in use for years and is **the font** used for **all navigation links** on yaas.io. That is the design system in place. The only exception I can find is the Techne top nav secondary-level and every time I see it it looks broken, like someone didn't code it properly.

<img width="884" alt="screen shot 2017-06-07 at 5 06 23 pm" src="https://user-images.githubusercontent.com/424119/26903622-af8385ce-4ba3-11e7-9c8a-a9542b025f34.png">

We work like hell to keep things consistent on the site where we have minimal control. It doesn't set a good example if our section goes rogue. Why shake it up?
