### ISSUE TITLE
Docs: Build out the main content area

### ISSUE THREAD

**Issue by xak** [SAP/techne#691]
The initial implementation should focus on the "article" top section (page title and description) and the layout containers (spacing and alignment).

# Inputs
**Specs:** https://app.box.com/files/0/f/27696923061
**Invision:** https://sapse.invisionapp.com/share/DTBXJCSJW#/238743129_Docs-Grid and https://sapse.invisionapp.com/share/DTBXJCSJW#/238743128_Docs-MainContent

Use the Grid and Guides pages to build out the main content area and the high-level sections.

# Outputs
* Implement baseline responsive behavior (assume containers stack at smaller sizes)
* Define max content width (we don't want fully fluid behavior soon massive displays)
* Implement grid and layout classes (or mixins) to allow for multiple column containers
* Build page title and description containers to spec (these are fairly global and could be added to the master template if that makes sense)
* Begin implementation of type specs based on header and other content sizes

**Comment by joseegm** [comment]
Design at #694

**Comment by xak** [comment]
Note that this task is not about building out the full spec from #694 but rather the high-level structural containers that each page will inherit.

**Comment by joseegm** [comment]
@xak Okay. Description of the issues wasn't clear enough.

Please add the issue for the pimplementation of the components page. Thanks.

**Comment by xak** [comment]
The components page implementation issue will be created when #694 is complete.

**Comment by joseegm** [comment]
@xak That's a waste of time since the main elements needed to build the markup are already delineated on 
https://github.com/SAP/techne/issues/694

**Comment by xak** [comment]
As I understand it, the process was to work through the UX and design and then move toward implementation. Not all issues have been resolved for #694 . I'm creating implementation tasks only when I'm satisfied they can be completed successfully.

**Comment by joseegm** [comment]
Waste of time on the context of:
https://github.com/SAP/techne/milestone/10

 The main elements are defined on the wire frames already.
