### ISSUE TITLE
Consolidate standard gulp build commands

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#695]
Create a new `gulp build` to build the library and the website in one simple command. Executing relevant build tasks as described on https://github.com/SAP/techne/blob/v2.0/ops/README.md

### Usage

`gulp build` build the library and the website for development.

`gulp build --production` build the library and website for production.

More info on https://github.com/SAP/techne/pull/682 and #681

**Comment by joseegm** [comment]
Looks like this is gonna be addressed at #647

**Comment by saadmhybris** [comment]
This task is not obsolete
