### ISSUE TITLE
Docs: Update Global Navigation

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#696]
goal: Use the new Global navigation on Techne v2.0 website.

Current:
![screen shot 2017-05-29 at 11 42 50](https://cloud.githubusercontent.com/assets/22662903/26544952/1fd3ea0e-4464-11e7-8a6f-978bc77550aa.png)

Builder:
![screen shot 2017-05-29 at 11 44 54](https://cloud.githubusercontent.com/assets/22662903/26544992/4b3cab4a-4464-11e7-91fd-aab3e25c8476.png)

Main options stay the same: Getting Started, Styles, Components, Guidelines, Tutorials

**Comment by xak** [comment]
@joseegm We should **NOT** be using the new Builder nav. We tested it in anticipation of rolling it out site-wide and it tested very poorly. We must stick with the existing nav.

**Comment by xak** [comment]
#689 is the implementation task. It would be helpful to have an IA of the site or at least confirm that we we are making no changes to the IA as it exists now. A lot is being put on the devs to figure it out. I recommend we use Invision to build out a prototype of the site as the point of truth and to gather feedback.

**Comment by joseegm** [comment]
@xak we are focusing on the items at 
https://github.com/SAP/techne/milestone/10

Items that goes in the main navigation are already enumerated at the end of
https://github.com/SAP/techne/issues/696#issue-231976179

What other info you need to keep things moving?

**Comment by xak** [comment]
@joseegm It would be incredibly useful to to have a map of the site ... even if we're using the exact same IA as we have now. Could you create a WIKI page with a full site map — all primary and secondary pages (the sidebar nav) so we can build out the entire site shell. 

We cannot rely on issues alone to document the IA and hierarchy of the site. As issues get closed, they essentially die.

**Comment by joseegm** [comment]
It will be, of course, but we are focusing on this specific issue and all elements for their completion are already delineated at https://github.com/SAP/techne/issues/696#issuecomment-304863572

Can we please focus on what's important in the context of 
https://github.com/SAP/techne/milestone/10 ?

**Comment by xak** [comment]
If there are no changes to the IA then this issue is not needed. It is being addressed with #689.

**Comment by joseegm** [comment]
@xak 
Once more, the changes to the main options naming are already mentioned on https://github.com/SAP/techne/issues/696#issue-231976179

Again, we already have the code ready for the new nav. I don't see why is this been a problem. 

So, I expect the new navigation to be addressed on #689. 
@xak Right?

**Comment by xak** [comment]
We are not implementing the "new" nav. It tested very poorly and we should not be using it outside of Builder. #689 will implement the existing nav.

**Comment by joseegm** [comment]
@xak What do you mean it tested poorly? 
I have not seeing any test results apart from the ones posted early on:
https://github.com/SAP/techne/issues/616

**Comment by xak** [comment]
See email.

**Comment by like-me1** [comment]
@joseegm @LeoT7508 I'd like to start with palette for our web site. Can I get exact one or should I re-use complete palette from SAP style guide?

**Comment by LeoT7508** [comment]
@like-me1 

This is the color palette I've been working from, I haven't deviated from these basic colors. Im sure Zack has reached out to you about creating consistency with color and how he will be doing that with code etc. As of now these are the only colors I've been working with. If I create a new color I will add them to this list and share with the team. 
![techne2 0_colorpalette](https://cloud.githubusercontent.com/assets/28761982/26641564/9d42ae84-45f0-11e7-96a3-fe8ef5e7333f.jpg)

**Comment by like-me1** [comment]
@LeoT7508 exactly what I needed, thanks!

**Comment by LeoT7508** [comment]
@like-me1 

If you need help with any other colors please reach out and I can help you. We are trying to keep this as simple and organized as possible. This will most definitely grow, but only when necessary. 

Thanks.

**Comment by joseegm** [comment]
@xak 
After our team exchange by email yesterday. Looking the prototype that was tested and the test result. I still think the new navigation can be used for the Techne Website. 
Of course with the right implementation.

The points are still valid: we already have the code and we have the options for it.

**Comment by joseegm** [comment]
Unfortunately this was ignored by @xak 
Goes back on the backlog
