### ISSUE TITLE
Design Secondary Navigation

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#698]
goal: Revisit the UX and Visual Design of the left navigation

Current examples
![screen shot 2017-05-29 at 11 57 42](https://cloud.githubusercontent.com/assets/22662903/26545492/1b31ff02-4466-11e7-9833-dfdd4e425ecc.png)

![screen shot 2017-05-29 at 11 57 57](https://cloud.githubusercontent.com/assets/22662903/26545505/20205e64-4466-11e7-9858-3c0c6c634ba9.png)

### Improve
1. Visual hierarchy.
2. More Visible Selected option.
3. Difference between the options that navigate deeper -branch- and the ones that change the page -leaf-.
4. Possibility to have collapsable options with sub-options.

### Scope
This will be scoped only for the Techne Website but with the goal to make it abstract enough to be used as a component as well.

**Comment by joseegm** [comment]
For the new Techne Website we only a single hierarchy. Like this one.
![secondary-navigation 4](https://cloud.githubusercontent.com/assets/22662903/26556908/c2157196-449d-11e7-8796-3c9f255e71e8.png)

**Comment by joseegm** [comment]
Me and Denise are nailing all the other posibilites that we have now on the Builder. WIP like
![secondary-navigation 2](https://cloud.githubusercontent.com/assets/22662903/26556946/0657d59c-449e-11e7-9372-b7fef6a4c265.png)

**Comment by xak** [comment]
@joseegm Same as for the top nav, we should not introduce changes for Techne. We should match the existing secondary nav structure. See #689. Same goes for the IA here. Please provide some guidance as to what pages will be under which sections of the site. If we're matching the existing site 1:1 then please include that list.

**Comment by joseegm** [comment]
@xak this is only for the components page as stated on
https://github.com/SAP/techne/issues/698#issuecomment-304698082

And as per the items on the milestone
https://github.com/SAP/techne/milestone/10
Communicated already

The list is, of course at
https://github.com/SAP/techne/wiki/Techne-Components

We are tackling the components page as per 
https://github.com/SAP/techne/issues/694

Any other info you need to get things moving?

**Comment by xak** [comment]
The secondary navigation patterns should already exist to accommodate different levels of navigation. https://devportal.yaas.io/tools/

**Comment by joseegm** [comment]
@xak we are taking that also in count for the final UX.

For this issue we focus on only displaying the simple hierarchy we use on the Techne website. Already mentioned on
https://github.com/SAP/techne/issues/698#issuecomment-304698082

**Comment by xak** [comment]
The output for this issue is required for #689 (already in progress).

**Comment by joseegm** [comment]
@xak for the Techne website the wireframes needed are at https://github.com/SAP/techne/issues/698#issuecomment-304698082

What's missing is the other navigation use case present in Builder that we are still working on it. But that's not relevant for the techne website right now.

@LeoT7508 
Can you take the wireframes on 
https://github.com/SAP/techne/issues/698#issuecomment-304698082
and design the secondary navigation, no much different from what you have.

All options and headers will be expanded by default, no option to contract for now to keep it simple.

**Comment by LeoT7508** [comment]
@joseegm 

I will start the secondary navigation today once I finish up the cards designs.

**Comment by LeoT7508** [comment]
@joseegm 

I talked to Zack and he feels confident moving forward with the navigation here:
https://devportal.yaas.io/tools/

So as of now we don't need a visual since he will be reusing this for our needs.

**Comment by joseegm** [comment]
@LeoT7508 
That's fine. But I have some issues still with some visual of the current state:

1. The font used is not very legible at the present size.
  ![screen shot 2017-06-02 at 11 12 29](https://cloud.githubusercontent.com/assets/22662903/26719370/88259968-4784-11e7-98fa-5a114a9949e0.png)

2. The contrast on the hover option is very low agains the dark background
![screen shot 2017-06-02 at 11 15 12](https://cloud.githubusercontent.com/assets/22662903/26719445/da3db1d6-4784-11e7-9619-5c608506cf3d.png)

3. The selected option visuals are missing on this screen. Present on the next one:
 ![screen shot 2017-06-02 at 11 17 36](https://cloud.githubusercontent.com/assets/22662903/26719507/1dbe01e0-4785-11e7-865b-c66a3aea7335.png)
  But this again have low contrast and is the same as the hover effect.

@LeoT7508 Do you think we can improve some of this issues? Or you want leave it like that?

**Comment by LeoT7508** [comment]
@joseegm 

I don't mind changing this, however I would advise against changing it since this navigation is used throughout the rest of YaaS, if we change it here then they would have to change it site wide. Or do we want to have our secondary nav look different than everywhere else on site?

**Comment by joseegm** [comment]
Think it is an opportunity to improve it. As it is still present the problems mentioned on https://github.com/SAP/techne/issues/698#issuecomment-305735452

Still I want to at least increase readability do it will be better without the "Dosis" font.

**Comment by xak** [comment]
See comment on #689. Dosis is used for (almost all) navigation across YaaS ... our pages will look broken if we don't use it.

**Comment by joseegm** [comment]
Crossposting from https://github.com/SAP/techne/issues/689#issuecomment-306711766 to keep all in context

@xak It is obvious that the readability is increased when not using Dosis. As per the next screenshot.
![screen-shot-2017-06-07-at-09 21 06](https://user-images.githubusercontent.com/22662903/26866912-88b3ec58-4b63-11e7-8c30-ad9b5015c831.png)

Keeping the status quo for the sake of keeping the status quo is not helpful. If there is something we can improve then we gonna improve it.

Dosis is a not a good font for small text, like this. That's why we can take it out of the navigation.

**Comment by joseegm** [comment]
No response since https://github.com/SAP/techne/issues/698#issuecomment-306720754
So we'll see the details on the tech implementation
