### ISSUE TITLE
Design Card Actions

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#701]
issue goal: Design the way actions inside the cards works.

### Current
* The whole cards can be clickable. This action will show the "contents" of the object the cards is representing in a new screen or a modal. That's the primary action of the card.
  Example of this case: the project cards on top
  ![450f84a6-4223-11e7-8dc2-f7ac8e5850be](https://cloud.githubusercontent.com/assets/22662903/26716475/c64c88e2-4779-11e7-893a-8c3230e23c62.png)

* Cards can have secondary actions. Those perform actions to the object the card is representing.
  Example of this case:
  ![2acc5540-420c-11e7-8afc-357765960c2a](https://cloud.githubusercontent.com/assets/22662903/26716745/fc88b088-477a-11e7-8087-2371eb5712a2.png)

**Comment by joseegm** [comment]
### Workable Solution
For some cases having a contextual *more* (...) menu on the top right of the card. This solution will be valid for when there is more than 1 action to that card
![950d99c0-46d8-11e7-936c-2c60bc13474e copy](https://cloud.githubusercontent.com/assets/22662903/26717125/8771d156-477c-11e7-9880-3c8280c21452.jpg)
Current use case of cards with more than one action: https://github.com/SAP/techne/issues/678#issuecomment-304265612
 
**Task**: Find a solution for having only one action on the card without the *more* menu, doesn't makes much sense to have a sub-menu with only one option inside.

**Comment by LeoT7508** [comment]
@joseegm @denisewildner 

I would need all instances of button labels to better understand how I can manage the button length and the position. 

This is what I have as of now, but it is not finally until I know it will work for all buttons
![screen shot 2017-06-02 at 11 39 10 am](https://cloud.githubusercontent.com/assets/28761982/26735606/387e31a0-4788-11e7-9b3a-7c8c7f34cf53.png)

Thanks.

**Comment by LeoT7508** [comment]
I put this together for this example. I think it should work and keep the placement and spacing consistent with everything else. 
![screen shot 2017-06-06 at 2 04 53 pm](https://user-images.githubusercontent.com/28761982/26847005-26a2859e-4ac1-11e7-87b6-f5498d1c52e9.png)

**Comment by joseegm** [comment]
@LeoT7508 
Think you missed to try the button at the bottom of the card from 
https://github.com/SAP/techne/issues/701#issuecomment-306432801

The example on https://github.com/SAP/techne/issues/701#issuecomment-306586023 only work for that particular case where the content is not too long.

Having the button on the footer of the card, will suffice most of the cases, since it doesn't disturb the content.

So, resuming:
* 3 dots to the top right
* Single button to the bottom right

Those cases are simple and flexible enough to cover most cases.

Now... Should be see the dropdown menu in a separate issue or having it in this context will be fine?
Meaning the widget that appears when pressing the 3 dots.

**Comment by LeoT7508** [comment]
@joseegm 

Actually I did create a version with the button at the bottom, however this solution doesn't work as it creates inconsistency with the padding of the cards, and the overall layout of the grid. The button and 3 dots works best when applied with the rules i created for cards, and that is as follows:

Cards will always only have:
- Primary value (wrap if necessary) 
- Secondary value (one line with “…” never wraps for spacing consistency)
- Status Label (one line, if there are multiple status’ they are separated by a 1px vertical rule,                 wrapping if necessary)
- Options (If necessary) 3 dots icon will hold all/multiple options. If a single button label gets too long it will be hidden in the 3 dots menu.

Also, when following only a 2 or 3 column layout for Common Cards, and a 4 or less column layout for Cards with Product images this solution works just fine. Its just a matter of following the rules set it place to ensure the spacing works. 

In certain unique scenarios we can adjust accordingly, like hiding a very long action in the 3 dots menu, but for now, this solutions should work based off the use cases I've seen.

**Comment by joseegm** [comment]
All right. Let's keep it that way then.

I'll spawn a new issue to see the design of the "dropdown menu" that appears when clicking the "..." icon.
