### ISSUE TITLE
Docs: Add SASS source maps to style guide CSS

### ISSUE THREAD

**Issue by like-me1** [SAP/techne#702]
#Show *.scss files for development environment

would be great to have a task which shows original *.scss files for development environment instead of techne-styleguide.css

**Comment by joseegm** [comment]
Meaning distributing also the `*.scss` files along with the normal and minimised `*.css` on the `/dist` folder?

**Comment by xak** [comment]
@like-me1 If you mean source maps, I agree. It should be like https://github.com/SAP/techne/blob/v2.0/ops/gulp/pkg-css.js#L27
