### ISSUE TITLE
the structure on the main page doesn't represent the actual one

### ISSUE THREAD

**Issue by SAPMontreal** [SAP/techne#704]
![screen shot 2017-06-05 at 10 03 26](https://cloud.githubusercontent.com/assets/4380815/26787681/e3e187a2-49d8-11e7-8544-1c40e6dc7b7e.png)

**Comment by joseegm** [comment]
@SAPMontreal 
Yep, looks like we gonna change the readme for v1.5.x 
Good catch.

**Comment by joseegm** [comment]
@xak 
Should we take action on this?

**Comment by xak** [comment]
Yes, we can do it with the next icon release. Feel free to do it or I can do it later. Not a high priority but easy enough.

**Comment by saadmhybris** [comment]
Closing this as we are no longer actively developing for 1.5x
