### ISSUE TITLE
SPIKE: Switch package manager

### ISSUE THREAD

**Issue by xak** [SAP/techne#707]
[Bower](https://bower.io) is no longer being developed ... but it is being maintained. They recommend [Yarn](https://yarnpkg.com) or [Webpack](https://webpack.js.org)

Two issues we need to investigate ...
1. Should we update our project to use a different package manager? 
2. What support should we offer to end users related to bower? What changes would be needed to support `bower` and `yarn`? 

The output of this issue will be an evaluation and recommendation.

**Comment by joseegm** [comment]
At this point, no switching is needed since yarn install the pacakges from the npmjs.org repo.

It finds and install the current package successfully.
![screen shot 2017-06-13 at 17 11 31](https://user-images.githubusercontent.com/22662903/27089749-92ae467a-505b-11e7-8740-209288eae5e1.png)

**Comment by joseegm** [comment]
@xak 
Do this questions is answered with the previous comment?

**Comment by xak** [comment]
We are not supporting bower with v2.0
