### ISSUE TITLE
Pkg: Build Cards component

### ISSUE THREAD

**Issue by xak** [SAP/techne#709]
# Inputs
**Design** 
Background at #678 
https://app.box.com/folder/29116880878

**Prototype** 
https://sapse.invisionapp.com/share/DTBXJCSJW#/239183941_Techne_2-0_Cards_CommonCards
https://sapse.invisionapp.com/share/DTBXJCSJW#/239183942_Techne_2-0_Cards_with_Supporting_Image

## Basic block structure
```
.tn-card+(--static)+(.is-disabled|[aria-disabled=true])
    .tn-card__media?
    .tn-card__content
        .tn-card__header
        .tn-card__description
        .tn-card__label?
```
See discussion at #692

# Outputs
- Card (Common Cards)
- Media cards (Cards with Supporting image)

# Notes
See https://hybris.box.com/s/ojarlct2k6gcp86r24qylqwo7a60xevf

_These are applicable to this issue_
Cards will always only have:
- Primary value (wrap if necessary) 
- Secondary value (one line with “…” never wraps for spacing consistency)
- Status Label (one line, if there are multiple status’ they are separated by a 1px vertical rule,                 wrapping if necessary)

**Comment by joseegm** [comment]
@xak 
This issue needs to labeled accordingly when it is ready to review. 
Which label you are using for that?

**Comment by joseegm** [comment]
### New Design for reference
<img width="1155" alt="screen shot 2017-06-27 at 15 04 05" src="https://user-images.githubusercontent.com/22662903/27588938-14b3d6fa-5b4a-11e7-9281-370ae7f9059d.png">

<img width="1281" alt="screen shot 2017-06-27 at 15 06 10" src="https://user-images.githubusercontent.com/22662903/27589068-5ff85ed8-5b4a-11e7-9167-2c32a2e07ec7.png">
