### ISSUE TITLE
Need type specs for the library

### ISSUE THREAD

**Issue by xak** [SAP/techne#721]
Just like we have a controlled color palette, we need a controlled type hierarchy. We don't want to hard code type values in each component so this needs to be established sooner than later.

The Cards, for example, use the following:
* Primary Value:  18px/22px (line-height)
* Secondary Value: 13px/19px
* Label: 12px/auto

This is what is implemented right now but I don't think this reflects any actual deliverables. 
https://sapse.invisionapp.com/share/DTBXJCSJW#/235917133_Core-TypeAndFonts

Just like the colors, this is important for theming. We want to establish a base type unit (browser default is 16px) and build from that unit. If a "hard-of-sight" theme needs to be implemented later we can change one unit and the whole system will adjust.

We can just hard code the value for now but it'll be harder to change the more we build out.

**Comment by xak** [comment]
@joseegm @LeoT7508 If this can be prioritized it would be very helpful. Note this is distinct from the website itself, which can use a whole different type hierarchy.

**Comment by joseegm** [comment]
@LeoT7508 
Please take a look if the *sizes*
https://sapse.invisionapp.com/share/DTBXJCSJW#/screens/235917133_Core-TypeAndFonts
are still correct. 

@xak 
Would be helpful to have the same base 10 for the font sizes, stating with 15px, for the base font. Use em for the line-height: 18px/22px ->  18px/1.2em. It is more easy to follow; fixed px for line-height will also be okay if they are consistent and also base 10.

@LeoT7508 
We should think about removing the dependency for Dosis, maybe just use the default fonts, to reduce the complexity and dependencies. Or choose other font that don't as "geeky" as Dosis. SAP uses "Benton Sans" which is a very nice font (https://www.sapbrandtools.com/font/#font-details)

It can be also other Open Source font that we can use.

What you think?

**Comment by LeoT7508** [comment]
@xak 
I am going to put together the font guide this morning. 

@joseegm 
Dosis is used mostly for "h" values so I think we should be ok with what we have. I'm sticking with Open Sans as our base font.

**Comment by LeoT7508** [comment]
@xak @joseegm 

Updated Typography guide. 

![techne_2 0_typography_master](https://user-images.githubusercontent.com/28761982/27201242-94b38588-51e2-11e7-81a1-f42072e514d1.jpg)

**Comment by xak** [comment]
@joseegm We'll def set the type up relative to a base — https://github.com/SAP/techne/blob/v2.0/src/styles/core/_settings.scss#L27. Just need to modify the values that are already set up. The `0` value is the base and that gets set as the default variable a little lower on the page which is used in `elements.scss` to set the body. I don't make any other sizes available with vars since the `type($size, $style)` mixin should be used instead. The line-height, def, relative too. The `em` unit isn't necessary, `1.2` does the same thing.

Sorted this with @LeoT7508 today so please consider this issue resolved with implementation details at #729. Thanks!
