### ISSUE TITLE
Investigate purpose and content for the "Styles" page (former Guidelines on v1.5.x)

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#726]
Goal 1: Collect the content that can be put under the "Styles" page on the main navigation.

As the new [components list](https://github.com/SAP/techne/wiki/Techne-Components)  already contains:
* Colors
* Typography

On the current "guidelines" page, the relevant content is:
1. Tone & Voice
2. Punctuation & Capitalisation
3. Messaging & Dialogs
4. Language and Translation
5. System Errors
6. Writing Help
7. Accessibility

The points 1..6 can be grouped as "textual information and writting guidelines". Now... lately we have been converging those with the guidelines Team Q already have in place. Right now they are corresponding.

**Question 1**: It will makes sense to link to Team Q guidelines or keep this information on the Techne website?

Keep in mind Team Q guidelines are widely used in YaaS and are more complete that ours can ever be.

The accessibility information can be added individually for every component and explain what `aria` and other accessibility parameters/helpers are needed. That can be done in other tab as per component needs.

@denisewildner @jeannewalters @xak 
I need your input on this.

**Comment by joseegm** [comment]
**Question 2**: Should we also display the information about the typography and colors again on this page.

**Comment by joseegm** [comment]
**Question 3**: Should we repurpose this page as follows?
* Techne Goals
* Info about the tone and voice; link to Team Q. Guidelines --- Alternative: reproduce the Team Q guidelines on Techne Website --- Keep the current info about textual information.
* Techne Philosophy
* Accessibility more in deep explanation.

**Comment by joseegm** [comment]
@denisewildner @jeannewalters @xak
This has been seating here since almost 1 week.
I'll tend for https://github.com/SAP/techne/issues/726#issuecomment-308550631
Any inputs, ideas, etc?

**Comment by denisewildner** [comment]
We should definitely align with Team Q guidelines. This wasn't really done before.

**Comment by xak** [comment]
@joseegm If this is a high priority then let's discuss it in the UX meeting tomorrow. We can use that time to prioritize topics and issues for the coming week with clear expectations and outputs. This could be assigned to a specific person to come up with a recommendation/deliverable.

**Comment by joseegm** [comment]
@xak Can you just put your ideas or feedback here? 
Is a waste of time to wait 16+ hours for that.

**Comment by jeannewalters** [comment]
@joseegm @denisewildner @xak Can someone post a link to the Team Q guidelines? Are we planning on completely aligning with them - if they make a change, how do we know about it? If we post the content on the Techne website, we could manage the approach. Would all outside teams be able to access the link to their guidelines?  These are some things I would like to have a UX call about and discuss as a UX team before we make this decision.

**Comment by joseegm** [comment]
@jeannewalters 
Yes, we did a complete alignment with Team Q on Feb and released a updated version to Tone and Voice. No further alignment needed.

Style and Standards are at: https://devportal-dev.stage.yaas.io/tools/documentationguidelines/110_StyleandStandards.html

No need to post the whole content on Techne website since it is visible on the above link. 

All external and internal teams have access to it.

It is better, as pointed by @denisewildner, to don't have duplicated information and linking to the Style and Standards. That answer the **question 1* on https://github.com/SAP/techne/issues/726#issue-236000882

We don't need a call to decide, when that all elements are already here.

Questions 2 and 3 still open.

**Comment by denisewildner** [comment]
Update on Team Q Styles and Standards from Kristie Herd yesterday:
[21/06/2017, 18:11:51] Herd, Kristine: FYI we are in the middle of splitting the SDK from the Guidelines, so please use our new ones.
Not yet released: https://devportal-dev.stage.yaas.io/tools/documentationguidelines/index.html but will be soon.
This is much easier to read, more succinct, and better organized.
It's still a WIP so you will see some things changed. But Mindy is done with the Styles and Standards section.

**Comment by joseegm** [comment]
**Question 2**:
Should we also display the information about the typography and colors again on this page? **Yes**

**Question 3**: 
https://github.com/SAP/techne/issues/726#issuecomment-308550631
Add also some of this content.

### Final page structure
1. Main usage copy text: Emphasising the Business UX
2. Techne philosophy
3. Use of Color
4. Themes
5. Info and link to Team Q - Style and Standard Guidelines
6. Accessibility info
