### ISSUE TITLE
Form Input inventory

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#733]
Goal: have in inventory of at most input line uses cases.

### The form inputs Current cases we have now:
https://techne.yaas.io/components/Form-Elements.html
* Normal
* Password
* Textarea

![screen shot 2017-06-19 at 13 50 58](https://user-images.githubusercontent.com/22662903/27283828-68ece1f8-54f6-11e7-8ca4-21cea14a0bec.png)

*Note*: Not to be confused with "states" of the input field like: pristine, error, focused, etc.

**Comment by joseegm** [comment]
### Form inputs for v2.0 and their usage
* **Standard**:  for Text entry; names, identifiers, etc.
* **Number**: for Numeric information only; prices, amounts, etc.
* **Password**: Info hidden by default.
* **Units**: display units; prices with currencies, etc.
* **Icon**: display an icon to the left or right; search boxes, clear input button, etc.
* **Limited**: is limited to N amount of characters with an indicator of how many characters left.
* **Read only**: only to display information in the context of a form.
* **Action**: display also a button (preferably with icon); add items to a list.

**Comment by joseegm** [comment]
@denisewildner @jeannewalters 
Do we have other uses cases?

*Note*: This issue is only to collect the different types. UX and Visuals will be treated in separate issues.

**Comment by xak** [comment]
I created an Invision board to collect examples of existing UIs — and added a Forms section. We should gather examples from EC as well. https://sapse.invisionapp.com/d/main#/projects/boards/5484242

**Comment by joseegm** [comment]
Not posting is products screenshots is, of course a must, but links to protected wiki pages it will be fine. We can also avoid that and only post small screenshots of individual elements.

**Comment by joseegm** [comment]
With the Elements created on #735 and the types on https://github.com/SAP/techne/issues/733#issuecomment-309372007 and looking at the uses cases from https://github.com/SAP/techne/issues/733#issuecomment-309551829

### Inputs types with standardised elements
![input-lines 2](https://user-images.githubusercontent.com/22662903/27323638-875acc52-55a2-11e7-8c2b-ada005b3cac8.png)

**Comment by joseegm** [comment]
This is done

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_inputs types with common elements](https://user-images.githubusercontent.com/28761982/27450174-63e5a71a-5750-11e7-979d-060dd1245d6e.jpg)

**Comment by joseegm** [comment]
Reopening this to keep it in context

@LeoT7508 

**Action and Action + Icon**: Since the **Icon + Action** have a *accent* color, I think we can give the **Action** and the **Action + Icon** the same color to keep it consistent

**Read only**: is missing the border.

**Comment by LeoT7508** [comment]
@joseegm 

The colors aren't completely flushed out here. I made them black as placeholder. But in theory yes they will probably be a grey shade or the action blue from the color palette. 

Jeanne and Irla are still having UX talks about how the fields should look. They were supposed to talk today to finalize.
