### ISSUE TITLE
Docs: clean up the visual inconsistency

### ISSUE THREAD

**Issue by like-me1** [SAP/techne#734]
Logo SVG is misaligned (flush to the top)
Logo alt should be "Techne" not "YaaS"
"YAAS" should be white
Dotted divider should be grayish color
Top nav items shouldn't be 17px and normal weight
Top nav hover states should be more like a tab (not filled fully to the top of the nav)
Items should have more spacing around them
SAP logo is misaligned
Second-level nav items look a tad brighter and selected state shouldn't be bold
At about 870px browser width the top nav breaks (becomes taller before the SAP logo is hidden)
The responsive nav and footer have some inconsistencies as well

**Comment by xak** [comment]
@like-me1 This is getting closer but it's not quite right. When I open a tab for Yaas.io (Techne or other pages) next to this and click back and forth you can see a lot of small issues. They should look exactly the same.

- The YAAS text is more bold
- The divider line is more to the right (probably from the bold text above) and extends below the top blue bar
- Nav items are spaced a little differently
- Nav items are a pixel or two lower
- Hover on nav items extends a pixel below the top bar
- SAP Hybris logo is a pixel or two to the right

When I squish the browser to tablet size, the nav items are very close.

At smaller sizes the dropdown nav are not different too.

- The "My Account" should have a toggle next to it
- That dropdown is not styled the same

And the side nav, that is the second-level nav at small screens, is not the same and the hamburger is not turning into the close icon.

Lastly, when you commit, please use `#734` so it gets picked up by the issue. `CCE-734` will not mean anything to GitHub.

Thanks.

**Comment by like-me1** [comment]
@xak, I will appreciate to have numbers next time instead of "little differently", "one or two pixels". Thanks

**Comment by saadmhybris** [comment]
@like-me1  is this issue complete? can we close it?

**Comment by like-me1** [comment]
@saadmhybris nope, it's in progress and as soon as I'm done I'll assign it to @xak, because he knows all details of it

**Comment by saadmhybris** [comment]
@like-me1 - I am picking up all the tickets related to techne documentation site to free up zack's plate. I'll take a look at the PR just opened and leave any comments on the PR.

**Comment by joseegm** [comment]
@like-me1 @saadmhybris 
Don't forget to reference this issue from the PR for easy linking.

**Comment by like-me1** [comment]
@saadmhybris have you reviewed it?
