### ISSUE TITLE
Define form input Help elements

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#738]
Goal: Identify and define all Help elements that can be used for the form inputs.

### Current help elements v1.5.x
* **Hint**: Help text displayed bellow the input field.
  ![screen shot 2017-06-19 at 13 12 56](https://user-images.githubusercontent.com/22662903/27282678-42c8387e-54f1-11e7-9d1a-bb09bd129263.png)
* **Help Tooltip**:  help Icon displayed above the input line. The icon trigger a tool tip with the help text. 
  ![screen shot 2017-06-19 at 13 13 42](https://user-images.githubusercontent.com/22662903/27282764-adc09ae0-54f1-11e7-9b0f-284120508cd2.png)
* **Help tooltip for Read Only inputs**:  displayed along static form fields
  ![screen shot 2017-06-19 at 13 21 30](https://user-images.githubusercontent.com/22662903/27282904-408e6924-54f2-11e7-9ea2-23605bb2681a.png)

**Comment by denisewildner** [comment]
Current rule: If help mode is switched off via help icon in Builder upper navigation bar, help icon is visible on right side above input field. On hover tooltip with help text shows.
If help mode is switched on, icon and helptext is always visible underneath input field.
Also see: https://techne.yaas.io/components/Help-and-Validation.html
![screen shot 2017-06-19 at 13 37 05](https://user-images.githubusercontent.com/7449143/27283555-232b9d36-54f5-11e7-877c-6a824c99dba1.png)

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_inputfields](https://user-images.githubusercontent.com/28761982/27450192-78db2794-5750-11e7-880d-b9f04df65365.jpg)

**Comment by joseegm** [comment]
Cropped the image to keep it in context with the goal of this issue
![27450192-78db2794-5750-11e7-880d-b9f04df65365](https://user-images.githubusercontent.com/22662903/27452816-58566788-5794-11e7-90c0-d043d3b3cb5a.jpg)

@LeoT7508 
1. We had some request in the past to make the tooltips "lighter", a lighter color will do the trick probably. Right now they look very "heavy". Can we give it a try?

**Side note**
The "read only" field have as per UX description on https://github.com/SAP/techne/wiki/Form-Inputs#types-and-variants-733, and discussion on https://github.com/SAP/techne/issues/735#issuecomment-309455851 and decided on https://github.com/SAP/techne/issues/735#issuecomment-309468765 have a border now.
![27323638-875acc52-55a2-11e7-8c2b-ada005b3cac8](https://user-images.githubusercontent.com/22662903/27453410-a718247c-5796-11e7-8c8f-a2a3d4219091.png)
That is better to maintain layout structure.

That means, we can use the same positioning as with the normal input fields. No action needed regarding this side note.

**Comment by joseegm** [comment]
Result of this issues is only to define the elements, info now available at https://github.com/SAP/techne/wiki/Form-Inputs#help-elements-738

The visuals for in another issue #757

**Comment by LeoT7508** [comment]
@joseegm 

If we make a significant color change, enough to notice, we fail the accessibility contrast requirements. So I think it would be wise to stick with these colors.

**Comment by joseegm** [comment]
@LeoT7508 
The current color combination fails the [WCAG 2.0 AAA](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) guidelines.

That can be tested at http://accessible-colors.com/
![screen shot 2017-06-26 at 08 31 48](https://user-images.githubusercontent.com/22662903/27527136-5abab5a2-5a4a-11e7-8325-160ef4bf71e7.png)

We can definitely try a lighter color.

**Comment by joseegm** [comment]
The goals of this issue has been met, visuals continue at #757.
Closing the conversation to keep things in context
