### ISSUE TITLE
Define Main content website components inflexion points

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#740]
Goal: As per #739, define the inflexion points for the components on **Content Component** for the Website.

### Related tasks
- [x] Component Definitions #741

**Comment by joseegm** [comment]
### Website Component Page Wireframe
![27042960-db100598-4f98-11e7-8269-00d7bea74d33](https://user-images.githubusercontent.com/22662903/27294792-18dbdf46-551b-11e7-8de7-ccbf5d51d9a5.png)
### Website Component Page Visuals
![00 4_techne_templateguides](https://user-images.githubusercontent.com/22662903/27294828-337fb728-551b-11e7-945f-17906a51d2aa.jpg)
### Website Styles Page visuals
![00 2_techne_styletemplateguides](https://user-images.githubusercontent.com/22662903/27294852-47e0c978-551b-11e7-82f4-4b4c60c14d7b.jpg)

**Comment by joseegm** [comment]
### Tablet Inflexion
* **Top Section**: stays at two columns.
* **Horizontal Section**: the layout behaves the same as the Vertical Section.
* **Vertical Section**: the layout stays the same.

![table-content-components-inflexion](https://user-images.githubusercontent.com/22662903/27391507-6c45bc08-56a4-11e7-993b-1395aa731fbf.png)

### Mobile Inflexion
* **Top Section**: display the title and content in a vertical way.
* **Horizontal Section**: the layout behaves the same as the vertical section.
* **Vertical Section**: the layout stays the same.

![mobile-content-components-inflexion](https://user-images.githubusercontent.com/22662903/27391521-762ce6f6-56a4-11e7-9323-b09d04510655.png)

**Comment by xak** [comment]
Is there a max content width or should all containers be fluid and fill the entire content area?

This image is more related to the library layouts but it still illustrates the concept ...

![mastertemplate--xl](https://user-images.githubusercontent.com/424119/27396711-8e75ce56-5679-11e7-91ad-cbcec9c47bce.png)

**Comment by joseegm** [comment]
The behavior of the elements for every Section is as illustrated bellow.

### Desktop
![website-conent-components](https://user-images.githubusercontent.com/22662903/27428489-813cce0a-5742-11e7-9778-5f800286d51d.png)

### Tablet
![table-content-components-inflexion](https://user-images.githubusercontent.com/22662903/27428511-8eb43708-5742-11e7-9695-0b15e725e82b.png)

### Mobile
![mobile-content-components-inflexion](https://user-images.githubusercontent.com/22662903/27428523-9a0a946c-5742-11e7-81d4-ef996b0a59cb.png)
