### ISSUE TITLE
Usage of White Space

### ISSUE THREAD

**Issue by bachofner** [SAP/techne#748]
Hi guys,
in our projects we need a very efficient use of space for our power users. Lists, Cards, Headlines, etc should be very sensitive about whitespace, fontsizes and the use of margins and paddings.
Eg. for Cards we would prefer like 10px padding instead of 40px.
Will there be a "Efficient-Mode" that can be turned on. That would be awesome. A hard override needs to be testest for every component after every update. So not ideal ;-)

Thank you,
André

**Comment by joseegm** [comment]
### Feature: **Spacing**.

It will have two modes:
* **Normal**: Default; No action needed, use of wide margins and paddings.
* **Compact**: Reduced margins, paddings and separating spacing to have more information density on the same screen real state.


| Normal  |  Compact  |
|---|---|
| ![normal spacing](https://user-images.githubusercontent.com/22662903/27426742-ed63a050-573c-11e7-8a6f-792ba1dfbd8f.png) | ![compact spacing](https://user-images.githubusercontent.com/22662903/27426765-fe167864-573c-11e7-9f54-5252c519bcd0.png) |

@bachofner 
This solution will suffice your Uses Cases for EC?

**Comment by xak** [comment]
@bachofner I'm collecting screen shots of Hybris interfaces on Invision. I can get you an account and added to our project or you can just throw them somewhere and I can grab them. **Don't want to post them here of course.** But really anything you have would be useful, some screens with lots of fields, edit modes, creation modes.

I want to create a library to help us in our research and discovery.

**Comment by joseegm** [comment]
This request has been expanded gonna be addressed at #751
