### ISSUE TITLE
Review Cards Implementation

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#754]
Goal: Check for the deployed result of the Cards implementation against the design

**Cards Design implementation**: #678
**Cards implementation details**: #709
Deployed: http://sap.github.io/techne/www/components/cards.html - stand June 23th. 

### Results
**Commons cards**: https://github.com/SAP/techne/issues/678#issuecomment-305724490
  1. Label on the read only card: color don't match the design

| Design | Implementation |
|---|---|
| ![screen shot 2017-06-23 at 09 19 56](https://user-images.githubusercontent.com/22662903/27470656-498d05f2-57f5-11e7-916d-900c03f0cde2.png)  | ![screen shot 2017-06-23 at 09 20 13](https://user-images.githubusercontent.com/22662903/27470663-529d3658-57f5-11e7-94e0-fbb49177359e.png) |
  2. Card showcasing a different layout is missing
  ![screen shot 2017-06-23 at 09 11 54](https://user-images.githubusercontent.com/22662903/27470421-154d3d30-57f4-11e7-923f-371dda70270b.png)
  3. When reducing the card width to 370px. The labels dont's wrap correctly

  | Design | Implementation |
  |---|---|
  |  ![screen shot 2017-06-23 at 09 17 01](https://user-images.githubusercontent.com/22662903/27470561-d9860f60-57f4-11e7-9a96-edcb02ca3bbe.png)  | ![screen shot 2017-06-23 at 09 15 10](https://user-images.githubusercontent.com/22662903/27470546-ce78114a-57f4-11e7-9d7e-26b199f8ecd0.png)  |
   
**Cards With Media**
1. Media element is not square

 | Design | Implementation |
  |---|---|
  | ![screen shot 2017-06-23 at 09 25 08](https://user-images.githubusercontent.com/22662903/27470883-2f403d6c-57f6-11e7-9dc6-b40bc3731849.png) | ![screen shot 2017-06-23 at 09 26 18](https://user-images.githubusercontent.com/22662903/27470906-39bd22a0-57f6-11e7-9aaa-a93b1c10bbc0.png) |

2. Missing Card with image on top
3. Missing Example where the image is smaller than the place holder element
  ![screen shot 2017-06-23 at 09 32 24](https://user-images.githubusercontent.com/22662903/27471103-e7fb088c-57f6-11e7-8b29-acb9ca8b67b0.png)
4. For the implementation please use these Hybris stock images to test the implementation
    - **Square**: https://techne.yaas.io/images/product-thumbnail.png
    - **Portrait**: https://techne.yaas.io/images/product-thumbnail-tall.png
    - **Landscape**: https://techne.yaas.io/images/product-thumbnail-wide.png

**Comment by xak** [comment]
The applicable changes have been implemented ... see #776 

## Overall changes
After looking at the current card implementation and at the ["alternate" use case](https://sapse.invisionapp.com/d/main#/projects/boards/5484242/165700287) for Cards, I decided to make the button option required just as the current cards require `cardRow cardRowClickable` to enable the effects. So now the static/readonly card becomes the base component.

Common card
- Label has been adjusted to match the design. A colored label here, however, would be allowed. Note, there is nothing coded in the Cards for to indicate status, a dev would need to use the appropriate `label` to indicate status. I'm just simulating the colors with helper classes. This will be changed once we complete `label`s
- The "alternate" card layout is now included. I'm viewing this as a custom usage of cards. As long as you include the `__content` element you get the padding but you can bring your own custom HTML to the body of the card. The content shown looks close to a "readonly" form field, once those are complete this markup example can change from the simulated code.
- Leo and I have discussed the labels for the Cards and decided against using a formal divider. Devs will be able to use a pipe `|` between the statuses. It is hard to enforce presentational dividers ([see comments](https://sapse.invisionapp.com/d/main#/console/11153756/239183941/comments/82884798)). The `__status` element is just a container so labels inside will be independent.  If this is a very common use case, we can revisit it with the Card groups when we see responsive behavior.

## Cards with media
- Only the icon card was part of this implementation task — https://sapse.invisionapp.com/share/DTBXJCSJW#/screens/239183942
- Updated with Hybris stock image.

**Comment by joseegm** [comment]
@xak 
Changes are not beed merged or deployed
The stand https://github.com/SAP/techne/commit/9c8adda0c9e56d79c7115b118a5f908bc91065c9 doesn't content the changes yet. 

Let me know when they are merged and deployed to make the review.

**Comment by xak** [comment]
The PR is #776 and ready for review. I don't know what the `deploy` commit you reference means for this issue.

**Comment by joseegm** [comment]
Deployed means that we are using the v2.0 as develop branch, and the changes are reviewed when they are deployed on 
http://sap.github.io/techne/

**Comment by xak** [comment]
I included details here so the code reviewer has some context for what changed. I have moved this issue back to "In Progress" and removed the "review" label.

**Comment by saadmhybris** [comment]
Sorry if this was discussed already - 

- Do we not wanna show multiple cards? 
- There is no responsive behaviour on the cards (or the left nav which is a separate issue) 
- Are we doing away with list view? I recall this discussion about using a list vs. card list, but just wanted to confirm.

**Comment by joseegm** [comment]
@saadmhybris 
The whole design process for the cards went down at
https://github.com/SAP/techne/issues/678

There we decided to removed the cards lists and adopt the **Product Thumbnail** into the cards.

**Comment by xak** [comment]
The card groups is at #730. We don't have exact specs for the layout yet but we can at least build out the 2 and 3 cols. Leo and I are working through the breakpoint and layout specs now. Those will be put into issues soon.

**Comment by saadmhybris** [comment]
ok, thanks for the info.

**Comment by xak** [comment]
http://sap.github.io/techne/www/components/cards.html

**Comment by joseegm** [comment]
@xak 

### Points still missing from https://github.com/SAP/techne/issues/754#issue-238057596 

**Cards With Media**
1. Media element is not square

 | Design | Implementation |
  |---|---|
  | ![screen shot 2017-06-23 at 09 25 08](https://user-images.githubusercontent.com/22662903/27470883-2f403d6c-57f6-11e7-9dc6-b40bc3731849.png) | ![screen shot 2017-07-07 at 08 56 16](https://user-images.githubusercontent.com/22662903/27946733-558c665a-62f3-11e7-983a-f3fb0e856876.png)  |

2. **Missing Card with image on top**
![screen shot 2017-07-07 at 09 06 18](https://user-images.githubusercontent.com/22662903/27946793-911759c8-62f3-11e7-8f7a-41c2500db8a8.png)

3. Missing Example where the image is smaller than the place holder element
  ![screen shot 2017-06-23 at 09 32 24](https://user-images.githubusercontent.com/22662903/27471103-e7fb088c-57f6-11e7-8b29-acb9ca8b67b0.png)

**Comment by xak** [comment]
Please see #724. The card types in Invision and present in the PSD provided to me are all implemented. I have not seen final designs for 1 and 3, and 2 (the vertical card) has been implemented in the branch `feature/724` which is now assigned for review.

Please open a new issue and connect with Leo to provide the PSD and update Invision with the addt'l card types and we can implement those.

Thanks.

**Comment by joseegm** [comment]
@xak 
All information have to be visible on github. That's why we are using it. To have one single point of up to date information. 

**See that invision is not always up to date and have broken links, so please use the information available on github. That's always up to date.**

Is simply not possible to miss.

The cards design was, as stated before, already posted to github at https://github.com/SAP/techne/issues/678#issuecomment-305724490 - Jun 2nd, 2017
and you commented on the same thread at https://github.com/SAP/techne/issues/678#issuecomment-306950136 - Jun 8th, 2017.

**This still belong to the same issue that is been reviewed.** No need to open any new issue. All information was available at the right time.

@LeoT7508 
We agreed to have the latest files always, right?
On this folder on Box:
https://app.box.com/folder/29116880878

**Comment by xak** [comment]
Leo and I have been working to maintain a single repo for all the designs on Invision. We are still ironing it out so I do apologize for broken links but I believe those have been fixed now.

When designs are complete, a link to the final PSD and updated screens on Invision (or Zeplin maybe down the line) will signal the handoff to development. **I will expect those deliverables so the dev team can squarely focus on the implementation.**

This does not preclude you from posting the screens and maintaining the documentation you desire here on Github for the sake of transparency.

Thanks.

**Comment by LeoT7508** [comment]
@joseegm @xak 

I think a lot the confusion comes from requests and issues the Smart Edit team has, if we are going to be using their feedback and input then we need to make sure they follow up with us promptly, not a week later about details they feel need to be prioritized. As of now we have a lot of small details floating around that aren't being finalized, so its hard to keep an "updated" design when there is still back and forth going on. I think we need to do a better job of managing how we work together, how Techne impacts and cascades down to other products and not how other products affect Techne.

**Comment by xak** [comment]
@LeoT7508 Agreed, we've discussed what I need for the implementation. I've synced the Box folder locally and always use the files in that folder. Photoshop syncs with Invision so there shouldn't be much overhead there. If any of that is tedious for you I'm sure we can find a compromise. It's just most important to me that the design be "close to final" before implementation begins. 

I have recommendations on how to improve the UX process but in the spirit of moving forward, I'll let you and Jose come to agreement on what you need and consider a successful handoff from UX. Please keep me updated so we can all be aware of the expectations.

Thanks.

**Comment by LeoT7508** [comment]
@xak 

Im 100% on board with using Invision and syncing things that way, all good on that end. 

I just synced files again to make sure everything is fresh for Cards, Input Fields, and colors to make sure things are updated. 

Thanks Zack.

**Comment by joseegm** [comment]
@xak 
Okay, I'll start including the task "update PSD on Box" from now on, in every Visual Design issue.

Design issues get the label "design done" after the review period. At that point they are ready to for implementation. List available at
https://github.com/SAP/techne/issues?q=is%3Aissue+is%3Aclosed+label%3A%22design+done%22

That was agreed months ago. And communicated in a meeting. The same process has been followed since then and hasn't changed.

When all is completed all the info will be posted on the wiki, the same we did with the inputs fields. https://github.com/SAP/techne/wiki/Form-Inputs

Keep in mind the cards was the first component, so the information and process was already improved on the inputs -the second- already.

@LeoT7508 
There is a standard period to respond to issues, 48 working hours, two full working days. That was clearly communicated also, to everybody collaborating actively in this project, including Jeanne and Irla.

If no feedback has been provided by that period, issues can move on, with the current information available on the issue. 

That will stop any possible bottle neck.

Thx

**Comment by LeoT7508** [comment]
@joseegm 

48 working hours, two full working days for feedback. This is noted and I will stick to this. 

Thank you.

**Comment by saadmhybris** [comment]
@joseegm - is there still work to be done here? just making sure all loose ends are taken care of before working on #775
