### ISSUE TITLE
Can the cards implementation be released to a closed alpha?

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#755]
The implementation of few of the card types is finished #709 
They are still things to fix #754 

After items on #754 are finished.
**Can we release that as part of a closed alpha as stand alone component?**

We can use swinkas front-end devs to try it out.

**Comment by xak** [comment]
@joseegm See #775.

**Comment by joseegm** [comment]
@xak 
Any date on that?

**Comment by xak** [comment]
@joseegm See #775

**Comment by joseegm** [comment]
@xak 
#775 have no date anywhere.

**Comment by xak** [comment]
It is in progress. It can be released once the dependent reviews are complete. See #775
