### ISSUE TITLE
Form inputs Help tooltip visuals

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#757]
Goal: revisit the visuals for the Help elements tooltip.

### Form inputs help elements
https://github.com/SAP/techne/wiki/Form-Inputs#help-elements-738

> From https://github.com/SAP/techne/issues/738#issuecomment-310488414

Cropped the image to keep it in context with the goal of this issue
![27450192-78db2794-5750-11e7-880d-b9f04df65365](https://user-images.githubusercontent.com/22662903/27452816-58566788-5794-11e7-90c0-d043d3b3cb5a.jpg)

@LeoT7508 
1. We had some request in the past to make the tooltips "lighter", a lighter color will do the trick probably. Right now they look very "heavy". Can we give it a try?

**Side note**
The "read only" field have as per UX description on https://github.com/SAP/techne/wiki/Form-Inputs#types-and-variants-733, and discussion on https://github.com/SAP/techne/issues/735#issuecomment-309455851 and decided on https://github.com/SAP/techne/issues/735#issuecomment-309468765 have a border now.
![27323638-875acc52-55a2-11e7-8c2b-ada005b3cac8](https://user-images.githubusercontent.com/22662903/27453410-a718247c-5796-11e7-8c8f-a2a3d4219091.png)
That is better to maintain layout structure.

That means, we can use the same positioning as with the normal input fields. No action needed regarding this side note.

**Comment by joseegm** [comment]
From @LeoT7508 https://github.com/SAP/techne/issues/738#issuecomment-310706459
@joseegm 

If we make a significant color change, enough to notice, we fail the accessibility contrast requirements. So I think it would be wise to stick with these colors.

**Comment by joseegm** [comment]
@LeoT7508 
The current color combination fails the [WCAG 2.0 AAA](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-contrast.html) guidelines.

That can be tested at http://accessible-colors.com/
![screen shot 2017-06-26 at 08 31 48](https://user-images.githubusercontent.com/22662903/27527136-5abab5a2-5a4a-11e7-8325-160ef4bf71e7.png)

We can definitely try a lighter color.

**Comment by LeoT7508** [comment]
@joseegm 

I think maybe you are using an old visual, the color you are using here is not right. I used the color they recommended once I saw the colors weren't passing the test. I use this same site to check my colors. According to this we definitely cannot use a lighter color, its showing that a lighter color does not work, and will fail accessibility test. We will more forward with #4D5A6C.

**Comment by joseegm** [comment]
@LeoT7508 
No. I got the color from the file on Box. #808FA7. 
Moving with #4D5A6C is fine. We can see about the lighter version once it is implemented. It is easier to modify.

So, the new color is #4D5A6C. With that and the updated Read only frame we are good to go on this.
Can you do the changes and update this thread, I'll then post the result in the wiki afterwards.

**Comment by LeoT7508** [comment]
@joseegm 

Thats interesting as that color doesn't currently exist in our color palette. Maybe you sampled it incorrectly. Either way this should work. 

![screen shot 2017-06-26 at 10 49 20 am](https://user-images.githubusercontent.com/28761982/27548081-718bf45e-5a5d-11e7-8463-741800f6ef57.png)


We are still discussing read only as I write this note. Jeanne feels strongly that we should test it. Hana is back from PTO tomorrow to conduct the user test.

**Comment by LeoT7508** [comment]
@joseegm 

![techne_2 0_inputfields](https://user-images.githubusercontent.com/28761982/27642826-866b3a0e-5be5-11e7-9242-09548f94bd51.jpg)

**Comment by joseegm** [comment]
This looks good, I'll put it for review.
Thanks @LeoT7508

**Comment by joseegm** [comment]
### Final
![27699293-63e0ab56-5cbf-11e7-98ab-c0aa8fb3549a 1](https://user-images.githubusercontent.com/22662903/27738667-486841ac-5dac-11e7-8a16-d0e170a76ecc.jpg)
