### ISSUE TITLE
Action Bar Design

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#758]
### Goals
1. Define UX Elements #759
2. Improve the Interaction design #793 
3. Define clear usage patterns: Desktop https://github.com/SAP/techne/issues/793#issuecomment-314776899, Mobile https://github.com/SAP/techne/issues/793#issuecomment-315319278
4. Refresh the Visual Design #759

### Current state v1.5.x
![screen shot 2017-06-23 at 15 55 13](https://user-images.githubusercontent.com/22662903/27485467-1347d818-582d-11e7-95df-d23f10992943.png)

### Pain points
1. Confusion of where the back button goes. Due to inconsistent behaviour / implementation.
2. Inconsistent behavior of **Cancel** / **Save**.
3. Inconsistent behavior when used to navigate in a multi-step flow. **Back**, **Cancel** / **Next**.
4. Not able to display the available and current steps in a multi-step flow. 
5. Dimension problem for localised buttons. Russian and French are Edge Cases.
6. The same Primary buttton have different actions, on the same screen, depending on the context.

**Comment by joseegm** [comment]
Action Bar Main design elements are at #759

**Comment by joseegm** [comment]
from Jeanne at https://github.com/SAP/techne/issues/759#issuecomment-311342559

Denise and I worked with him [Dieter] to remove the word, "Back" and just have the arrow to differentiate it from the sidebar

**Comment by joseegm** [comment]
### New Design for reference
<img width="1155" alt="screen shot 2017-06-27 at 15 04 05" src="https://user-images.githubusercontent.com/22662903/27588938-14b3d6fa-5b4a-11e7-9281-370ae7f9059d.png">

<img width="1281" alt="screen shot 2017-06-27 at 15 06 10" src="https://user-images.githubusercontent.com/22662903/27589068-5ff85ed8-5b4a-11e7-9167-2c32a2e07ec7.png">

**Comment by jeannewalters** [comment]
@joseegm  You've captured the scenarios when there are actions on the page. Dieter also created an example for when it's a landing page with a primary button, a table or tabs.
![screen shot 2017-06-27 at 11 00 15 am](https://user-images.githubusercontent.com/24274321/27594544-0a71870e-5b28-11e7-9c53-2fc65004741f.png)
![screen shot 2017-06-27 at 11 00 06 am](https://user-images.githubusercontent.com/24274321/27594543-0a6c780e-5b28-11e7-9931-cb38bc04f7cb.png)
![screen shot 2017-06-27 at 10 59 45 am](https://user-images.githubusercontent.com/24274321/27594542-0a6901ba-5b28-11e7-9af3-46965dea27eb.png)

**Comment by joseegm** [comment]
@LeoT7508 
Yes that is the latest stand of the design. Colors will most probably change.

@jeannewalters 
The Use of back in the **Action Bar** and back on the **Side Navigation** may be better have that in its own discussion, they are not implemented consistently right now on YaaS. We may only need one of both.

Other use case for the bar is when the user is in a flow with multiple steps.
![screen shot 2017-06-28 at 11 50 27](https://user-images.githubusercontent.com/22662903/27631230-2a9cc8ec-5bf8-11e7-84c0-34c31286caba.png)

**Comment by xak** [comment]
@joseegm Since the Action Bar uses `icon` and `button` components, I recommend those be prioritized.

**Comment by joseegm** [comment]
@xak 
Button is in process at #782

**Comment by joseegm** [comment]
Uses cases and behaviour started at #793

**Comment by joseegm** [comment]
Flow/Steps and Mobile inflections now at #793

**Comment by joseegm** [comment]
UX Elemtns, Use Cases and Behaviours are now documented at
https://github.com/SAP/techne/wiki/Action-Bar-Design

**Comment by joseegm** [comment]
Closing this, since this tasks is continuing on #793
