### ISSUE TITLE
Action Bar Define UX Elements

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#759]
Goal: Identify, name and describe the UX Elements of the ActionBar

### Current state v1.5.x
![screen shot 2017-06-23 at 15 55 13](https://user-images.githubusercontent.com/22662903/27485467-1347d818-582d-11e7-95df-d23f10992943.png)

**Comment by joseegm** [comment]
### Action Bar main Elements
![image](https://user-images.githubusercontent.com/22662903/27581106-f34b7dd2-5b2c-11e7-8908-fc92f278f516.png)

| Element | Description |
|---|---|
| **Action Bar** | Is located at the top of the page. It shows the user the present location on the **Location Element**. Serves as a navigation element with the **Back Button**. Can have **Actions** on the Page, that perform over the whole content of the page, the **Actions Element** | 
| **Back Button** | Navigate the user back to the previous screen/step in the navigation hierarchy | 
| **Location Element** | Display the Current location in form of a Page title. Can display Steps in a Step-flow | 
| **Actions Element** | Display Actions that perform an action on the object the page is representing. Can display also "Save/Cancel" actions when content of the page is modified |

**Comment by jeannewalters** [comment]
@LeoT7508 Here's a place where I'd suggest you refer back to the last designs Dieter did on the toolbar. Denise and I worked with him to remove the word, "Back" and just have the arrow to differentiate it from the sidebar. I would add more but the link to Box where those visuals were is not longer working.  Let me know if you can give me access again and I will add more about the decisions that were made in that design to resolve issues that we were encountering with the current 1.5 design.

**Comment by joseegm** [comment]
@jeannewalters 
Thanks.

This issue is to **identify the UX Elements only**. The issue goal is stated at the very top
**Goal**: Identify, name and describe the UX Elements of the ActionBar

This issue is labeled 'review', the outcome to review are the UX Elements (https://github.com/SAP/techne/issues/759#issuecomment-311309593)

The pain points are added at the main tasks #758 

Visuals will have their own issues.

**Comment by jeannewalters** [comment]
@joseegm The designs included UX elements. I can't add further comments on that until I get access which is what I'm requesting from Leo. Thanks

**Comment by denisewildner** [comment]
@jeannewalters @LeoT7508 @joseegm When I think about it now – with consistency in mind – we should reconsider, if we better should have the description (=wording "BACK") underneath the icon there, too.

**Comment by LeoT7508** [comment]
@joseegm  @jeannewalters  @denisewildner 

From what I recall Dieter and I worked on this as the next step in the evolution of the Action Bar. 

![screen shot 2017-06-27 at 10 21 42 am](https://user-images.githubusercontent.com/28761982/27595576-ab39f4c4-5b22-11e7-805c-aa01e7001613.png)

Does this still hold weight?

**Comment by jeannewalters** [comment]
The goal in Dieter's design was to eliminate the noise.
- the elements next to each other (Back to <Page> in left nav and arrow inside the page do not work consistently but maybe I'm not understanding your comment about consistency. I think showing them differently (Back to Page and back arrow might be enough to make the user consider the differences.
![image](https://user-images.githubusercontent.com/24274321/27595292-4c09805c-5b2a-11e7-9d41-ba84ea11c989.png)

**Comment by jeannewalters** [comment]
@joseegm That is the for the user case when it's a detail page. There are other use cases though for that bar.

**Comment by joseegm** [comment]
@LeoT7508 @jeannewalters 

Answered on https://github.com/SAP/techne/issues/758#issuecomment-311612597 to keep all in context
