### ISSUE TITLE
Identify Color Palletes solutions

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#766]
Goal: List and Identify color Palletes solutions that can be suitable for Techne 2.0

### Preliminary list

| Approach | Description  |  Representation  |
|---|---|---|
| **[Material](https://material.io/guidelines/style/color.html#color-color-tool)** | *Main* and *Accent* colors and shades, from a fix set of palettes. On this approach every can have multiple variation with the identifier **50, 100, 200, 300, 400, 500, 600, 700, 800, 900**. Where **500** is the main shade and **<500** are lighther, **>500** are darker. | ![screen shot 2017-06-26 at 14 04 55](https://user-images.githubusercontent.com/22662903/27538573-f086462c-5a78-11e7-84e8-4dc1c047a3a7.png)  |
| **Named** | Having 3 main set of colors. **Brand/main**: The color most used across all UI. **Accent**: Used for Buttons and action. **Neutral**: used for grays. Every of this colors can have variations up and down on the spectrum: **light, lighter, lightest** and **dark, darker, darkest** | ![screen shot 2017-06-26 at 14 04 14](https://user-images.githubusercontent.com/22662903/27538615-272a1618-5a79-11e7-9dd3-bf1156513b98.png) |

Decision will take in count how easy is to implement, extensibility and flexibility for design.

**Comment by joseegm** [comment]
I'll like to go with the material approach and we can leverage the SAP Extended palette: https://www.sapbrandtools.com/graphics/#graphics-graphs. Scroll to the bottom.

**Comment by joseegm** [comment]
With both approaches we are missing the colors for: **warning**, **error**, **success**. Unless we have a 3rd palette for that.

**Comment by LeoT7508** [comment]
@joseegm 

I have to check in with @xak to make sure this fits in with his development system. Our goal was to keep as small a color palette as possible. I have to make sure this fits in with that ideology.

**Comment by joseegm** [comment]
@LeoT7508 
The approach now on the library is using **Named colors**

from https://github.com/SAP/techne/blob/v2.0/src/styles/core/_settings.scss#L51
```scss
$colors: (
    brand: #006fbb,
    accent: #fbc100,
    action: #009cdf,
    success: #61bf33,
    warning: #e96b1a,
    error: #df1919,
    lightest: #eef1f3,
    light: #d7d7d7,
    dark: #7f90a4,
    darkest: #21262c,
) !default;
```
So if we decide for that we have to extend it to have shades of the same color, but it is the same approach.

**Comment by LeoT7508** [comment]
@joseegm 

Zack and I are going to have a meeting tomorrow to go over this in more detail. I want to make sure it makes sense for him and for the design system we are creating. 

Thanks.

**Comment by joseegm** [comment]
@LeoT7508 @xak 
What are your inputs on this after your meeting?

**Comment by xak** [comment]
@joseegm We are still working through it.

**Comment by LeoT7508** [comment]
@joseegm 

As Zack mentioned we are still working through it, I should have something to post here later today, if not tomorrow for sure. 

I will keep you posted. 

Thanks.

**Comment by joseegm** [comment]
@xak @LeoT7508 
Please post the outcomes here if you already have it.

**Comment by joseegm** [comment]
@LeoT7508 @xak 
Guys, any news on this?

**Comment by LeoT7508** [comment]
@joseegm @xak 

As mentioned on the call earlier today, we are going with a cross between what Jose asked from, "material design" approach and our own, simple, growing, but also more strict version of color palettes with limited shades. 

![techne_2 0_colorpalette_master](https://user-images.githubusercontent.com/28761982/27875282-445daa1e-6178-11e7-961d-cb4b8a726f71.jpg)

**Comment by joseegm** [comment]
@LeoT7508  
Like this approach for Text and Neutral colors.

But it will fall short on real usage, for instance: Which colors to use for the Top and Side navigation, not the real color but the color name.

Accents colors are usually used for the actions. 

Other thing where we are going to put the SAP Brand color?
https://www.sapbrandtools.com/color-palette/#palette-details

**Comment by LeoT7508** [comment]
@joseegm 

One thing to remember here is this palette will grow as we need more colors, this is not the final version of this document, its just the starting point. 

Top and side navigation are included in this already. "Brand" is the global navigation bar color, and "accent 1" is the side navigation color.

**Comment by joseegm** [comment]
@LeoT7508 
This task is to decide on a final solution we want to adopt, so basically the outcome of this discussion is **to select** an approach that can scale.

So, we have "groups" of colors, like this:
```
COLORNAME
COLORNAME - shade 1
COLORNAME - shade 2
```
 for example on the current pallete
```
ACTION
ACTION - shade 1
ACTION - shade 2
```

If I got that correctly, then, if we need another color for the **action** group, the new color will be called: "action shade 3". Since we already have "action", "action shade 1", "action shade 2".

**Is that correct?**

Now, **Accents**
In the color context the definition of [accent](https://www.google.de/search?q=define%3Aaccent&oq=define%3Aaccent&aqs=chrome..69i57j69i58.2238j0j1&sourceid=chrome&ie=UTF-8) is to **emphasise**.

The present case is used like a "shade" of the **brand** color.

**Should we rather have?**
```
BRAND 
BRAND - shade 1
BRAND - shade 2
```

Because the objective of emphasising elements is been done now by the **Action** color group. As I see it.

Then we don't need an **accent** color name.

**That makes sense?**

**Comment by LeoT7508** [comment]
@joseegm 

Groups of colors is the idea. 

The colors will continue to be grouped as we add yes and shades will be added as necessary. 

Accents - This is not correct. Shades are only added as a shade of a color, not a completely different color. 
These colors are going to fall under Primary colors and have unique names since they are for primary components. They can have shades, but they will not all be "brand" colors. 

Accents and Actions can be 2 different things. It really just comes down to what terminology Zack and I feel work best, we don't have to overthink it too much.

**Comment by joseegm** [comment]
@LeoT7508 
Yes I'm trying to understand the terminology. This task is for that. So let's come up with the group names and what they are used for.

**Comment by LeoT7508** [comment]
@joseegm 

Ok, well for now this is what we are using. It will continue to evolve. For now we can go with what we have. 

The over all idea is:

Color Group

     - Color 1
          - Color 1 Shade 1
          - Color 1 Shade 2

     - Color 2
          - Color 2 Shade 1
          - Color 2 Shade 2

Color Group

     - Color 1
         
     - Color 2
          - Color 2 Shade 1
          - Color 2 Shade 2
          - Color 2 Shade 3

     - Color 3

     - Color 4
          - Color 4 Shade 1


As per the pattern shown here, it can vary depending on how the color palette has grown. And of course colors can continue to be added.

**Comment by xak** [comment]
@joseegm See page 14-18 for the application of the colors. That may help.
https://hybris.box.com/s/6xl2gbv6f4g34o7zg9aokfzml5a4ml66

**Comment by joseegm** [comment]
@LeoT7508 @xak 
That pattern can work, we have to test it.

I'll resume it here in the following table and document it on the wiki.

| Color group | Color Name | Color Shade | Color HEX | |
|---|---|---|---|---|
| Primary | Brand | Shade 1 | #006FBB | <img src=http://www.colorhexa.com/006fbb.png width=200px height=50> |
| | Acent | Shade 1 | #27394F | <img src=http://www.colorhexa.com/27394f.png width=200px height=50> |
| | Action | Shade 1 | #009CDF | <img src=http://www.colorhexa.com/009cdf.png width=200px height=50> |
| | | Shade 2 | #00A5EC | <img src=http://www.colorhexa.com/00a5ec.png width=200px height=50> |
| | | Shade 3 | #0093D1 | <img src=http://www.colorhexa.com/0093d1.png width=200px height=50> |
||||
| Text | Dark | Shade 1 | #21262C | <img src=http://www.colorhexa.com/21262c.png width=200px height=50> |
| | | Shade 2 | #7F90A4 | <img src=http://www.colorhexa.com/7f90a4.png width=200px height=50> |
| | | Shade 3 | #63758B | <img src=http://www.colorhexa.com/63758b.png width=200px height=50> |
| | Inverse | Shade 1 | #FFFFFF | <img src=http://www.colorhexa.com/ffffff.png width=200px height=50> |
| | | Shade 2 | #F6F8F9 | <img src=http://www.colorhexa.com/f6f8f9.png width=200px height=50> |
| | | Shade 3 | #EEF1F3 | <img src=http://www.colorhexa.com/eef1f3.png width=200px height=50> |
| | | | | |
| Neutral | Neutral | Shade 1 | #F9FBFC | <img src=http://www.colorhexa.com/f9fbfc.png width=200px height=50> |
| | | Shade 2 | #D7D7D7 | <img src=http://www.colorhexa.com/d7d7d7.png width=200px height=50> |
| | | Shade 3 | #CCDAEB | <img src=http://www.colorhexa.com/ccdaeb.png width=200px height=50> |
||||||
| Status | Success | Shade 1 | #61BF33 | <img src=http://www.colorhexa.com/61bf33.png width=200px height=50> |
| | Warning | Shade 1 | #E96B1A | <img src=http://www.colorhexa.com/e96b1a.png width=200px height=50> |
| | Error | Shade 1 | #DF1919 | <img src=http://www.colorhexa.com/df1919.png width=200px height=50> |

**Comment by joseegm** [comment]
This has been documented now on
https://github.com/SAP/techne/wiki/Colors

putting this to review

**Comment by joseegm** [comment]
This changed again, been clarified on #765
