### ISSUE TITLE
Visual Design for the Cards Actions

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#769]
### Goal
Style the Card actions

**UX Elements** Defined and described at #768

Tasks
- [ ] Update Wiki
- [ ] Update PSD file on box

**Comment by LeoT7508** [comment]
@joseegm 

I have to some other tasks I need to complete today and maybe tomorrow before I can start on this. I will get to it as soon as possible. 

Thanks.

**Comment by joseegm** [comment]
@LeoT7508 
Great! 
Please check #768 and let me know if all elements are clear or you need some more information about that.

Thanks

**Comment by joseegm** [comment]
@LeoT7508 
Did you got to work on this?

**Comment by joseegm** [comment]
@LeoT7508 
Are you working on this one?

**Comment by joseegm** [comment]
Closing this since Visuals are happening at #768
