### ISSUE TITLE
Pkg: Build individual components

### ISSUE THREAD

**Issue by xak** [SAP/techne#771]
# Output
Standalone component CSS
- Build each SCSS file in `src/styles/components` into `dist/components`

**Comment by joseegm** [comment]
Do we have a PR for this?

**Comment by xak** [comment]
#773

**Comment by joseegm** [comment]
### Review results

Component reviewed: https://github.com/SAP/techne/blob/7f5cb2db72aabf3a9d33c5d59e6a91b82f6a021b/dist/css/components/techne-card.css
and documentation at
http://sap.github.io/techne/www/components/cards.html - stand of 7, July 2017 12:00 UTC+1

Based on the [2nd Technical goal](https://github.com/SAP/techne/wiki/Techne-2.0-Goals): **Provide out-of-the box interoperability with Angular and React**.

1. **State classes cannot be isolated**.

    When managing an component **state** in Angular, is common practice to use the `ng-class`directive to map status variables to css classes, as follows:

  
    ```html
    <div class="tn-card" 
            ng-class="{ 'tn-card-readonly': !card.link, 'is-disabled': card.disabled }" />
    ```

    for this to work in the current implementation, it has to be rewritten as
    ```html
    <div 
            ng-class="{ 'tn-card': !card.link:, 'is-disabled': card.disabled , 
                        'tn-card-button': card.link }" />
    ```

   **NOTE: To match the current classes implementation extra work on the implementation side is needed.**

    **That extra condition on angular 1.5.x with 2 ways binding is going to be evaluated on every digest cycle.**

    **Decreasing the performance of the controller**


    Same problem with react, please see `className` [example](https://stackoverflow.com/questions/34521797/how-to-add-multiple-classes-to-a-reactjscomponent/34521945#34521945): 

    ```js
    var cardClasses = classNames({
          'tn-card': true,
          'tn-card--readonly': !self.link,
          'is-disabled': self.disabled
     });
    return (<div className={cardClasses} />);
    ```

     To mach the current implementation
     ```js
    var cardClasses = classNames({
          'tn-card': !self.link,
          'tn-card--button': self.link,
          'is-disabled': self.disabled
     });
    return (<div className={cardClasses} />);
    ```
    **NOTE: this will create an additional mutable property.**

    **Real live example from Builder public website**

     ```js
     <div class="cardRow" 
          ng-class="{'cardRowClickable' : clickable && !entry.entryClickDisabled && !entry.entryDisabled, 'cardRowDisabled' : entry.entryDisabled}" >
      ```

      **IMPORTANT: majority of the teams are used to follow this methods and the current code base is built as this.**

      **This is bring a lot of friction, that will hinder the adoption.**

> More elements coming.

**Comment by xak** [comment]
@joseegm With the merging of #784 this is no longer relevant. I removed the convenience factor of a single class which does create problems as you describe. 

http://sap.github.io/techne/www/components/cards.html

Your initial example holds up now as the implementation would be like this ...
```
<div class="tn-card"
	ng-class="{ 'is-disabled': card.disabled , 
                'tn-card--button': card.link }" />
```

With the new version, we should encourage the use of ngAria in favor of state classes so the Builder example could be ...

```
<div class="tn-card" 
     ng-class="{ 'tn-card--button' : clickable && !entry.entryClickDisabled }"
     ng-disabled="{ entry.entryDisabled }">
```

The disabled attribute will hold even when the card is a button so the extra expression at the end  — `'cardRowClickable' : clickable && !entry.entryClickDisabled && !entry.entryDisabled` — for the disabled state in ngClass shouldn't be necessary. The `is-disabled` class will continue to work however — http://sap.github.io/techne/www/components/cards.html#disabled

The convenience of a single class was more of test and it obviously creates more problems than it solves so it was dropped.

Thanks for this info. Let me know if you see any other issues.

**Comment by joseegm** [comment]
I think this can be closed now.
Next time please reference this issue also from the PR for easy linking. Thanks.
