### ISSUE TITLE
Release cards CSS as v2.0-alpha-1

### ISSUE THREAD

**Issue by xak** [SAP/techne#775]
The components CSS is building with #773 so we want to do a pre-release of the v2.0 package.

https://help.github.com/articles/creating-releases/

**Comment by xak** [comment]
Looking at #754 to fix a few small issues now.

**Comment by saadmhybris** [comment]
Let me know when the v2.0 branch is ready for alpha relase and I will start preparing a release branch.

**Comment by xak** [comment]
@saadmhybris I opened PR #776 for the card updates. If that is good, the cards can be released. Those basic card types should be enough to test.

**Comment by joseegm** [comment]
Why this issue have no assignee? Who is in charge of this one?

Before releasing we need to finish these reviews
https://github.com/SAP/techne/issues/778
https://github.com/SAP/techne/issues/777
https://github.com/SAP/techne/issues/754
