### ISSUE TITLE
Docs: Review of Components page

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#777]
Goal: match the current Website Component Page implementation to the design.

Current implementation - stand https://github.com/SAP/techne/commit/9c8adda0c9e56d79c7115b118a5f908bc91065c9

Design wireframes: https://github.com/SAP/techne/issues/694#issuecomment-304610787 
Website components visuals: https://github.com/SAP/techne/issues/694#issuecomment-307823292 

### Problems
- [ ] Code syntax highlighting is missing
- [ ] Tabs for **sample** and **code** by component is missing
- [ ] **Structure** information is missing documentation. What it is?
- [ ] Documentation copy text have not prominent place, please update as per the wireframes
- [ ] Confusing headers
![screen shot 2017-06-30 at 11 08 14](https://user-images.githubusercontent.com/22662903/27729069-a4ef5d8e-5d84-11e7-9b3d-01bc32418b75.png)
  Add the accessibility to the main documentation

**Comment by saadmhybris** [comment]
Closing this is as it is no longer valid.
