### ISSUE TITLE
Define Icon usage

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#804]
goal: specify the sizing and usage of the icons

### Tasks
- [x] Define main icon sizes, proportions and spacing
- [x] Document results: https://github.com/SAP/techne/wiki/Icons

**Comment by joseegm** [comment]
### Usage

The icons included in the Techne library are the ones used by the components themselves. There is no general purpose icons to use expect a few exceptions

### Icon template

To keep all the style an proportions of the icons consitent, the use of the following template is recommended.

![image](https://user-images.githubusercontent.com/22662903/28365330-798ebff0-6c88-11e7-8d10-4a347a2b0621.png)

The template have a set of guides to keep the size in the icon themselves and the proportions standard.

The guides can be used depending on the different shape of the icon.


![image](https://user-images.githubusercontent.com/22662903/28365324-6b6e5886-6c88-11e7-9126-25f827c42ae6.png)

**Comment by joseegm** [comment]
### Sizes

The icons are developed in a 500x500px resolution. And Exported as SVG vector format, to be combined in a icon font.

Icons are displayed on the UI with sizes corresponding to the Spacing, starting with 16x16px. Using that system we end with a system like this

![image](https://user-images.githubusercontent.com/22662903/28365750-0f7401b4-6c8a-11e7-9a12-3b52385dc75c.png)

**Comment by joseegm** [comment]
@LeoT7508 
Please take a look if the above is aligned with the icon system you have.
Thanks.

**Comment by LeoT7508** [comment]
@joseegm 

We can keep this for now, but lets mark it as open and in progress since it might change depending on what happens when we work on it in more detail.

**Comment by LeoT7508** [comment]
@joseegm 

I was actually just looking at Icons and how this system will impact fields, it could be an issue with spacing in fields. Ill see which option is the best way to go. Even more reason to keep this issue as "In Progress"

**Comment by joseegm** [comment]
@LeoT7508 
This issue is in progress. 

But I think we have enough elements now to define the way the icon design should work and also the usage inside the actions -that's the component with more use of it. 

So we can make some decisions and finish this tasks. If we keep things open all the time we don't finish any of them. The good thing, we can always revisit stuff afterwards if we encounter some discordance. Don't you think?

In this issue is important to keep a balance and the right proportions for the different types of shapes, here for context

![image](https://user-images.githubusercontent.com/22662903/28455161-56978550-6dfe-11e7-974b-707ddbda63b7.png)

Also the proportions in relation to the outer guide, on the last version that was a really big problem that we need to solve with 2.0.

A couple questions so we can advance on this:
1. Do you think the main shapes are useful?
2. Can we agree that all the icons are drawn using the template on  https://github.com/SAP/techne/issues/804#issuecomment-316360002? 
3. Can we define standard sizes like the ones on https://github.com/SAP/techne/issues/804#issuecomment-316362504? 

Thanks

**Comment by LeoT7508** [comment]
@joseegm 

This sizing system won't work. We probably will have to go with 18px, 26px, and 32 or 34. I gotta see how it works out. Thats why I suggest we keep it open. Since we are still working through it.

**Comment by joseegm** [comment]
@LeoT7508 

Let's complete this tasks. 

The sizes should be corresponding with the 4px dimensions system.
You suggested: **18px, 26px, and 32 or 34**

What we need next, is: **a set of sizes that would work with all the other elements**. Inputs, Actions, etc.

**Comment by LeoT7508** [comment]
@joseegm 

Moving forward we will be using 18, 26, 32px sizes for icons. 

Attached are examples:

![techne_2 0_icons_master](https://user-images.githubusercontent.com/28761982/28642822-4af2a53a-7219-11e7-834e-93c2193ea171.png)


Small and medium are represented here: Small is the "!" icon. 

Medium is the radio button. 

![screen shot 2017-07-26 at 3 41 14 pm](https://user-images.githubusercontent.com/28761982/28642780-2d9a19b4-7219-11e7-8788-4cd3be9ce242.png)

Large icons are used in fields. 

![screen shot 2017-07-26 at 3 41 48 pm](https://user-images.githubusercontent.com/28761982/28642847-571c6d96-7219-11e7-9b07-85a959f6e469.png)

**Comment by joseegm** [comment]
Results documented on 
https://github.com/SAP/techne/wiki/Icons
