### ISSUE TITLE
Design Form Select

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#805]
goal: Design the Form Select to match the new inputs at #737 

### Current v1.5.x
<img width="663" alt="screen shot 2017-07-13 at 12 19 46" src="https://user-images.githubusercontent.com/22662903/28161987-dec8d4ea-67c5-11e7-91a4-36eae095a830.png">

### Tasks
- [ ] Define UX elements and behavior
- [ ] Visual Design
- [ ] Document results in the wiki

**Comment by xak** [comment]
See https://select2.github.io/examples.html

**Comment by joseegm** [comment]
@xak 
With this one we only are designing the normal Dropdown. 

From the page you sent, the first example. The others examples on that page are more complex components with search, etc.

Once we finished this one we can create a variant or a new component with those features.

**Comment by xak** [comment]
@joseegm Please note that the example is not a normal dropdown. It's a custom Select2 implementation. The styling will require pulling in vendor CSS so it may be more effective to handle all dropdown cases as once.

There is no way to style the dropdown part in CSS so is the outcome here to style only the `select` element with up/down arrows? Does this also apply to `ul` list menus used for navigation? "Dropdown" is a little bit misleading.

Be clear in the final documentation if all `select` elements get transformed to Select2 boxes or can a project use default `select`s without the styling for the `option`s. There are JS implications here that need to be considered by development esp. whether the custom styling is global or opt-in.

Thanks.

**Comment by joseegm** [comment]
The decision of using or not Select2 is a development decision. We had massive problems maintaining Select2 in v1.5.x so I'll like to avoid it.

There is no new design yet. 
1. What you mean with "up/down" arrows?
2. What other `ul` list for navigation you are referring?
3. What you mean by "custom styling is global or opt-in"?

Changing Dropdown to `Form Select`to be more clear

This is referring to the default select via css; and custom HTML markup component if more features are needed. We are not going to depend on Select2 for style.

**Comment by xak** [comment]
_Tagging @saadmhybris for reference._ 

I agree about Select2, but it will not be possible to support the various `select` controls in use now without Select2, Selectize.js or other solution. **CSS alone simply cannot do it.** 

The best CSS can do is this ...
<img width="440" alt="screen shot 2017-07-27 at 4 19 01 pm" src="https://user-images.githubusercontent.com/424119/28692736-7888570a-72e7-11e7-98aa-e3bcd8244c0c.png">

The `option`s have limited styling capabilities (that vary across browsers) so you get the good ol' system dropdown ...
<img width="451" alt="screen shot 2017-07-27 at 4 19 28 pm" src="https://user-images.githubusercontent.com/424119/28692762-968fc3c8-72e7-11e7-87d5-73c1c2b984cf.png">
 
So for the default select, we can only style the `select` element to look like an input with the addition of the "open/close" indicator on the right (what I meant by up/down arrows). The `form-group` lock up with a label, help and errors should be the same as inputs. 

To your other questions ...
_What you mean by "custom styling is global or opt-in"?_
Should end implementors have the choice of using the browser default select (see image 1 above) or will **ALL** `select` elements get transformed into the Select2 look. I assume the latter will be the case, where the init is `$('select').select2();`. I'd like to understand the exact pain points around Select2. Has global transformation been a problem or is it more about integration challenges?

_What other ul list for navigation you are referring?_
A navigation `ul` menu is used for links and is not part of a form. Select2 transforms the form element into a list and binds to the original form element. This isn't incredibly important right now but it's good to know when building so we can test against both elements just like a `tn-button` needs to be tested against `button` and `a` elements. The styling could be the exact same but one is a `select` and the other a `ul`. 

Hope that helps. If this is only about the default `select` that's cool, I just wanted to point out that there is a lot more going on behind this one element.

**Comment by joseegm** [comment]
I'm aware of the CSS styling limitations. That will be take in count when doing the design.

The details of the implementation that consumers of the library are doing is out of our scope, we only provide the corresponding CSS styles and HTML markup.

You can ping @saadmhybris about the problems we had with Select2 in the past.

The `ul` lists used for navigation have nothing to do with the select.

We will make the styles for the default component. If we find other use cases that need a different design then we will see how to implement them.

Thanks for your input.

**Comment by saadmhybris** [comment]
The problem we had with select2 in the past is when doing one off customizations. Both select2 and angular directive that builds that component was owned and managed by another team so the UI devs didn't have access to it. Also, select2 attaches to the body tag (at least the version at that point)  so it's not possible to customize individual instances. This was a big pain point as it was used all over the modules and there were UX asks to make modification on a one off basis.

**Comment by xak** [comment]
@saadmhybris Do we have a good understanding of the one-off customizations? That would be good for UX to know.

**Comment by saadmhybris** [comment]
The one-off customization had to do with just some basic style overrides. Like with our [expandable button pattern](https://techne.yaas.io/patterns/Expandable-Button.html), where builder teams were using select2 component instead of a dropdown list, we couldn't easily customize select2 dropdown to match the expandable button pattern.

**Comment by joseegm** [comment]
The case @saadmhybris mentioned is a valid one but it is out of the scope of this issue.

This issue is not concerned with the Select2 use. It is for the simple form select. Other custom cases will be defined, if needed.

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_form select](https://user-images.githubusercontent.com/28761982/29468930-d69e482e-840b-11e7-89be-53ef5073c080.png)

**Comment by xak** [comment]
@LeoT7508 This looks good but one thing ... would it be a big deal to make the indicator — `V` — a 90° angle or use a Unicode character? That way I don't have to use an icon. 

The checkbox worked well since the make uses a 90° angle meaning I could make a box with borders on two sides and rotate it to look like a checkmark. https://github.com/SAP/techne/pull/876/files#diff-9b2d847fc5562e255de1ce5050bf5c6bR113

<img width="237" alt="screen shot 2017-08-21 at 10 34 06 am" src="https://user-images.githubusercontent.com/424119/29526755-4a35834a-865c-11e7-9f6a-541f35c68578.png">

It would be great to do that here as well if it works for you.

**Comment by LeoT7508** [comment]
@xak 

Depends on the line weight. Do you have an example?

**Comment by xak** [comment]
We could use 2px weight ... here's what the checkbox looks like at 10x10 with 2px border width.

<img width="144" alt="screen shot 2017-08-21 at 10 42 31 am" src="https://user-images.githubusercontent.com/424119/29527136-8ce4c0f6-865d-11e7-855a-061f67973db6.png">

Minor tweak.

**Comment by LeoT7508** [comment]
Looks like 1px will be closer to what we have in the original. The check will look more like a check though correct? Not like a chevron?

**Comment by xak** [comment]
The checkbox will not change. I just used that as an example to show what the rotated chevron would look like.

**Comment by LeoT7508** [comment]
@xak 

Lets give it a shot and see how it looks.
