### ISSUE TITLE
Design Tree

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#808]
goal: design and improve the Tree component

### Current v1.5.x
<img width="988" alt="screen shot 2017-07-13 at 12 29 20" src="https://user-images.githubusercontent.com/22662903/28162409-2edb1992-67c7-11e7-8fb7-847813771b0f.png">

### Pain points
1. Too much similarity with the table with is confusing when you need to select which component to use.

### Tasks
- [ ] Define Use cases
- [ ] Define UX elements
- [x] Visual Design
- [ ] Document results

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_tree60pxrows](https://user-images.githubusercontent.com/28761982/29778531-50bb9dd4-8bd5-11e7-96ec-cde589eb6d3e.png)
