### ISSUE TITLE
Design Multi-tab Editor

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#811]
goal: design the multi-tab editor to match the new design

### Current v1.5.x
<img width="975" alt="screen shot 2017-07-13 at 12 43 19" src="https://user-images.githubusercontent.com/22662903/28162864-f84fb02a-67c8-11e7-9e2d-be0928e0aafa.png">

### Taks
- [ ] Port the uses cases from the current version, still relevant
- [ ] Define status, from the current version
- [ ] Document UX Elements
- [x] Visual design

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_multi-tab editor](https://user-images.githubusercontent.com/28761982/29935341-09991f50-8e44-11e7-82ad-16d129692172.png)

**Comment by xak** [comment]
@LeoT7508 Which elements here do not currently exist? Looks like the tabs/buttons are unique sizes with unique states, i.e., a red background for error. The "Select" dropdown has no border and has unique error states.

Please show all interactive states if they differ from the base component. For example, the tabs are like both primary and text buttons so should they pick up the hover behaviors? Default dropdowns have a dark blue background and inverse type color on hover, should that differ for the errored "!GR" example above? 

Lastly, make sure every use case is represented here from https://techne.yaas.io/patterns/Multi-Tab-Editor.html. For example, each tabs has two error states — 
1. `.is-invalid` where the tab is not selected but has an error (red text)
2. `.is-invalid.is-selected` where the tab is selected and has an error (red background)

Should the "More/Select" dropdown be the same, red filled in background even if there is no border? There is also a static view which I'm guessing would use the "readonly" inout with the single rule line at the bottom.

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_multi-tab editor](https://user-images.githubusercontent.com/28761982/30549330-19481356-9c5a-11e7-8c12-2f039e9f0f6b.png)

**Comment by joseegm** [comment]
@LeoT7508 
Can you please upload these ones to Zeplin?

**Comment by LeoT7508** [comment]
@joseegm 

These have been up on Zeplin for some time now, under the Forms section.

**Comment by joseegm** [comment]
Ahh, very good.
