### ISSUE TITLE
Design Tooltips

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#812]
goal: design tool tips

### Current v1.5.x
<img width="227" alt="screen shot 2017-07-13 at 12 47 33" src="https://user-images.githubusercontent.com/22662903/28162979-8033f834-67c9-11e7-9bdb-f7e1caea3b50.png">
<img width="309" alt="screen shot 2017-07-13 at 12 47 48" src="https://user-images.githubusercontent.com/22662903/28162980-804d31d2-67c9-11e7-8c53-4cc82c4790f0.png">

### Related on v2.0
Inputs help tooltips where already designed and documented at https://github.com/SAP/techne/wiki/Form-Inputs#help-elements-738
This visual design will be keep
![image](https://user-images.githubusercontent.com/22662903/28163039-b76c3aaa-67c9-11e7-9014-3e188a53cc54.png)

### Pain points
1. Can only be displayed in one direction

### Tasks
- [x] Define Use case
- [x] Define UX Elements
- [x] Visual Design
- [x] Document results

**Comment by LeoT7508** [comment]
@xak 

The design for this is done along with Input Fields. 

Let me know if you need anything more before I close this issue.
