### ISSUE TITLE
Design Alerts

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#813]
goal: define better the uses cases and the visual design

### Current v1.5.x
<img width="983" alt="screen shot 2017-07-13 at 12 54 30" src="https://user-images.githubusercontent.com/22662903/28163208-7083fe6a-67ca-11e7-9251-a9916659c617.png">

### Tasks
- [x] Define Use cases
- [x] Define Ux Elements
- [x] Visual Design

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_messagingsystem](https://user-images.githubusercontent.com/28761982/29468823-6bb92e66-840b-11e7-9b85-753cca8feacf.png)

**Comment by xak** [comment]
@LeoT7508 The orange seems dark enough to use white text. Can we be consistent with all of them?

**Comment by LeoT7508** [comment]
@xak 

White on that orange doesn't meet accessible color standards.

**Comment by joseegm** [comment]
documented on
https://github.com/SAP/techne/wiki/Alerts
