### ISSUE TITLE
Linking bootrap from website

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#815]
Techne website is linking bootstrap and with the wrong path
http://sap.github.io/techne/www/components/cards.html

### Error
<img width="1059" alt="screen shot 2017-07-13 at 13 14 23" src="https://user-images.githubusercontent.com/22662903/28163933-55f20f1c-67cd-11e7-8622-762a38fa84f6.png">

**Comment by saadmhybris** [comment]
This is my doing... i'll fix it.

**Comment by saadmhybris** [comment]
PR created here - https://github.com/SAP/techne/pull/817
