### ISSUE TITLE
Spike: Investigate using CSS variables

### ISSUE THREAD

**Issue by xak** [SAP/techne#818]
Since we're still early in the architecture, curious about migrating to/using CSS variables.
http://caniuse.com/#feat=css-variables

## Questions
- Is this a non-starter based on Edge support?
- How would CSS vars work with/compete with SASS vars?
- Do we gain any efficiencies with CSS vars over SASS vars?
- Does it help or hurt theming potential?

**Comment by saadmhybris** [comment]
1. Sooner or later there will be edge support. it's shocking that it's not supported at this point. I thought Microsoft was cool again?  
2. The only benefit I see to using CSS vars as opposed to SASS vars if we were to completely remove SASS from the equation and code directly in CSS, which is not likely given our needs to modulization and segmentation of styles.
3. Probably same on some processing time, but it's negligible at this point. The syntax --var-name can get mixed up with BEM naming convention and cause confusion for devs who are not aware of CSS vars. 
4. We still need to declare and define all the themeable properties of a component. Switching themes may be faster as processing happens in the browser and JS manipulation for vars could also come in handy. 

I feel it's still a bit too early and SASS is still a better choice with mixins, nesting, native functions, etc.

**Comment by joseegm** [comment]
Agree with the points from @saadmhybris. Not at this point.

But it will make theming really easy for consumers of the library.

CSS variables use also the cascade.
