### ISSUE TITLE
Re-architect the Components Page and Improve the Component Development workflow

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#822]
@xak 
This one is very important.

### Goal
**Find a better architecture for the Website Components page and Improve Component development experience**

Looking at
https://github.com/SAP/techne/blob/v2.0/docs/styleguide/components/cards.html

The current implementation of v2.0 website. The documentation copy text is **"hardcoded" together with the markup used to generate the page. **

This spaghetti code -see extract bellow- make difficult to work in the documentation copy text, since it is mixed with the markup for the layout of the website.

```html
<div class="docs-section">
    <div class="docs-flow">
        <div class="docs-flow__box--12-5">
            <h3 id="disabled" class="docs-header--h3">Disabled card<br> .tn-{{ key }}[aria-disabled="true"] or .tn-{{ key }}.is-disabled <a href="#disabled">#</a></h3>
        </div>
        <div class="docs-flow__box--12-7">
            <p>State: Disabled, this class/attribute can be toggled with JS </p>
            {% set example %}
                {{ card(
                        button=true,
                        title='Repellendus obcaecati molestias',
                        description='Lorem ipsum dolor sit amet, consectetur adipisicing elit aute irure dolor in reprehenderit in voluptate',
                        status='<span>Voluptate quis adipisci sit</span> | <span>Voluptate quis adipisci sit</span>',
                        disabled=true
                    ) }}
            {% endset %}
            <p>
                {{ example }}
            </p>
            <p>A11Y NOTE:
                Use 'aria-disabled' when the control is interactive yet it is not currently available. The class 'is-disabled` is more approriate when the state is presentational and interactivity is not necessarily expected.
            </p>
        </div>
    </div>
    <p> {{ format.example(example) }} </p>
</div>
```

### Thats a step backwards from how we have it on the old v1.5.x

The documentation on v1.5.x was along with the example markup, together with the LESS code. See
https://github.com/SAP/techne/blob/develop/src/less/techne-patterns/_data-card.less

```less
// Grouped Cards with Section Headlines
//
// In some cases it is useful to group data cards on a single page with clear section/sub-section headings. Also it may be useful to nest such groups and allow the display to scale gracefully. In these cases please use this modifier to the data card component.
//
// Markup:
// <div class="dataCards dataCards-grouped dataCards-singleColumn">
//  <div class="dataCard-heading">
//    <div class="cardRow">
//      <h3>Section Headline</h3>
//     </div>
//  ...
//  Note: Rest of the code removed for clarity of the illustration
//
// Pattern 4.3

.dataCards {
    display: flex;
    align-items: stretch;
    flex-wrap: wrap;
    flex: 0 1 auto;
    /* ...
        Note: Rest of the code removed for clarity of the illustration */
```

### Pain Points
1. **The old v1.5.x had a simpler workflow**, for the 3 main workflows we have: changing the documentation, changing the html, changing the Less styling code. 

    Simply because it was **all in one single file in one single location** most of the time

2. To work in a single component on the current implementation the developer have to have open, at least, 3 different files on **3 different locations**

    - **The html file where the documentation resides**
      https://github.com/SAP/techne/blob/v2.0/docs/styleguide/components/cards.html

     - **Sub-template file that renders the actual HTML example code** 
     https://github.com/SAP/techne/blob/v2.0/src/templates/card.html

     - **The SCSS file where the**
     https://github.com/SAP/techne/blob/v2.0/src/styles/components/card.scss 

3. **The copy text is interlaced with the layout HTML markup.** Making difficult to make changes to only the documentation, without influencing the markup.

    This also makes difficult for other teams that only work on the documentation, like Team Q; review and make changes to the copy text only.

4. **There is no simple way to define an index or order for the whole Component page automatically**. That feature was present in the old v1.5.x. 

    On v1.5.x you could define the sections and the order of the sections by simply adding
    ```less
    // Pattern 4.3
    ````
    At the end of a documentation+markup block.      

    **To achieve the same outcome on the current implementation, the developer have to change the main layout markup of the page.** 

    **This is way more error prone than the old version v1.5.x**

5. **No Extensibility**. To add a common feature to the **Website Components page**, the developer **have to modify every single component .html file**.

    With a present list of [40+ components](https://github.com/SAP/techne/wiki/Techne-Components) and growing: **There will be a point when adding a new feature to the Components Page will become too difficult if the developer needs to modify 40+ HTML pages and on top of that an average of 5 sections inside**.
 
    **Resulting in the Component Pages feature stagnating, due to the difficulty and cost to introduce new features**

    **This is an architectural failure**, that leads to the next point

6. **No reusable code**. Having the documentation copy text intertwined with the page layout markup doesn't permit to reuse the code needed for the website component sections. **Not even on the same component page**

    Example of this problem:
    ```html
    <!-- base component example -->
    <div class="docs-section">
        <div class="docs-flow">
            <div class="docs-flow__box--12-5">
                <h3 id="base" class="docs-header--h3">Common card <br> .tn-{{ key }} <a href="#base">#</a></h3>
            </div>
            <div class="docs-flow__box--12-7">
                {% set example %}
                    {{ card(
                            title="Primary Value",
                            description="Secondary Value aute irure dolor in reprehenderit in voluptate",
                            status='Status'
                        ) }}
                {% endset %}
                <p>{{ example }}</p>
            </div>
        </div>
        <p> {{ format.example(example) }} </p>
    </div>

    <!-- static button -->
    <div class="docs-section">
        <div class="docs-flow">
            <div class="docs-flow__box--12-5">
                <h3 id="static" class="docs-header--h3">Button card<br> .tn-{{ key }}[role="button"] or .tn-{{ key }}--button <a href="#static">#</a></h3>
            </div>
            <div class="docs-flow__box--12-7">
                <p>Modified: Includes hover effect</p>
                {% set example %}
                    {{ card(
                            modifier="button",
                            button=true,
                            title="Lorem ipsum dolor quam placeat numquam repellendus",
                            description="Tenetur quam placeat obcaecati molestias voluptatibus dolorum ut.",
                            status='<span class="tn-has-color-status-success">Voluptate quis adipisci sit</span>'
                        ) }}
                {% endset %}
                <p>
                    {{ example }}
                </p>
            </div>
        </div>
        <p> {{ format.example(example) }} </p>
    </div>
    ```

    It is evident that `<!-- base component example -->` and `<!-- static button -->` sections have the same HTML Structure, **but it cannot be reused**.
    
10+ more pain points can be listed here: like not using a easy markup language like MarkDown among other things that will make our development easier... but these are the most important ones.

Please @xak @like-me1 @saadmhybris 
Take a deep look at the points mentioned and let's fix this, it is, **de facto, worst, than the older v1.5.x**

**Comment by xak** [comment]
# BLOCKED by #786

**Comment by joseegm** [comment]
@xak 
**How is this blocking #786?**

The structure part in only a smaller part of it

**Comment by xak** [comment]
@joseegm Just like individual components, you create a foundation and build on top of that. Improvements can be made to automate these pages, containers can be generated, content can be moved to separate files, common elements can be templated, etc. There is absolutely flexibility to do any of that. As we continue to establish the patterns of the component page, the logic of how modifiers are iterated and presented, the content of the headers, the descriptions, how we present a11y info, etc. we can being to optimize the presentation and make enhancements.

Unfortunately, this means we have to go back to some previous pages but that's the main side effect of building a house while your still designing it. As I've said before, it would be very useful to see a wireframe of the actual Cards page that reflects the actual content then we can implement a pattern that can be used on all pages. More importantly it would set the structure for subsequent pages.

What can I provide to facilitate this? I asked for this at least a month ago.

**Comment by joseegm** [comment]
The component page was finishes months ago, and it is extensible in the design to acommodate new features.

**Wireframes of the actual Component page with the cards**: on https://github.com/SAP/techne/issues/694#issuecomment-304610787
Finished on **MAY 29, 2017**

![image](https://user-images.githubusercontent.com/22662903/28218375-a51125ec-68b8-11e7-944a-b71279013d03.png)

@xak
Can you please address and find solutions to the **technical** problems on https://github.com/SAP/techne/issues/822#issue-243011146 Paint points

Those pain points have nothing to do with the design.

**Comment by joseegm** [comment]
@xak 
IMPORTANT: by the way #786 was created on July 7th, 2017. The wireframes are finished since **May 29th**

#786 cannot be a blocker of this issue. 
Seems the wrong concept of blocker is been used here.

**Comment by saadmhybris** [comment]
No longer valid.
