### ISSUE TITLE
Docs: Discuss Linking to external libs.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#825]
How should we link to external libraries and plugins like jQuery, Bootstrap(if needed) and any other plugins? 

Right now, we are linking to CDN files which make things easy, but you cannot completely work offline if needed. It has been an issue for me in the past from the development standpoint. If there is no wifi, the local environment does not render 100%. 

Option 2 is to pull down the NPM package. With this approach, we need to discuss how to link the file. Should we point to the node_modules folder from ./www or create a gulp task to copy over the needed files in ./www?

**Comment by joseegm** [comment]
The recommended approach will be using package managers. We only can use packages with approved licenses. For that we have a new tool that we have to implement. The tool check the respective packages config files, it won't check the linked CDN files.

The tool chain have to support using dependencies, I see it doesn't right now.

**Comment by saadmhybris** [comment]
I agree on using package manager (NPM in our case), we'll have to discuss how to include them in CSS/JS files.

**Comment by xak** [comment]
Definitely agree on using a package manager. The issue for me is whether there are any concerns managing library dependencies and website dependencies from the same packages.

**Comment by joseegm** [comment]
They are **dependencies**: those are for the library and **development dependencies**: those are used for the website.
