### ISSUE TITLE
How is the Spacing implemented in production?

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#827]
Goal: exemplify how the spacing feature can be implemented by using the Stand alone component CSS.

From 
https://github.com/SAP/techne/pull/821

The Spacing feature is already implemented but is it only for the use on SCSS, not for the use on plain CSS, which is the majority of the Use Cases that we have.

### Question
How a consumer of the library in CSS form will implement this feature on their UI?

**Comment by xak** [comment]
Good question!

The `compact` version of the library will be considered an advanced feature and will be adjustable when using the SASS — just as any other theming feature. Supplying multiple out-of-the-box spacing options, e.g.,  `tn-card--compact` and `tn-card--tight`, for every component will bloat the CSS for all users to cover edge cases for a small number of users.

**The question is should teams be able to use a mix of regular and compact components to suit their needs or is it a feature to be enabled globally?** I don't have enough information or examples of compact UIs to know for sure. My feeling is that the drop-in Techne theme should have assumptions built-in and we shouldn't encourage mixing and matching. We are providing lots of ways for teams with advanced theming needs to adjust components to meet their needs, SASS feature flags, exposing component local variables, reduced CSS specificity.

Sp far we only have one team that has requested this feature. Let's check with them to better understand their needs, global vs. fine-tuned. We no doubt need an "Advanced" page on the website to explain the SASS powerful customization features available when using the source.

**Comment by joseegm** [comment]
Is not only one team, but a set of products, the EC products.

Don't consider it and "advanced" feature. There is no advanced features, there are features, that's all.

All components have to be implemented to adapt to a spacing class that can be present in a higher element in the DOM tree. The spacing options can be set at any level on the component hierarchy and the components bellow that will use the compact space.

The solution was first described at the request https://github.com/SAP/techne/issues/748
Was also designed at https://github.com/SAP/techne/issues/763, https://github.com/SAP/techne/issues/751

That will answer your question.

Example:
```html
<div class="tn-compact"> <!-- Spacing class set -->
    <div class="tn-cards"> <!-- Component adapt the spacing -->
        <div class="tn-card"> <!-- Component adapt the spacing --> 
            <!-- . . . -->
        </div>
    </div>
</div>
```

That's is already implemented on
https://techne-alpha.firebaseapp.com/components/structure/spacing
