### ISSUE TITLE
Documentation focus should be on CSS use

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#828]
goal: clarify the type of consumer use case that we are addressing.

### Current situation
Most of projects and teams using the library are consuming only the CSS files. That pattern will continue to be the same.

### Problem
The documentation now is centered in documenting the SCSS mixings, variables, etc.

**That's not how the library is consumed now and not how it will be consumed in the future**. We have to change the focus of the documentation to address the normal consumer use case of the library, using the CSS files.

**Comment by joseegm** [comment]
@xak @saadmhybris 
Any ideas or comments on this issue?

**Comment by xak** [comment]
We decided that the component structure will be something like this for each component and variants ...

```
section
  title
  version-number (at some point)
  class-name (the note that now appears above the code block)
  description
  note (optional, mostly about a11y)
  example
  code
```

I'm looking at other options to document the SASS, maybe SASSDoc or even just an Advanced page on the site.

**Comment by joseegm** [comment]
@xak 
**That was not the issue here.** 

Again the goal of the issue for context:
**goal: clarify the type of consumer use case that we are addressing.**

I'm asking about the focus on SCSS on the documentation. Here is an example
<img width="996" alt="screen shot 2017-07-21 at 19 03 24" src="https://user-images.githubusercontent.com/22662903/28474056-5677b614-6e47-11e7-91d7-028b67751260.png">

The focus will be in using the library via CSS not SCSS. 

**CSS is the main use case we have now and it is the focus**

**Comment by xak** [comment]
@joseegm I'm simply noting all the relevant information about the type. It was not my intention that this be the final page. **I would like to expose information about the SASS in some way, however, ** even if it's a link to a different page or SASSDocs. It is part of the Tech goals to provide a toolkit to enable development so it's important to expose the advanced usage even if it's not the primary use case. 

The [current Techne page](https://techne.yaas.io/Guidelines.html#guidelines-visual-system) does **not** do a good job of explaining the design system or technical usage for type (in fact, many components use sizes that are not shown included in the specs).

I'll leave it to UX to consolidate the different needs and information and recommend an approach to satisfy them all and improve the documentation.  Let me know if you need clarification on the design system and how sizes are being used.

**Comment by joseegm** [comment]
@xak 

You are mixing things, I'm noting the emphasis on the SCSS use on the present documentation. The library is mostly consumed in CSS, so that will be the focus of the documentation.

The SCSS information can be exposed but it should be secondary.

**Comment by xak** [comment]
It makes most sense to me to implement separate documentation for the SASS library. That can be done on a separate track.

**Comment by saadmhybris** [comment]
Closing this as we have solved this issue or reached an agreement :)
