### ISSUE TITLE
Pkg: Add compact card

### ISSUE THREAD

**Issue by xak** [SAP/techne#837]
Create a new modification of the cards to reduce the padding by 1/2.

`.tn-card--compact`

**Comment by xak** [comment]
A new section has been added to the bottom of the Cards page which show 3 examples of the `--compact` modification.

**Comment by joseegm** [comment]
The spacing feature is not correctly implemented. 
Please refer to the explanation at: 
https://github.com/SAP/techne/issues/816#issuecomment-317336702

The "compact" can be set from any place in the component hierarchy. Not mainly on individual components.

**Comment by xak** [comment]
Parent modifiers are not an ideal solution. It is preferred to put the modification on the actual element being modified to avoid additional presentation containers and it reduces specificity when overriding styles.

The implementation as designed is good for an MVP. We can gather feedback during alpha and beta releases to better holistically assess the impact or each option.
