### ISSUE TITLE
Must-haves for project framework

### ISSUE THREAD

**Issue by xak** [SAP/techne#839]
TBD for @xak

**Comment by xak** [comment]
See https://github.com/SAP/techne/wiki/2.0-Requirements for first draft.

**Comment by joseegm** [comment]
Thanks for putting this together. 
Majority of this was agreed already. 

Some of this is not clear: Remember it should have a goal. The goal is expected to be in this issue.

**What is the goal of this document**? 
**What's the value to the project?** 

Once those first questions are answered these points need to be revisit.

#### Project

- The npm package will distribute the dist, scss, and test directories.

    **The /test doesn't need to be packaged, this is for internal use only. Integrated with the CI system**

#### Package

- Components must be conceived of and built with a data-driven mentality.

    **QUESTION**: How is the teams using Angular -most of them- can benefit from this? Concretely.

- The SASS source will be a robust toolkit for developers

    **QUESTION**: How exactly this will work?

- All components must use a BEM class notation.

    **What's the migration impact?** All the teams now are using the bootstrap class hierarchy now.

#### Website

- Website should use the library from the source

    1. The website should take advantage of the toolkit features in the library.
    2. Library settings and components should be augmented with documentation specific features.
    3. Production website builds should use the distributed library package, not the project source, to enforce the separation.

    ** The point 3 contradict the main point**

**Comment by xak** [comment]
**The npm package will distribute the dist, scss, and test directories.**
It's not uncommon to package tests with a library but, no, it's not 100% necessary initially.

**Components must be conceived of and built with a data-driven mentality.**
Component architectures are designed to work with structured data. It obvious that our components should expect a data structure with predictable rendering based on that data. If we are not sufficiently abstracting and optimizing our components we are creating overhead for end implementors. See example [card schema and JSON output](http://jeremydorn.com/json-editor/?schema=N4IgLglmA2CmIC5wDsC0BjAhgJwCYgBpwBPAB3iQHsAjAK1nTEJFO0vO0lgGdFQBbSrggAzCLGx8S5RCBzZMxZv0wAPAJJhY/XggBMRKNt2gwZCiG5hsEZAHNmsZAFd+iANohqzsGErJmADcJSCxoEABdAF8ooitMLSkzGSR5RWYjHSTzWSsbe0cXNwRPYW5Majh8IgALCFxcJ0iYokgYClMcpDzbByIRSmwVJiQtVSYiRpFMZ2gRkAAFGxVsYgACADVMaGd4WJBG7nQbUkh/bJTLa17mAaGE2TGJg9hp2fmAZQZ/XBx1rZ2eyI/FgwkwUlY7BC4hMIEEwjEEguFh6BSITlcHhAbGcyGqIDE0HC0SIpASNWRuWuaIJg2GsmcNhA+22YAAKrBxpTutS+rT7vMnsyWlcEs5YckUbzbnSHqNOUwWYwIP4JV0rvk+Xd6fKuSLsLAAI7OCAG/AlCKTV62KAq5Cw6C2ADW3JANHojGYkI4XAdFVg4QQnUuqK1ssFCuZREZgeDUs1MoFDKZMVTQAAA=&value=N4Igtg9gJglgZjApgJxALgNoF0A0IDOALgIaGLrZ6EyEA25aIACsjGMcgJ4AEAasbQCu5PFET4AxqwAO1CADt0IAMqIJCqBx78hI8IljF0oSLAQolyCIPlQQeaaQAWS+yAGEAKogAehVwC+eESkgviueMQScvLhjCABQAA==&theme=bootstrap2&iconlib=fontawesome4&object_layout=normal&show_errors=interaction). There are many advantages to this approach from testing, automation, and documentation.

**The SASS source will be a robust toolkit for developers**
The points listed start to explain but ultimately this is about providing all the building blocks necessary to implement OOTB components as well as add on custom components. With a design system built well a developer will **NEVER** hard code a font size, a font face, a color, or a dimension. Functions and mixins provide those values and **MUST** be used to support theming capabilities. Every minute a developer is measuring a margin or sampling a color is a minute not spent innovating or optimizing. See [Bourbon](http://bourbon.io) to understand the potential of a powerful SASS toolkit.

**All components must use a BEM class notation.**
The migration impact is no more than introducing a namespaced library. Every team will need to refactor every component to the 2.0 version, that's unavoidable in any circumstance. Any previous CSS will be irrelevant with the new class names so that will need to be refactored as well. There are advantages, however, once the migration is complete. There will be no need to match the specificity of the component selectors, it will be very clear in override stylesheets which component is being affected, modifications can be made with variable redefinition or new style declarations. This is a major update to the library, some migration overhead is to be expected, we want to minimize that but we also want to bring great value once teams are on the other side.

**Website should use the library from the source**
It seems to contradict but what I mean is that when the production website is deployed, part of the build process should be to pull the latest package from NPM and use that when building the website CSS. It's as if the website has no access to the library except through NPM instead of pulling it from a sibling directory. This is the best way to ensure that the website is using the correct version of the library since it's possible that the SCSS source could be ahead of the NPM package. When working locally, however, it's much easier to use the local SCSS source from the project itself instead of the NPM package.

**Comment by joseegm** [comment]
@xak 
I think they are not really all topics rightly explained, yet.
Period of 48 hours wasn't not observed either.

Some concrete answers are still needed. 
I will formulate them as questions, to facilitate the clarity of your answers1.

1. Do we have tests, currently, for the library components?
2. How a consumer of the library will use the tests, if we distribute them?
3. Data driven components means the components are designed to only accept data that fulfil the defined schema?
4. Can a consumer of the library reuse the schema or the template that generate the HTML snipped in angular, react or other frameworks?
5. The SASS toolkit is intended for our internal Techne Developers or the developers consuming the library?
7. How many teams that consume techne are using SASS?
6. Is most important for the library to reduce CSS specificity or to make the classes easy to use and logic?
7. Using the NPM package on the website means that we have to release the library to NPM first. Does that means that we cannot use the website for displaying the development of components?

**Comment by xak** [comment]
@joseegm This is a list to illustrate the requirements, an MVP will be determined based on many other factors. With that in mind ...

1. No, but we should. For launch, no, eventually, yes, I would like to.
2. It allows end implementors to run tests locally to ensure that our code is not breaking. This is not critical, some teams do, some teams don't. We don't have to distribute. It definitely makes more sense for JS libraries than CSS libraries. The WIKI was already updated to remove the `test` reference.
3. Yes. Of course, we **cannot**  and **will not** enforce character limits or custom content but when the entire team is involved in understanding the data structure and the schema up-front, the impact of changes and additions become more clear and become a shared responsibility. If a new modification or element is being added to a component, then UX, design and dev should be aware of how that modification gets applied and whether it requires changing the schema or data structure. When UX and design are **ONLY** thinking of presentation, it complicates the job of the developers downstream. 
4. Yes, that's [the point](https://sapse.invisionapp.com/share/6NCQ6SNJE#/245274252_UI). 
5. Yes.
6. Currently, only Back Office and Dev Portal, I believe, use SASS.
7. These are equally important. Every library decision must balanced these two concerns. BEM takes care if the first one, predictable structures, common vocabulary, and a good set of helper classes take care of the second one.
8. Yes. If a new version of the library is being released then the library goes first, the website second. If a typo is being fixed on the website, the library does not need to be released. Each can have their own release cycles. Now, if you want to display experimental, not-yet-released versions of components on the website which do not have CSS in the library, then that is a separate use case that can be solved independently.

**Comment by joseegm** [comment]
@xak 
Thanks for the answers, that more clear now.

To avoid confusion I will like to avoid introducing terms as MVP, we are aiming to the **Alpha release(s)** then comes the **Beta releases** Let's stick to that naming so we all know of what we are talking about.

We have not defined any MVP for Techne at any moment. **What's the MVP you mentioned?**

2. Consumers of the library run tests to see if **their code breaks**. They don't test our library itself. The library should be stable when released.
    So this is not needed to be distributed. Glad to see it removed.
3. Your answer raise more questions: just want to understand what you have in mind.
    1. Define 'entire team'. The techne team or the consumer teams?
    2. It is the schema necessary to use the library as a consumer?
    3. Who is in charge of defining the schema?
    4. At what point the schema is defined?
    5. How exactly the schema affects the design?
    6. Who modify the schema when a change is made on the design?
    7. Can we produce the HTML without the Schema?
    8. Assuming that to make any modifications to the component is necessary to modify the Schema, the SCSS the HTML and Documentation.
    How is that easier that only modifying the HTML, SCSS and Documentation?
    9. How high is the learning curve of such a schema?
    10. Is the schema defined using a standard Schema Language known by our developers?
    11. Not using a schema to produce the HTML will make the development of the components faster?
    13. How a UX or designer knows that his changes affect the schema or not?
    14. What happen if a change made in UX and Design affects the schema?
    15. What are the 3 major problems we will have if we don't use the schema to produce the HTML for the consumers of the library?
    16. What are the 3 major problems we will have if we don't use the schema to produce the HTML for the our developers?
4. Is not clear what that mockup does. That raise more questions and don't answer the original one.
    1. Will the consumer be able to get any value of the schema on their projects?
    2. Will the consumer  be able to reuse **the template that generate the HTML** from the schema on their projects?
    4. What the consumer will gain from using such an interface? The goal of it.
    3. Who define the schema generated on that mockup?
    > The mockup raise a lot more questions but these are enough for now. To see if is really needed now.
5. Yes for the internal developers or yes also for the consumer teams?
8. The answer raise more questions:
    1. That means that our release process gets more complex divided in two parts, one depending of the other?
    2. To develop a component you need the website to **see the changes your are developing**.
     If the website use only the released library.
     How do you develop the components outside of the website?

**Comment by joseegm** [comment]
@xak 
The answer to the above questions are needed to assess the value of the schema and to decide if we need it at all.

**Comment by xak** [comment]
A schema-driven library would provide a lot of benefits to the entire Techne team and end implementors. It is clear this will not be part of the MVP and that is fine. However, the dev team will continue to consider schema and data requirements when architecting components. 

The goal of this issue was to list the requirements for the technology and we will continue working toward that after the MVP. This does not affect the current path of work.
