### ISSUE TITLE
Revisit "Invalid" status on inputs, radio buttons and checkboxes

### ISSUE THREAD

**Issue by joseegm** [SAP/techne#841]
goal: find a better **visual solution** to display **Error messages**

### Problem

The error messages with a surrounding box looks visually good when they are displayed along a normal Input. But it looks unbalanced and inconsistent when it displayed with radio buttons or check buttons.

![screen shot 2017-07-25 at 12 42 15](https://user-images.githubusercontent.com/22662903/28568719-173fbeae-7137-11e7-9d2b-ab9732f58518.png)

**We need a better visual solution here for displaying error messages that doesn't look so unbalanced.**

Maybe remove the surrounding box. And putting the error message text in red.

**Comment by joseegm** [comment]
This  ticket will affect #802, #801 as well as the visuals already documented on https://github.com/SAP/techne/wiki/Form-Inputs

**Comment by xak** [comment]
Please note that it is a best practice to include an icon in addition to the color to better accommodate color-blind and low-vision users.

**Comment by joseegm** [comment]
Something like this, in front of the error messages.

![image](https://user-images.githubusercontent.com/22662903/28610392-79308d80-71e8-11e7-87ab-087a750bcaad.png)

**Comment by jeannewalters** [comment]
In Smart Edit and Personalization, we have a warning use case where the user is not blocked from moving forward but the entry is not correct. Are you covering that anywhere in Techne?

**Comment by joseegm** [comment]
Yes, you mentioned it when we were discussing the Status for the Inputs, but we decided that "invalid" and "valid" status was enough, for now.

**Comment by joseegm** [comment]
Add the "warning" state.

**Comment by LeoT7508** [comment]
@joseegm 

These examples are attached in the Radio Buttons & Check Boxes tickets.

**Comment by joseegm** [comment]
Yup.

Closing this as we already decided on the meeting. The warning state will be treated as a separate issue.
