### ISSUE TITLE
Ops: Deployment for dev, staging, prod

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#857]
Goal: Setup Deployment for dev, staging, prod environments.

Jekyll plays well with GitHub pages. However, we need multiple environments. Investigate who to make this happen.

**Comment by saadmhybris** [comment]
Opened a ticket with Wookies for this - https://jira.hybris.com/browse/WOO-9524

**Comment by derberg** [comment]
yo, on it

**Comment by derberg** [comment]
ok, looks like it works, I managed to achieve it only with travis reconfiguration, and we still use the previous code and approach we had for gh-pages branch publishing.
http://sap.github.io/techne/

Please confirm that this is what you wanted

**Comment by saadmhybris** [comment]
Sweet! it is working. We need to solve for how we reference techne.css in the documentation site. right now that css is not loading so the components don't render properly. 

questions - 
 - are we still using gulp to build the website 
 - the gh-pages branch, this is where the code is copied by Travis right? Should we not directly merge any changes to this branch? 
 - is the Travis plan triggered every time we do a merge in v2.0 branch?

**Comment by derberg** [comment]
* no, now jekyll must and is used, gulp only used to get generated stuff into the gh-pages branch
* so css is not part of the site and we still need to separately build those? I need to look into it
* yes, works like before, triggered on merge

**Comment by derberg** [comment]
I assumed this `gulp docs-build --production` must not be used any more
which tasks I would have to run to get missing csses ?

**Comment by saadmhybris** [comment]
docs-css.js copies the techne.css into './docs/_site/css' but then again the docs-styleguide.js is outdated and need to be updated. I can let me work on that should fix the missing techne css.

**Comment by derberg** [comment]
I understand you don't need me for now and will let me know once you need me?

**Comment by saadmhybris** [comment]
@derberg - thanks for your help. I have updated the gulp tasks and travis.yml as well go fix the CSS issues. it all seems to work as expected for now. 

cheers!
