### ISSUE TITLE
Docs: Port 1.5 components that don't require redesign

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#858]
Goal: Port 1.5 components that don't require redesign

Further discussion is needed as we have a dependency on bootstrap on most of the 1.5 components.

**Comment by xak** [comment]
A simple place to start may be to scaffold the pages on the site so we can establish the full nav, etc. even if the pages have no content. That will help us know what we are working towards at least.

**Comment by saadmhybris** [comment]
Closing this as we would need a separate for each component.
