### ISSUE TITLE
Validate personas for Techne 2.0 website

### ISSUE THREAD

**Issue by denisewildner** [SAP/techne#861]
In order to don't repeat the mistakes we did for the Techne 1.0 website, we should validate the user needs and expectations towards the website, before starting on the UX & Design.

**Comment by denisewildner** [comment]
I have just send out this questionnaire to the team to get final feedback. After this, Hana will send out the survey to our user personas to collect feedback.

**Comment by denisewildner** [comment]
Looks like the survey wasn't very fruitful. We reminded the potential users 3 times and there were only 11 participating. 5 out of 11 only completed the survey. I am attaching the results here, too.

**Comment by denisewildner** [comment]
[Responses_All_170828.pdf](https://github.com/SAP/techne/files/1263291/Responses_All_170828.pdf)

**Comment by denisewildner** [comment]
Overall outcome:
- Main Persona: **(Full-stack) developer**
- no-one came from an external link to the techne.yaas.io-Site
- 100% (= 6 people) looked for **Components**, 66.6% (= 4 people) looked for **Guidelines**

3 out of 3 people **disagreed** with: 
-  "I think that I'd need a technical guide to be able to use the Technè content."
- 2 out of 3 people **disagreed** with: 
- "I would imagine that most people would find what they are looking for on the Technè website very quickly."
- "I felt very confident using the Technè website."

"What did you need to achieve the above goals?":
- I need proper examples, **live examples** if that's possible! It's a shame that some components, like select input is barely explained. Just pasting html is not enough as I don't believe, that these components were not tested in web app env
- nothing, example was there
- Click a lot

"Were you ultimately successful in using Technè to achieve your goals?"
- Only 50% said YES

"Did anything about the Technè site make it harder that it needed to be to achieve your goals?"
- no, the elements I used it wasn't hard
- The components are not on a **single page** (like bootstrap Doku) so each component needs a roundtrip

"Are there any other UI guidelines websites you currently use or have visited?"
- Bootstrap
- Fiori & Apple (Person said: "Techne is easier")
- Google Material Design 

"What was the main thing that stopped you from achieving your goal?"
- Examples, examples, examples. In the end I got it, but it was way to much hassle. And it's not like, that I have no experience with bootstrap, I just find live examples useful
- It is hard to distinguish between patterns and components, when looking for certain elements. SO I had to click through everything before finding the right thing. Sometimes it wasn't even there.
- I had to click through a lot

"If you could wave a magic wand and have anything, what would you change that would have made your tasks easier?"
- pssssssst, examples that are live
- put everything on one page and have a good search
- Follow bootstrap or devportal or any other modern docu site with approach that the whole content for one topic is displayed on one page. Loke all components or all patterns on one page

**Comment by xak** [comment]
@denisewildner I copied your assessment to a WIKI page so this isn't lost once the story is closed.
https://github.com/SAP/techne/wiki/Survey-Results

**Comment by joseegm** [comment]
The results are documented on the wiki, thanks Zack, we can close this now and use the info when we return the focus to the website
