### ISSUE TITLE
Ops: Fix website deployment

### ISSUE THREAD

**Issue by xak** [SAP/techne#865]
Travis needs to be updated to build the new Jekyll site. The site now has no content — http://sap.github.io/techne/www

**Comment by saadmhybris** [comment]
already being worked on here - https://github.com/SAP/techne/issues/857

**Comment by xak** [comment]
@saadmhybris The new environments are not needed to fix the deployment. The Travis task builds the site and checks in `www` to `gh-pages`. Aren't you simply building into a new location now?

https://github.com/SAP/techne/blob/v2.0/.travis.yml
https://github.com/SAP/techne/blob/v2.0/ops/gulp/ghpages-deploy.js#L6

**Comment by saadmhybris** [comment]
ok, let me try this. maybe I am over complicating things...
