### ISSUE TITLE
Pkg: Implement Icons

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#870]
- [ ] Develop
- [ ] Design review
- [ ] Code review
- [ ] Merge

Goal: We have an icon system in place, but still need to componentize it.

**Comment by saadmhybris** [comment]
@LeoT7508 Quick question - 

you have defined icon sizes are 18px 26px and 32px.

Is there a specific reason why we are using 18px for regular icon size? I ask this because our base font size is 16px and it will make life easy if the base icon size is 16px as well. Please let me know if this is ok. otherwise, we may run into situations where you have to play with the positioning of the icons if used inline with text. for example text buttons with icons.

**Comment by LeoT7508** [comment]
@saadmhybris 

These sizes work with input fields. The smallest icon wouldn't be used with body copy 16px text, we have text buttons with icons, those have a different type size and won't use the small icon. The smallest icons 16px are used for tooltips & help options right now. 26px icons fit inside fields and are the standard size for check boxes and radio buttons.

**Comment by saadmhybris** [comment]
We need to go back to the font icon system we previously had. unfortunately, SVG icon system did not meet our current requirement of easy to embed and change colors on the fly.

**Comment by saadmhybris** [comment]
Implemented icons using icon fonts instead of SVG icons. Closing this issue for now.
