### ISSUE TITLE
Pkg: Implement list-group component

### ISSUE THREAD

**Issue by xak** [SAP/techne#884]
# Workflow

- [x] Develop
- [x] Design review
- [x] Code review
- [x] Merge to `dev`

# Inputs
- See background at #806
- See current [YasS list-group examples](https://sapse.invisionapp.com/d/main#/projects/boards/5484242)
- See [1.5 implementation](https://techne.yaas.io/components/Lists.html)

## Specs
- **PSD**: https://app.box.com/folder/14968986610
- **Zeplin:** https://zpl.io/VxA6xka

## Basic block structure (suggested)

The structure here can closely match the `input-group` where an `addon` can be put before or after each item.
```
.tn-list-group
	.tn-list-group__addon?
	.tn-list-group__item+
	.tn-list-group__addon?
```

# Outputs

- Base styles for the list and items
- Show an icon option after the list item text, e.g., an "X" for deleting the item.
- Since this is an [enhancement of a Bootstrap component](http://getbootstrap.com/components/#list-group), additional Bootstrap modifications may need to be accounted for.

**Comment by like-me1** [comment]
@LeoT7508 this task is ready for Dev review, could you please review it at the same time from your side? branch is: feature/884-list-group, after running "npm test" navigate to http://localhost:3030/list-group. Thanks

**Comment by LeoT7508** [comment]
@like-me1 

Im not sure if theres supposed to be a hover for the whole row, @joseegm, should the row hover how Uliana built it? Or should it be a static component with only the icon using a hover?

**Comment by saadmhybris** [comment]
The hover state for the list items should match table row hover state. 

http://sap.github.io/techne/table.html

**Comment by LeoT7508** [comment]
@saadmhybris 

Are we sure? I don't think thats how it works now here:
https://techne.yaas.io/components/Lists.html

Its a static list. 

@joseegm  Thoughts?

**Comment by xak** [comment]
@saadmhybris @LeoT7508 @joseegm There should **NOT** be hovers on the list-group.

**Comment by joseegm** [comment]
@LeoT7508 
For consistency reasons there should be hover effect on the list as well, same as the table and tree.

**Comment by LeoT7508** [comment]
@joseegm @like-me1 

Since we do want a hover then we need to change this hover affect to match what we use for tables, this hover affect is what we use for fields and drop down menus.

**Comment by joseegm** [comment]
@LeoT7508 
Yes, is the same hover as tables and the tree, with a background color. 
The hover effect on the inputs is different with only an outline.

**Comment by like-me1** [comment]
@LeoT7508 we agreed with Jose on a concept "on the flight" because the solution: "change the background color to the one we have for tables doesn't work when the row has a checkbox". But I kindly ask you guys again, provide the right concept BEFORE the ticket pushed into development. It's clear that different people have different opinions and some investigation needs to be done in advance to make the right concept. But not during the development phase. Let's try to keep it in mind for the Zeplin/PSD sources to provide hover/active/focus/disabled states if applicable. I'll try to keep it in mind before starting the ticket as well.

**Comment by LeoT7508** [comment]
@like-me1 

Id go with whatever Jose feels works best. 

About changing this on the fly, thats part of designing components, things are going to change at random times, thats part of iterating and creating design systems. We try our best to have things ironed out early on, but at times things come up later in the process and we all have to adjust accordingly, its part of what we do.

**Comment by xak** [comment]
I agree with @LeoT7508 that change is always part of the picture but I also agree with @like-me1 that we need to do better. We are missing some very simple, basic things and leaving too much discovery to the developers.

We can to revisit this. But please, please, please look at https://getbootstrap.com/docs/4.0/components/list-group/ and look at https://sapse.invisionapp.com/d/main#/projects/boards/5484242. 

Maybe what we have in Zeplin is all we need to satisfy all of our use cases but it doesn't look that way.
