### ISSUE TITLE
Pkg: Make CDN version available

### ISSUE THREAD

**Issue by xak** [SAP/techne#901]
#770 

The release process should include deploying the min version of Techne to the CDN/location.

`https://techne.yaas.io/libs/techne/2.0.0-alpha-1/techne.min.css`

**Comment by saadmhybris** [comment]
@derberg - any ideas on how we can get 2.0 alpha files up on https://techne.yaas.io/libs/techne/... ? 

do we still need to work with a bamboo plan or can we configure Travis to publish the files there?

**Comment by xak** [comment]
@derberg Even if it's FTP we can manage it in the short term. We want to do an alpha release this week and having an external link would be very helpful for testing purposes.

**Comment by derberg** [comment]
Hey, sorry for late response. First I need to know, is http://sap.github.io/techne/ is staying for tryout and sandboxing? or is it suppose to become a main page for techne and we should map it to techne.yaas.io? 
Storing file is easy, I can extend travis for ghpages or bamboo for internal hosting. I just need to know where is the techne 2.0 going to be hosted as a main page and how do I net techne.min.css, with what gulp task

**Comment by xak** [comment]
@derberg The Github pages will eventually be the main page but not until 2.0 is officially released. At that point we will want to redirect to GitHub **BUT** 1.5 will need to remain active. We'll do something like `techne.yaas.io/1.5.7`. We can provide a list of redirect reqs as we get closer to release.

For the libs, the best approach would be to copy everything in the `dist` directory. I started drafting a release process — https://github.com/SAP/techne/wiki/Release-Process. The CDN portion would be something like ...

- Make `package.version` directory at `techne.yaas.io/libs/techne/`
- Copy contents of `dist` directory to new directory

Then all CSS and fonts would be available at https://techne.yaas.io/libs/techne/2.0.0-alpha-1/`.

**Comment by derberg** [comment]
ok then, so I understand that for now you just need a quick solution and for long term we will talk about some more sophisticated automated process. 

For now, bamboo modified, it is not only doing current techne but also exposing latest techne from v2.0 branch: https://techne.yaas.io/libs/techne/2.0.0-alpha-1/techne.min.css

**Comment by saadmhybris** [comment]
@derberg thanks! we are good for now on this issue.
