### ISSUE TITLE
Contextual Menu 

### ISSUE THREAD

**Issue by LeoT7508** [SAP/techne#907]
Goal: Apply new design styles to contextual menu. 

![screen shot 2017-08-24 at 1 52 05 pm](https://user-images.githubusercontent.com/28761982/29683320-85fa95ae-88d3-11e7-9dd4-d47293785b31.png)

- [x] Visual Design

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_contextual menu](https://user-images.githubusercontent.com/28761982/29683495-2ee0a0aa-88d4-11e7-9719-ee2c376b26a8.png)

**Comment by xak** [comment]
@LeoT7508 Since this menu is often to the right of the screen, maybe the menus should open below like you have on the cards screens. Or do you want to have an option for each placement — left, bottom, right?

**Comment by LeoT7508** [comment]
@xak 

I think it would be smart to have the menu open from each side, left bottom, right, to cover all scenarios. These other menus aren't exactly the same so we might have to think about them differently when we get to them. So yes I think this might be a design for contextual menu's, since these other 2 are somewhat different.
