### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by LeoT7508** [SAP/techne#908]
Define: Apply design style to pagination. 

![screen shot 2017-08-24 at 2 01 26 pm](https://user-images.githubusercontent.com/28761982/29683671-c129c9dc-88d4-11e7-802b-482396620c8a.png)

- [ ] Visual Design

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_pagination](https://user-images.githubusercontent.com/28761982/29683754-07edc486-88d5-11e7-9f20-1bb9a1ffbe3f.png)

**Comment by xak** [comment]
@LeoT7508 Two things ...

# Please show an example of more than 3 pages, what it would look like at the front and the back ,e.g., 91 pages total, I'm on page 2, on page 23, and on page 90.

![screen shot 2017-08-25 at 9 25 07 am](https://user-images.githubusercontent.com/424119/29718440-6defdd02-8978-11e7-8bbf-45b849faf137.png)

# We have a selected state for the link buttons — https://zpl.io/aB8G102 — with the darker color and underline. All the states for link button would be appropriate here, e.g., hover, selected, disabled (>>), and be most consistent. Then we can use the "link" button for these with no special treatments.

**Comment by LeoT7508** [comment]
@xak 

![techne_2 0_pagination](https://user-images.githubusercontent.com/28761982/29726202-7b973772-8994-11e7-941f-d7fd0bedf7f7.png)
