### ISSUE TITLE
Spec cards layout for various screen sizes

### ISSUE THREAD

**Issue by xak** [SAP/techne#918]
Need to understand how cards will behave responsively. Thus far we have 2-, 3- (default), and 4-col layout options implemented for all screens.

See https://techne.yaas.io/starterpages/start.html. These changes from 3 to 2 to 1 per row.
See https://techne.yaas.io/starterpages/product-grid.html. These change from 6 to 4 to 2 per row.

What are the rules for the new implementations?

**Comment by LeoT7508** [comment]
@xak 

These files are also up on Zeplin.

![stater page - cards 1 - 3 column 300](https://user-images.githubusercontent.com/28761982/30183199-25d6f3ae-93df-11e7-86c4-30ce74047b32.png)
![stater page - cards 1 - 3 column 800](https://user-images.githubusercontent.com/28761982/30183196-25b603b0-93df-11e7-8d57-cf3282f29d7d.png)
![stater page - cards 1 - 3 column 1024](https://user-images.githubusercontent.com/28761982/30183197-25b69316-93df-11e7-969c-6db1b045b502.png)
![stater page - cards 1 - 3 column 1440](https://user-images.githubusercontent.com/28761982/30183195-25b5f596-93df-11e7-8029-a38515d5325c.png)
![stater page - cards 1 - 3 column 1580](https://user-images.githubusercontent.com/28761982/30183198-25b6fce8-93df-11e7-8156-efe819243164.png)

**Comment by xak** [comment]
@LeoT7508 You still have not accounted for the behavior of the 2- or 4-column layout. How should those behave?

**Comment by joseegm** [comment]
I think this is already done on the different card groups
