### ISSUE TITLE
Design Cards starter pages

### ISSUE THREAD

**Issue by xak** [SAP/techne#954]
We now have all the components need to build the Cards starter page — https://techne.yaas.io/starterpages/start.html

Please include responsive behaviors

**Comment by LeoT7508** [comment]
@xak 

![stater page - cards 1 - 3 column 300](https://user-images.githubusercontent.com/28761982/30183337-ac37f72c-93df-11e7-9910-73a46664dc99.png)
![stater page - cards 1 - 3 column 800](https://user-images.githubusercontent.com/28761982/30183341-ac3db1b2-93df-11e7-83aa-ee72916b1086.png)
![stater page - cards 1 - 3 column 1024](https://user-images.githubusercontent.com/28761982/30183340-ac3d0fe6-93df-11e7-83a3-af15f820ce48.png)
![stater page - cards 1 - 3 column 1440](https://user-images.githubusercontent.com/28761982/30183339-ac3c359e-93df-11e7-974c-6a4f067a7442.png)
![stater page - cards 1 - 3 column 1580](https://user-images.githubusercontent.com/28761982/30183338-ac3b189e-93df-11e7-9900-0a18a7dec741.png)
