### ISSUE TITLE
Docs: Make side nav on mobile friendly.

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#971]
<img width="379" alt="screen shot 2017-09-05 at 5 25 46 pm" src="https://user-images.githubusercontent.com/15215400/30086280-ff3d999e-925f-11e7-96da-6e77a5fbef56.png">

Goal: Make side-nav mobile-friendly by making it slide in and out of view using a hamburger menu similar to the 1.5 techne site - https://techne.yaas.io/

**Comment by joseegm** [comment]
This is outdated
