### ISSUE TITLE
Spike: Algolia search

### ISSUE THREAD

**Issue by saadmhybris** [SAP/techne#976]
Although we have a decent search capability in Jekyll it has its limitation. It will not scale with the content of the site and will dramatically slow down once we have a hefty volume of content. 

Is it possible for us to use Algolia search? it is used by bootstrap 4 site and they offer the service for free if you display "search by Algolia" sticker - https://www.algolia.com/pricing

- Can we use it? 
- Is SAP legal ok with this?
- If not, can we afford to pay for it? 

This is how bootstrap implemented search. 
<img width="375" alt="screen shot 2017-09-06 at 8 29 39 pm" src="https://user-images.githubusercontent.com/15215400/30141635-464c2a84-9342-11e7-8e87-48eacd7ea29d.png">

@derberg - have you explored this option for Wookie projects? 

@joseegm, @xak pls chime in.

**Comment by derberg** [comment]
You know my opinion, nothing is better than google custom search :P  
I didn't try algolia. I think it should be easy to get an approval for it as our commerce is already integrated with it https://devportal.yaas.io/services/beta/algoliasearch/latest/ 
Check with wombats PO for more details.

Anyway, google custom search forever:
https://kubernetes.io/docs/home/
http://loopback.io/doc/
https://devportal.yaas.io/?ft=gcs

**Comment by joseegm** [comment]
maybe later on
